/**
 * Homeward ward-list UI, Mercury-style: light surfaces, Inter variable font
 * with measured weights (420/480/530), cobalt actions, sidebar, KPI tiles
 * with a live sparkline, collapsible patient cards, a patient-centred barrier
 * graph, an Accounts-style Services rail,
 * and the activity log.
 *
 * Polls /state every 2s. Buttons: "Approve plan" (header, staff approval of
 * all proposed items), "Confirm reviewed" (clinical hold sign-off),
 * "Prepare escalation" (blocked_human handover). Each KPI tile opens a modal
 * over a blurred backdrop listing the items behind that number with what the
 * agent planned, did, verified, and the evidence it quoted. No dependencies — Node http
 * + one page. Inter loads from Google Fonts; falls back to system-ui offline.
 *
 * Colors follow the dataviz skill's fixed status palette (icon + label,
 * never color alone); text stays in ink tokens, the dot carries the color.
 *
 * Written for a clinician glancing at it: every state has a one-sentence
 * meaning, and every simulator call reads as what the agent did and what
 * the service replied (trace.ts wording). The raw request, reply and
 * idempotency key sit behind a "Show request" drop-down that stays open
 * across the poll.
 */
import { createServer } from 'node:http'
import type { BoardState, ChecklistItem, PatientRow } from '../orchestrator/model.ts'
import { approveAll, clearHold, prepareEscalation } from '../orchestrator/run.ts'

/** What each verified item does NOT prove — epistemic honesty, per item kind. */
const CAVEATS: Record<string, string> = {
  medicines: 'Collection is recorded; this does not prove adherence or ongoing supply.',
  bloods: 'Results are available; this does not constitute clinical review of those results.',
  device: 'A reading was received; this does not confirm sustained monitoring or clinical review of readings.',
  visit: 'The visit is completed; this does not confirm ongoing care-package funding or future visits.',
  summary: 'The letter reached the GP inbox; this does not confirm the GP has read or actioned it.',
  'follow-up': 'The task exists on the GP worklist; this does not confirm the review has happened.',
  'clinical-hold': 'Clinician sign-off is a human decision recorded here, not an automated judgement.',
  'care-package': 'Escalated to a human decision; nothing here resolves the funding question.',
}
const caveatFor = (id: string): string | undefined =>
  Object.entries(CAVEATS).find(([k]) => id.endsWith('-' + k))?.[1]

const mdWhen = (ms?: number) => (ms ? new Date(ms).toISOString().replace('T', ' ').slice(0, 16) + ' (sim)' : '—')

/** Consolidated per-patient discharge coordination record, as Markdown. */
export function buildReceipt(board: BoardState, patientId: string): string | undefined {
  const p = board.patients.find((x) => x.patientId === patientId)
  if (!p) return undefined
  const verified = p.items.filter((i) => i.state === 'verified').length
  const blockers = p.items.filter((i) => i.state === 'clinical_hold' || i.state === 'blocked_human')
  const open = p.items.filter((i) => !['verified', 'clinical_hold', 'blocked_human'].includes(i.state))
  const L: string[] = []
  L.push(`# Discharge coordination record — ${p.name} (${p.patientId})`)
  L.push('')
  L.push(`Generated by Homeward · world \`${board.world}\` · sim clock ${mdWhen(board.simNow)} · real time ${new Date().toISOString().slice(0, 16).replace('T', ' ')} UTC`)
  L.push('')
  L.push('## Verdict')
  L.push('')
  const ready = p.items.length > 0 && p.items.every((i) => i.state === 'verified')
  L.push(ready
    ? `**Operationally ready.** All ${p.items.length} checklist items independently verified. Final discharge remains a clinical decision.`
    : `**Not yet confirmed.** ${verified} of ${p.items.length} items verified.` +
      (blockers.length ? ` Outstanding human decisions: ${blockers.map((b) => b.title).join('; ')}.` : '') +
      (open.length ? ` Still in progress: ${open.map((o) => o.title).join('; ')}.` : ''))
  L.push('')
  L.push(`Patient context: ${p.conditions.join(', ') || '—'} · stage ${p.stage ?? '—'}${p.location ? ' · ' + p.location : ''}. Recorded needs: ${p.needs.join(', ') || '—'}. Goals: ${p.goals.join(', ') || '—'}.`)
  p.items.forEach((i, n) => {
    L.push('')
    L.push(`## ${n + 1}. ${i.title}`)
    L.push('')
    L.push(`**State:** ${i.state.replace('_', ' ')} · **Owner:** ${i.owner}`)
    if (i.evidence.length) {
      L.push('')
      L.push('**Detected from the record:**')
      for (const e of i.evidence) L.push(`- "${e.quote}" — \`${e.site} ${e.resourceId}\``)
    }
    if (i.proposedAction) { L.push(''); L.push(`**Plan:** ${i.proposedAction}`) }
    if (i.approval) L.push(`**Approved by:** ${i.approval.by} at ${mdWhen(i.approval.at)}`)
    if (i.humanReason) { L.push(''); L.push(`**Why a human is required:** ${i.humanReason}`) }
    const wire = (board.trace ?? []).filter((t) => t.idempotencyKey && t.idempotencyKey.includes(i.id))
    if (wire.length) {
      L.push('')
      L.push('**Actions executed (wire record):**')
      L.push('')
      L.push('| Time | What the agent did | Result | Call |')
      L.push('| --- | --- | --- | --- |')
      const cell = (s: string) => s.replace(/\|/g, '\\|')
      for (const t of wire) {
        L.push(`| ${new Date(t.at).toTimeString().slice(0, 8)} | ${cell(t.headline ?? t.action ?? t.method)} | ${cell(t.outcome ?? t.got ?? (t.ok ? 'OK' : 'failed'))} | \`${t.action ?? t.method}\` ${t.ok ? `HTTP ${t.status}` : `FAILED ${t.status || ''}`} |`)
      }
    }
    if (i.resolution) L.push(`
Idempotency key: \`${i.resolution.idempotencyKey}\``)
    if (i.generated) { L.push(''); L.push(`**Drafting provenance:** ${i.generated === 'model' ? 'content written by the live model' : 'canned fallback (model unavailable)'}`) }
    if (i.verification) {
      L.push('')
      L.push(`**Independent verification:** ${i.verification.passed ? 'PASSED' : 'NOT YET'} — ${i.verification.observed} at ${mdWhen(i.verification.atSimTime)}`)
    }
    if (i.escalation) {
      L.push('')
      L.push(`**Escalated to:** ${i.escalation.responsibleTeam} — ${i.escalation.nextAction}`)
      L.push(`> ${i.escalation.note}`)
    }
    const cav = caveatFor(i.id)
    if (cav && ['verified', 'clinical_hold', 'blocked_human'].includes(i.state)) {
      L.push(''); L.push(`**This does not prove:** ${cav}`)
    }
  })
  L.push('')
  L.push('---')
  L.push('')
  L.push('Synthetic simulator data (NHS-SIM). Every action above was executed against the simulator and independently re-read; RECORD quotes are verbatim from the record. Final discharge decisions rest with the responsible clinician.')
  L.push('')
  return L.join('\n')
}

export const PAGE = `<!doctype html>
<html lang="en"><head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Homeward</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400..700&display=swap" rel="stylesheet">
<style>
  :root{
    --page:#f9f9f7; --surface:#ffffff; --ink:#0b0b0b; --ink-2:#52514e; --ink-3:#898781;
    --hairline:rgba(11,11,11,0.10); --grid:#e1e0d9;
    --accent:#5266eb; --accent-soft:rgba(82,102,235,0.08);
    --good:#0ca30c; --warning:#fab219; --serious:#ec835a; --critical:#d03b3b;
    --radius:12px;
  }
  *{box-sizing:border-box;margin:0}
  body{font-family:Inter,system-ui,-apple-system,"Segoe UI",sans-serif;background:var(--page);color:var(--ink);
       font-size:14px;line-height:1.45;-webkit-font-smoothing:antialiased}
  a{color:inherit;text-decoration:none}

  .app{display:grid;grid-template-columns:224px 1fr;min-height:100vh}
  .sidebar{background:var(--surface);border-right:1px solid var(--hairline);padding:20px 14px;
           display:flex;flex-direction:column;gap:2px;position:sticky;top:0;height:100vh}
  .brand{display:flex;align-items:center;gap:10px;padding:4px 8px 18px}
  .brand .mark{width:30px;height:30px;border-radius:8px;background:linear-gradient(135deg,#5266eb,#7a8cf0);
               display:grid;place-items:center;color:#fff;font-weight:530;font-size:13px}
  .brand .name{font-weight:480;font-size:14px}
  .brand .sub{font-size:11px;color:var(--ink-3)}
  .nav-item{display:flex;align-items:center;gap:10px;padding:8px 10px;border-radius:8px;color:var(--ink-2);
            font-weight:420;cursor:pointer}
  .nav-item.active{background:var(--accent-soft);color:var(--accent);font-weight:480}
  .nav-item:hover:not(.active){background:#f4f4f1}
  .psearch{margin:2px 4px 10px;padding:7px 12px;font:inherit;font-size:12px;border:1px solid var(--grid);
           border-radius:8px;width:calc(100% - 8px);background:#fbfbf9;color:var(--ink)}
  .psearch:focus{outline:none;border-color:var(--accent)}
  .plist-label{font-size:10px;font-weight:600;letter-spacing:.06em;text-transform:uppercase;color:var(--ink-3);
               padding:4px 10px 6px}
  .pat{display:flex;align-items:center;gap:9px;padding:8px 10px;border-radius:8px;cursor:pointer;border-left:3px solid transparent}
  .pat:hover{background:#f4f4f1}
  .pat.sel{background:var(--accent-soft);border-left-color:var(--accent)}
  .pat .avatar{width:28px;height:28px;font-size:11px}
  .pat .pn{font-size:13px;font-weight:480;line-height:1.2}
  .pat .pm{font-size:10.5px;color:var(--ink-3);white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
  .pat .pdot{margin-left:auto;width:9px;height:9px;border-radius:50%;flex:none}
  .hero{background:var(--surface);border:1px solid var(--hairline);border-radius:var(--radius);
        padding:18px 20px;margin-bottom:14px;box-shadow:0 1px 2px rgba(11,11,11,0.03)}
  .hero .q{font-size:12px;font-weight:600;letter-spacing:.05em;text-transform:uppercase;color:var(--ink-3)}
  .hero h2{font-size:20px;font-weight:480;margin:2px 0 10px}
  .hero .verdict{font-size:22px;font-weight:530;letter-spacing:-0.01em}
  .hero .verdict.no{color:var(--critical)}
  .hero .verdict.yes{color:var(--good)}
  .hero .verdict.warn{color:#7a5605}
  .hero .vsub{font-size:13.5px;font-weight:480;margin-top:4px}
  .hero .vwhat{font-size:13px;color:var(--ink-2);margin-top:6px;line-height:1.55}
  .sidebar .foot{margin-top:auto;padding:10px;font-size:12px;color:var(--ink-3);border-top:1px solid var(--grid)}
  .sidebar .foot b{color:var(--ink-2);font-weight:480}

  .main{padding:28px 36px;max-width:1140px}
  .header{display:flex;align-items:flex-end;justify-content:space-between;gap:16px}
  h1{font-size:22px;font-weight:480;letter-spacing:0.01em}
  .subtitle{color:var(--ink-3);font-size:13px;margin-top:2px}
  button.primary{font:inherit;font-size:13px;font-weight:480;color:#fff;background:var(--accent);
                 border:none;border-radius:999px;padding:9px 20px;cursor:pointer;white-space:nowrap}
  button.primary:hover{filter:brightness(1.06)}
  button.ghost{font:inherit;font-size:12px;font-weight:480;color:var(--ink-2);background:var(--surface);
               border:1px solid var(--hairline);border-radius:999px;padding:8px 16px;cursor:pointer;white-space:nowrap}
  button.ghost:hover{background:#f4f4f1}
  .wire{font-family:ui-monospace,SFMono-Regular,monospace;font-size:11px;display:flex;gap:8px;align-items:baseline;
        padding:5px 0;border-top:1px solid var(--grid);color:var(--ink-2)}
  .wire .m{min-width:38px;font-weight:600}
  .wire .m.post{color:var(--accent)}
  .wire .bad{color:var(--critical)}
  .wire .k{color:var(--ink-3)}
  .wire code{background:#f4f4f1;border-radius:4px;padding:0 4px}
  .kv{display:grid;grid-template-columns:96px 1fr;gap:0 14px;padding:8px 0;border-top:1px solid var(--grid);align-items:baseline}
  .kv:first-of-type{border-top:none}
  .kv .k{font-size:12px;color:var(--ink-3);font-weight:420}
  .kv .v{font-size:13px;color:var(--ink);line-height:1.5}
  .kv .v code{font-family:ui-monospace,monospace;font-size:11px;background:#f4f4f1;border-radius:4px;padding:1px 5px}
  .call{border:1px solid var(--grid);border-radius:8px;padding:10px 14px;margin-top:8px}
  .call .head{display:flex;gap:10px;align-items:baseline;font-size:12px;flex-wrap:wrap}
  .call .head .t{color:var(--ink-3);font-variant-numeric:tabular-nums}
  .call .head .m{font-weight:600;color:var(--accent)}
  .call .head .m.get{color:var(--ink-3)}
  .call .head .a{font-weight:480}
  .call .head .ok{color:var(--good);font-weight:480}
  .call .head .fail{color:var(--critical);font-weight:480}
  .call pre{background:#f6f6f4;border-radius:6px;padding:8px 10px;font-size:11px;line-height:1.5;
            white-space:pre-wrap;word-break:break-all;margin:8px 0 0;font-family:ui-monospace,monospace;color:var(--ink-2)}
  .call .meta{font-size:11px;color:var(--ink-3);margin-top:6px;word-break:break-all}
  .call .say{display:grid;grid-template-columns:16px 58px minmax(0,1fr);gap:8px;align-items:baseline;font-size:13px}
  .call .say .ic{width:16px;height:16px;border-radius:50%;display:grid;place-items:center;font-size:10px;font-weight:530;
                 color:#fff;background:var(--good);align-self:start;line-height:1}
  .call.read .say .ic{background:#c9c8c1}
  .call.bad .say .ic{background:var(--critical)}
  .call .say .t{color:var(--ink-3);font-size:12px;font-variant-numeric:tabular-nums;white-space:nowrap}
  .call .say .what{color:var(--ink);font-weight:420}
  .call.read .say .what{color:var(--ink-2)}
  .call .say .out{display:block;color:var(--ink-3);font-size:12px;margin-top:1px}
  .call.bad .say .out{color:var(--critical)}
  .call.read{padding:6px 14px;border-color:transparent;margin-top:2px}
  details.reqdd{margin:4px 0 0 82px}
  details.reqdd summary{cursor:pointer;color:var(--accent);font-size:11px;font-weight:480;list-style:none;
                       display:flex;width:max-content;align-items:center;gap:4px;user-select:none}
  details.reqdd summary::-webkit-details-marker{display:none}
  details.reqdd summary::before{content:'▸';font-size:10px}
  details.reqdd[open] summary::before{content:'▾'}
  details.reqdd .head{margin-top:8px}
  .stmt{font-size:12px;color:var(--ink-2);margin-top:6px;font-style:normal}

  .kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin:22px 0}
  .kpi{background:var(--surface);border:1px solid var(--hairline);border-radius:var(--radius);padding:14px 16px;
       position:relative;overflow:hidden}
  .kpi .label{font-size:12px;color:var(--ink-3);font-weight:420}
  .kpi .value{font-size:26px;font-weight:530;letter-spacing:-0.01em;margin-top:2px}
  .kpi .hint{font-size:11px;color:var(--ink-3)}
  .kpi.has-spark{padding-bottom:40px}
  .kpi{cursor:pointer;transition:border-color .12s,box-shadow .12s}
  .kpi:hover,.kpi:focus-visible{border-color:var(--accent);box-shadow:0 0 0 3px var(--accent-soft);outline:none}
  .kpi .more{position:absolute;top:12px;right:14px;font-size:11px;color:var(--ink-3)}

  .modal-backdrop{position:fixed;inset:0;z-index:50;display:none;place-items:center;padding:24px;
                  background:rgba(11,11,11,0.28);backdrop-filter:blur(6px);-webkit-backdrop-filter:blur(6px)}
  .modal-backdrop.open{display:grid}
  .modal{background:var(--surface);border:1px solid var(--hairline);border-radius:14px;width:min(760px,100%);
         max-height:84vh;overflow:auto;padding:20px 24px 24px;box-shadow:0 20px 60px rgba(11,11,11,0.18)}
  .modal-head{display:flex;align-items:center;gap:12px;margin-bottom:4px}
  .modal-head h2{font-size:17px;font-weight:480}
  .modal-head .sub{color:var(--ink-3);font-size:12px;margin-top:2px}
  .modal-head button{margin-left:auto}
  .modal .group{margin-top:16px}
  .modal .group h3{font-size:13px;font-weight:480;display:flex;gap:8px;align-items:baseline}
  .modal .group h3 span{color:var(--ink-3);font-size:11px;font-weight:420}
  .mi{padding:10px 0;border-top:1px solid var(--grid)}
  .mi .row{display:flex;align-items:baseline;gap:10px}
  .mi .detail{margin:6px 0 0 0;padding-left:8px;border-left:2px solid var(--grid);font-size:12px;color:var(--ink-2)}
  .mi .detail>div{margin-top:3px}
  .mi .detail b{font-weight:480;color:var(--ink)}
  .mi .detail code{font:inherit;font-size:11px;color:var(--ink-3)}
  .mi .trace{color:var(--ink-3);font-variant-numeric:tabular-nums}
  .modal .empty{color:var(--ink-3);font-size:13px;padding:18px 0}
  .kpi svg{position:absolute;left:0;right:0;bottom:0;width:100%;height:28px;display:block}

  .content{display:block}
  .card{background:var(--surface);border:1px solid var(--hairline);border-radius:var(--radius);
        padding:18px 20px;margin-bottom:14px;box-shadow:0 1px 2px rgba(11,11,11,0.03)}
  .rail .card{padding:16px 18px}
  .rail h2,.log-card h2{font-size:13px;font-weight:480;margin-bottom:6px}

  .patient-card{padding:0;overflow:hidden;transition:border-color .16s}
  .patient-card.expanded{border-color:rgba(11,11,11,0.16)}
  .patient-head{display:flex;align-items:center;gap:12px;flex-wrap:wrap;width:100%;padding:16px 18px;
                border:0;background:transparent;color:inherit;text-align:left;font:inherit;cursor:pointer}
  .patient-head:hover{background:#fbfbf9}
  .patient-head:focus-visible{outline:2px solid var(--accent);outline-offset:-2px}
  .avatar{width:34px;height:34px;border-radius:50%;background:rgba(82,102,235,0.10);color:var(--accent);
          display:grid;place-items:center;font-weight:480;font-size:13px;flex:none}
  .patient-name{font-weight:480;font-size:15px}
  .patient-meta{color:var(--ink-3);font-size:12px}
  .ready-pill{margin-left:auto;display:flex;align-items:center;gap:10px}
  .ready-pill .count{font-size:12px;color:var(--ink-2);font-weight:420;white-space:nowrap}
  .bar{width:110px;height:6px;border-radius:3px;background:var(--grid);overflow:hidden}
  .bar>i{display:block;height:100%;background:var(--good);border-radius:3px}
  .chevron{width:20px;height:20px;display:grid;place-items:center;color:var(--ink-3);font-size:14px;line-height:1;
           transition:transform .16s,color .16s;flex:none}
  .patient-card.expanded .chevron{transform:rotate(180deg);color:var(--ink)}

  .items{margin-top:12px}
  .item{display:flex;align-items:baseline;gap:10px;padding:9px 0;border-top:1px solid var(--grid);cursor:pointer}
  .item:hover{background:#fbfbf9}
  .tag{font-size:9px;font-weight:600;letter-spacing:.05em;text-transform:uppercase;border-radius:4px;
       padding:1px 5px;vertical-align:1px;white-space:nowrap}
  .tag.rec{background:#efeeea;color:#5c5a55}
  .tag.ai{background:var(--accent-soft);color:var(--accent)}
  .tag.sim{background:rgba(12,163,12,0.10);color:#0a7a0a}
  .legend{display:flex;gap:10px;align-items:center;font-size:11px;color:var(--ink-2);margin-left:auto;flex-wrap:wrap}
  .legend span{display:inline-flex;gap:5px;align-items:center}
  .chip{display:inline-flex;align-items:center;gap:6px;padding:2px 9px;border-radius:999px;
        font-size:11px;font-weight:480;color:var(--ink-2);background:#f4f4f1;flex:none;min-width:92px;justify-content:center}
  .chip .dot{width:7px;height:7px;border-radius:50%;flex:none}
  .owner{font-size:11px;color:var(--ink-3);min-width:76px;font-weight:420}
  .item .title{font-weight:420}
  .evidence{color:var(--ink);font-size:12px;font-style:normal}
  .err{color:var(--critical);font-size:12px}
  .item .right{margin-left:auto;flex:none}
  button.confirm{font:inherit;font-size:12px;font-weight:480;color:var(--accent);background:var(--surface);
                 border:1px solid var(--accent);border-radius:999px;padding:4px 14px;cursor:pointer}
  button.confirm:hover{background:var(--accent-soft)}
  .escalation{margin-top:6px;padding:8px 10px;border:1px solid var(--hairline);border-left:3px solid var(--accent);
              border-radius:6px;font-size:12px;color:var(--ink-2);background:var(--accent-soft)}

  .graph-wrap{border-top:1px solid var(--grid);padding:16px 18px 18px;background:var(--surface)}
  .graph-toolbar{display:flex;align-items:center;justify-content:space-between;gap:14px;margin-bottom:8px}
  .graph-title{font-size:12px;font-weight:480;color:var(--ink-2)}
  .legend{display:flex;align-items:center;gap:12px;flex-wrap:wrap;color:var(--ink-3);font-size:10px}
  .legend span{display:inline-flex;align-items:center;gap:5px;white-space:nowrap}
  .legend i{width:7px;height:7px;border-radius:50%;display:block}
  .dependency-graph{height:430px;position:relative;isolation:isolate;overflow:hidden}
  .dependency-lines{position:absolute;inset:0;width:100%;height:100%;z-index:0;overflow:visible}
  .dependency-lines line{stroke-width:1;vector-effect:non-scaling-stroke;opacity:.26}
  .graph-hub{position:absolute;left:50%;top:50%;transform:translate(-50%,-50%);z-index:2;width:58px;height:58px;
             border-radius:50%;background:var(--surface);border:1px solid rgba(82,102,235,.52);display:grid;place-items:center}
  .graph-hub .person{position:relative;width:11px;height:11px;border:1.5px solid var(--accent);border-radius:50%;margin-top:-9px}
  .graph-hub .person:after{content:"";position:absolute;width:23px;height:12px;left:-7.5px;top:15px;border:1.5px solid var(--accent);
                           border-bottom:0;border-radius:14px 14px 0 0}
  .graph-node{--node-color:var(--ink-3);position:absolute;transform:translate(-50%,-50%);z-index:2;width:166px;min-height:62px;
              border:1px solid var(--hairline);border-left:3px solid var(--node-color);border-radius:10px;background:var(--surface);
              padding:10px 12px;cursor:pointer;text-align:left;transition:background .12s,border-color .12s}
  .graph-node:hover,.graph-node:focus-visible{background:#fafaf8;border-color:rgba(11,11,11,.20);border-left-color:var(--node-color);outline:none}
  .graph-node .node-top{display:flex;align-items:center;justify-content:space-between;gap:7px;margin-bottom:5px}
  .graph-node .node-owner{font-size:9px;font-weight:600;letter-spacing:.055em;text-transform:uppercase;color:var(--ink-3)}
  .graph-node .node-title{font-size:12px;line-height:1.3;font-weight:480}
  .graph-node .node-action{margin-top:7px;font:inherit;font-size:10px;font-weight:530;color:var(--accent);background:transparent;
                           border:0;padding:0;cursor:pointer}
  .graph-node.not-started{--node-color:#a5a39c}
  .graph-node.in-progress{--node-color:var(--warning)}
  .graph-node.stuck{--node-color:var(--critical)}
  .graph-node.completed{--node-color:var(--good)}
  .graph-insights{border-top:1px solid var(--grid);margin-top:6px;padding-top:10px;font-size:11px;color:var(--ink-2)}
  .graph-insights b{font-weight:480;color:var(--ink)}

  @media(max-width:900px){
    .app{grid-template-columns:1fr}.sidebar{display:none}.main{padding:22px 18px}.content{grid-template-columns:1fr}.rail{display:none}
    .kpis{grid-template-columns:repeat(2,1fr)}.dependency-graph{height:auto;display:grid;grid-template-columns:1fr 1fr;gap:8px;padding-top:104px}
    .dependency-lines{display:none}.graph-hub{top:18px;transform:translateX(-50%)}
    .graph-node{position:relative!important;left:auto!important;top:auto!important;transform:none!important;width:auto;min-height:62px}
  }
  @media(max-width:560px){.dependency-graph{grid-template-columns:1fr}.graph-toolbar{align-items:flex-start;flex-direction:column}.ready-pill .bar{display:none}}

  #actions{display:flex;flex-direction:column;gap:8px;margin:0 0 14px}
  .acard{display:flex;align-items:center;gap:12px;background:var(--surface);border:1px solid var(--hairline);
         border-left:4px solid var(--accent);border-radius:var(--radius);padding:12px 16px;
         box-shadow:0 1px 2px rgba(11,11,11,0.03)}
  .acard .who{font-size:10px;font-weight:600;letter-spacing:.05em;text-transform:uppercase;
              color:var(--accent);background:var(--accent-soft);border-radius:4px;padding:2px 7px;flex:none}
  .acard .t{font-weight:480;font-size:14px}
  .acard .sub{font-size:12px;color:var(--ink-3)}
  .acard .act{margin-left:auto;flex:none}
  .acard.done{border-left-color:var(--good);color:var(--ink-2)}
  .viewbar{display:flex;align-items:center;justify-content:space-between;gap:14px;margin:0 0 14px}
  .seg{display:inline-flex;background:#efeeea;border-radius:999px;padding:3px}
  .seg button{font:inherit;font-size:12px;font-weight:480;border:none;background:transparent;border-radius:999px;
              padding:5px 16px;cursor:pointer;color:var(--ink-2)}
  .seg button.active{background:var(--surface);color:var(--ink);box-shadow:0 1px 2px rgba(11,11,11,0.10)}
  .ptable{background:var(--surface);border:1px solid var(--hairline);border-radius:var(--radius);overflow:hidden;
          box-shadow:0 1px 2px rgba(11,11,11,0.03);margin-bottom:14px}
  .phead,.prow{display:grid;grid-template-columns:230px 230px 1fr 120px;gap:14px;padding:12px 18px;align-items:center}
  .phead{font-size:10.5px;font-weight:480;letter-spacing:.06em;text-transform:uppercase;color:var(--ink-3);
         border-bottom:1px solid var(--grid);padding:10px 18px}
  .prow{border-top:1px solid var(--grid);border-left:3px solid transparent;cursor:pointer}
  .prow:first-of-type{border-top:none}
  .prow:hover{background:#fbfbf9}
  .prow.sev-bad{border-left-color:var(--critical)}
  .prow.sev-warn{border-left-color:var(--warning)}
  .prow.sev-good{border-left-color:var(--good)}
  .pcol{display:flex;align-items:center;gap:10px;min-width:0}
  .pcol .nm{font-weight:480;font-size:14px}
  .pcol .sub{font-size:11.5px;color:var(--ink-3);white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
  .schip{display:inline-flex;align-items:center;gap:6px;border-radius:999px;padding:3px 11px;font-size:12px;font-weight:480}
  .schip .dot{width:7px;height:7px;border-radius:50%}
  .schip.bad{background:rgba(208,59,59,0.08);color:#a32f2f}
  .schip.warn{background:rgba(250,178,25,0.12);color:#7a5605}
  .schip.good{background:rgba(12,163,12,0.10);color:#0a7a0a}
  .schip.plain{background:#f4f4f1;color:var(--ink-2)}
  .need{display:inline-flex;align-items:center;gap:6px;border:1px solid var(--grid);border-radius:999px;
        padding:2px 10px;font-size:11.5px;color:var(--ink-2);background:var(--surface);margin:2px 6px 2px 0;white-space:nowrap}
  .need .dot{width:6px;height:6px;border-radius:50%}
  .need:hover{border-color:rgba(11,11,11,0.22)}
  .need .more{color:var(--ink-3)}
  .rlink{font-size:11px;color:var(--ink-3);text-decoration:none;border-bottom:1px dotted var(--grid)}
  .rlink:hover{color:var(--accent)}
  .lrow{display:flex;align-items:baseline;gap:10px;padding:10px 18px;border-top:1px solid var(--grid);cursor:pointer;background:var(--surface)}
  .lrow:hover{background:#fbfbf9}
  .lrow .q{color:var(--ink-2);font-size:12px}
  .svc{display:flex;align-items:center;gap:10px;padding:8px 0;border-top:1px solid var(--grid)}
  .svc:first-of-type{border-top:none}
  .svc .ic{width:28px;height:28px;border-radius:50%;background:rgba(82,102,235,0.10);color:var(--accent);
           display:grid;place-items:center;font-size:10px;font-weight:480;flex:none}
  .svc .nm{font-size:13px;font-weight:420}
  .svc .n{margin-left:auto;font-size:12px;color:var(--ink-2);font-variant-numeric:tabular-nums}
  .svc .n.clear{color:var(--ink-3)}

  .status{display:inline-flex;align-items:center;gap:8px;font-size:12px;color:var(--ink-2);
          background:var(--surface);border:1px solid var(--hairline);border-radius:999px;padding:6px 14px}
  .status.quiet{color:var(--ink-3)}
  .spin{width:13px;height:13px;border:2px solid var(--accent-soft);border-top-color:var(--accent);
        border-radius:50%;animation:spin .8s linear infinite;flex:none}
  @keyframes spin{to{transform:rotate(360deg)}}
  .loading-hero{display:flex;flex-direction:column;align-items:center;gap:16px;padding:110px 0;color:var(--ink-2)}
  .loading-hero .spin{width:34px;height:34px;border-width:3px}
  .loading-hero .what{font-size:14px;font-weight:480}
  .loading-hero .why{font-size:12px;color:var(--ink-3)}
  #wiretrace{display:flex;flex-direction:column;max-height:340px;overflow:auto}
  #wiretrace .w{font-family:ui-monospace,monospace;font-size:10.5px;color:var(--ink-2);
                display:flex;gap:6px;align-items:baseline;padding:5px 0;border-top:1px solid var(--grid)}
  #wiretrace .w:first-child{border-top:none}
  #wiretrace .t{color:var(--ink-3);flex:none;font-variant-numeric:tabular-nums}
  #wiretrace .m{font-weight:600;flex:none}
  #wiretrace .m.post{color:var(--accent)}
  #wiretrace .a{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
  #wiretrace .st{margin-left:auto;flex:none;color:var(--ink-3)}
  #wiretrace .st.bad{color:var(--critical)}
</style></head><body>
<div class="app">
  <aside class="sidebar">
    <div class="brand"><div class="mark">H</div>
      <div><div class="name">Homeward</div><div class="sub">discharge coordination</div></div></div>
    <input class="psearch" id="psearch" type="search" placeholder="Find a patient or SIM number"
           oninput="patFilter=this.value;render(lastState)">
    <div class="plist-label" id="plistLabel">Patients</div>
    <div id="plist"></div>
    <div style="height:10px"></div>
    <div class="nav-item" onclick="openModal('trace')">Full trace</div>
    <div class="foot">world <b id="world">—</b><br>sim clock <b id="clock">—</b></div>
  </aside>
  <main class="main">
    <div class="header">
      <div><h1>Ward round</h1></div>
      <span id="status"></span>
    </div>
    <div class="kpis" id="kpis"></div>
    <div class="viewbar">
      <span></span>
      <span class="legend"><span title="Plan drafted; nothing happens until staff approve it"><i style="background:#a5a39c"></i>Not started</span><span title="Approved; the agent is acting in the owning service, then checking its records after time moves"><i style="background:var(--warning)"></i>In progress</span><span title="Needs a person: a clinical hold, an external decision, or an action that failed"><i style="background:var(--critical)"></i>Stuck</span><span title="Confirmed complete in the owning service's own records"><i style="background:var(--good)"></i>Completed</span></span>
    </div>
    <div class="content">
      <div id="board"></div>
    </div>
  </main>
</div>
<div class="modal-backdrop" id="modal" onclick="if (event.target === this) closeModal()">
  <div class="modal" role="dialog" aria-modal="true" aria-labelledby="modalTitle">
    <div class="modal-head"><div><h2 id="modalTitle"></h2><div class="sub" id="modalSub"></div></div>
      <div class="legend"><span><span class="tag rec">record</span> from the sim record</span>
        <span><span class="tag ai">AI</span> model-written</span>
        <span><span class="tag sim">sim</span> service response</span></div>
      <button class="confirm" onclick="closeModal()">Close</button></div>
    <div id="modalBody"></div>
  </div>
</div>
<script>
const CAVEATS = ${JSON.stringify(CAVEATS)}
const caveatFor = (id) => { const e = Object.entries(CAVEATS).find(([k]) => id.endsWith('-' + k)); return e && e[1] }
const META = {
  proposed:               { label: 'Not started', color: '#a5a39c' },
  approved:               { label: 'In progress', color: 'var(--warning)' },
  resolving:              { label: 'Working',    color: 'var(--warning)' },
  awaiting_verification:  { label: 'Verifying',  color: 'var(--warning)' },
  verified:               { label: 'Completed',  color: 'var(--good)' },
  failed:                 { label: 'Stuck',      color: 'var(--critical)' },
  clinical_hold:          { label: 'Clinical hold', color: 'var(--critical)' },
  blocked_human:          { label: 'Human decision', color: 'var(--critical)' },
}
const SERVICES = {
  gp: 'GP Records', hospital: 'Hospital EPR', pharmacy: 'Pharmacy', community: 'Community Care',
  diagnostics: 'Diagnostics', wearables: 'Home Health', clinician: 'Clinician',
}
const OWNER_LABEL = {
  gp: 'GP', hospital: 'Hospital', pharmacy: 'Pharmacy', community: 'Community',
  diagnostics: 'Diagnostics', wearables: 'Home Health', clinician: 'Clinician',
}
const OPEN = ['proposed','approved','resolving','awaiting_verification','failed']
const esc = (s) => String(s ?? '').replace(/[&<>"]/g, (c) => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))
const q = (s) => esc(String(s ?? '').replace(/"/g, ''))
// How the service is named inside a sentence ("acting in the pharmacy").
const SERVICE_IN_PROSE = {
  gp: 'GP practice', hospital: 'hospital', pharmacy: 'pharmacy', community: 'community team',
  diagnostics: 'diagnostics service', wearables: 'home monitoring service', clinician: 'clinician',
}
// One sentence per state: what it means and who is doing what.
const STATE_HELP = {
  proposed:              (svc) => 'Not started. Plan drafted; nothing happens until staff approve it.',
  approved:              (svc) => 'In progress. Approved; the agent will act in the ' + svc + ' on its next round.',
  resolving:             (svc) => 'In progress. The agent is acting in the ' + svc + ' right now.',
  awaiting_verification: (svc) => 'In progress. Done in the ' + svc + '; will be checked against its own records once time has moved.',
  verified:              (svc) => 'Completed. Confirmed in the ' + svc + "'s own records.",
  failed:                (svc) => 'Stuck. The action could not be completed; a person needs to look at this.',
  clinical_hold:         (svc) => 'Stuck. Only a clinician can clear this; the agent will not.',
  blocked_human:         (svc) => 'Stuck. Needs a decision no system can make.',
}
const stateHelp = (i) => {
  const h = STATE_HELP[i.state]
  if (!h) return ''
  if (i.state === 'verified' && i.owner === 'clinician' && i.verification) return 'Completed. ' + esc(String(i.verification.observed).replace(/^cleared/, 'Cleared')) + '.'
  return h(SERVICE_IN_PROSE[i.owner] || i.owner)
}
const chip = (state) => {
  const m = META[state] || { label: state, color: 'var(--ink-3)' }
  const help = STATE_HELP[state] ? STATE_HELP[state]('owning service') : ''
  return '<span class="chip" title="' + esc(help) + '"><span class="dot" style="background:' + m.color + '"></span>' + m.label + '</span>'
}
const GRAPH_STATE = {
  proposed:              { key: 'not-started', label: 'Not started', color: '#a5a39c' },
  approved:              { key: 'in-progress', label: 'In progress', color: 'var(--warning)' },
  resolving:             { key: 'in-progress', label: 'In progress', color: 'var(--warning)' },
  awaiting_verification: { key: 'in-progress', label: 'In progress', color: 'var(--warning)' },
  failed:                { key: 'stuck', label: 'Stuck', color: 'var(--critical)' },
  clinical_hold:         { key: 'stuck', label: 'Stuck', color: 'var(--critical)' },
  blocked_human:         { key: 'stuck', label: 'Stuck', color: 'var(--critical)' },
  verified:              { key: 'completed', label: 'Completed', color: 'var(--good)' },
}
const graphState = (state) => GRAPH_STATE[state] || GRAPH_STATE.proposed
let currentView = 'graph'
let selectedPatient = null
let patFilter = ''
function setView(v) { currentView = v; if (lastState) render(lastState) }
const SHORT = {
  'clinical-hold': 'Clinical review', medicines: 'Discharge medicines', bloods: 'Blood monitoring',
  device: 'Home monitoring', visit: 'Home support visit', summary: 'Discharge summary',
  'follow-up': 'GP follow-up', 'care-package': 'Care package funding',
}
const shortTitle = (i) => { const e = Object.entries(SHORT).find(([k]) => i.id.endsWith('-' + k)); return e ? e[1] : i.title.slice(0, 28) }
const needDot = (st) =>
  st === 'failed' ? 'var(--critical)' :
  st === 'blocked_human' || st === 'clinical_hold' ? 'var(--accent)' :
  ['approved', 'resolving', 'awaiting_verification'].includes(st) ? 'var(--warning)' : '#a5a39c'
let expandedPatientId = null
let initialExpansionSet = false
function togglePatient(id) {
  expandedPatientId = expandedPatientId === id ? null : id
  if (lastState) render(lastState)
}
const taskTitle = (item) => {
  const id = item.id.toLowerCase()
  if (id.endsWith('clinical-hold')) return 'Clinical review'
  if (id.endsWith('medicines')) return 'Discharge medicines'
  if (id.endsWith('bloods')) return 'Blood monitoring'
  if (id.endsWith('device')) return 'Home monitoring'
  if (id.endsWith('visit')) return 'Home support visit'
  if (id.endsWith('summary')) return 'Discharge summary'
  if (id.endsWith('follow-up')) return 'GP follow-up'
  if (id.endsWith('care-package')) return 'Care package'
  return item.title
}
function graphForPatient(p) {
  const count = Math.max(p.items.length, 1)
  const positions = p.items.map((_, index) => {
    const angle = (-Math.PI / 2) + (index * Math.PI * 2 / count)
    return { x: 50 + Math.cos(angle) * 33, y: 50 + Math.sin(angle) * 36 }
  })
  const lines = p.items.map((i, index) => {
    const pos = positions[index]
    return '<line x1="50%" y1="50%" x2="' + pos.x.toFixed(2) + '%" y2="' + pos.y.toFixed(2) +
      '%" style="stroke:' + graphState(i.state).color + '" />'
  }).join('')
  const nodes = p.items.map((i, index) => {
    const pos = positions[index]
    const state = graphState(i.state)
    const label = taskTitle(i)
    const action = i.state === 'clinical_hold'
      ? '<button class="node-action" data-id="' + esc(i.id) + '" onclick="event.stopPropagation();clearHold(this.dataset.id)">Confirm reviewed</button>'
      : (i.state === 'blocked_human' && !i.escalation
        ? '<button class="node-action" data-id="' + esc(i.id) + '" onclick="event.stopPropagation();escalate(this.dataset.id)">Prepare escalation</button>'
        : '')
    return '<div class="graph-node ' + state.key + '" role="button" tabindex="0" data-id="' + esc(i.id) + '" ' +
      'aria-label="' + q((OWNER_LABEL[i.owner] || i.owner) + ': ' + label + '. ' + state.label) + '" title="' + q(i.title) + '" ' +
      'style="left:' + pos.x.toFixed(2) + '%;top:' + pos.y.toFixed(2) + '%" ' +
      'onclick="itemStory(this.dataset.id)" onkeydown="if(event.keyCode===13||event.keyCode===32){event.preventDefault();itemStory(this.dataset.id)}">' +
      '<div class="node-top"><span class="node-owner">' + (OWNER_LABEL[i.owner] || esc(i.owner)) + '</span></div>' +
      '<div class="node-title">' + esc(label) + '</div>' + action + '</div>'
  }).join('')
  const insights = (p.insights || []).length
    ? '<div class="graph-insights"><b>Agent observations:</b> ' + p.insights.map((n) => esc(n.title)).join(' · ') + '</div>'
    : ''
  return '<div class="graph-wrap"><div class="graph-toolbar"><span class="graph-title">Discharge dependencies</span>' +
    '<span class="legend"><span><i style="background:#a5a39c"></i>Not started</span>' +
    '<span><i style="background:var(--warning)"></i>In progress</span>' +
    '<span><i style="background:var(--critical)"></i>Stuck</span>' +
    '<span><i style="background:var(--good)"></i>Completed</span></span></div>' +
    '<div class="dependency-graph"><svg class="dependency-lines" aria-hidden="true">' + lines + '</svg>' +
    '<div class="graph-hub" aria-hidden="true"><span class="person"></span></div>' + nodes + '</div>' + insights + '</div>'
}
const history = []
const spark = () => {
  if (history.length < 2) return ''
  const max = Math.max(...history, 1)
  const pts = history.map((v, i) =>
    (i / (history.length - 1) * 100).toFixed(1) + ',' + (26 - (v / max) * 22).toFixed(1)).join(' ')
  return '<svg viewBox="0 0 100 30" preserveAspectRatio="none">' +
    '<polygon points="0,30 ' + pts + ' 100,30" fill="rgba(82,102,235,0.10)"/>' +
    '<polyline points="' + pts + '" fill="none" stroke="var(--accent)" stroke-width="1.5" vector-effect="non-scaling-stroke"/></svg>'
}
const kpi = (key, label, value, hint, extra) =>
  '<div class="kpi' + (extra ? ' has-spark' : '') + '" role="button" tabindex="0" onclick="openModal(\\'' + key + '\\')" ' +
  'onkeydown="if (event.key === \\'Enter\\' || event.key === \\' \\') { event.preventDefault(); openModal(\\'' + key + '\\') }">' +
  '<span class="more">details</span><div class="label">' + label + '</div><div class="value">' + value + '</div>' +
  (hint ? '<div class="hint">' + hint + '</div>' : '') + (extra || '') + '</div>'

// --- KPI detail modal: what the agent is doing behind each number ------------
const CATS = {
  ward:  { title: 'On the ward',        sub: 'every tracked patient and their full checklist',
           patients: (s) => s.patients, items: (p) => p.items },
  ready: { title: 'Ready to discharge', sub: 'patients with every item verified',
           patients: (s) => s.patients.filter((p) => p.items.length && p.items.every((i) => i.state === 'verified')), items: (p) => p.items },
  open:  { title: 'Open barriers',      sub: 'items the agent is proposing, working or verifying',
           patients: (s) => s.patients, items: (p) => p.items.filter((i) => OPEN.includes(i.state)) },
  human: { title: 'Awaiting a human',   sub: 'clinical holds and external decisions automation must not touch',
           patients: (s) => s.patients, items: (p) => p.items.filter((i) => i.state === 'clinical_hold' || i.state === 'blocked_human') },
}
let lastState = null
let openKey = null
const when = (ms) => ms ? new Date(ms).toISOString().slice(0, 16).replace('T', ' ') : ''
const itemDetail = (i, log) => {
  const d = []
  d.push('<b>Status:</b> ' + stateHelp(i))
  if (i.proposedAction && (i.state === 'proposed' || i.state === 'approved')) d.push('<b>Plan:</b> ' + esc(i.proposedAction))
  if (i.approval) d.push('<b>Approved</b> by ' + esc(i.approval.by) + (i.approval.at ? ' at ' + when(i.approval.at) : ''))
  if (i.humanReason) d.push('<b>Why a human:</b> ' + esc(i.humanReason))
  if (i.resolution) d.push('<b>Agent did:</b> ' + esc(i.resolution.action) + ' &rarr; <code>' + esc(i.resolution.resourceId) + '</code>' +
    (i.resolution.atSimTime ? ' at ' + when(i.resolution.atSimTime) : '') + ' <code>key ' + esc(i.resolution.idempotencyKey) + '</code>')
  if (i.verification) d.push('<b>' + (i.verification.passed ? 'Verified:' : 'Checked, not yet:') + '</b> ' + esc(i.verification.observed) +
    (i.verification.atSimTime ? ' at ' + when(i.verification.atSimTime) : ''))
  if (i.error) d.push('<b class="err">Error:</b> <span class="err">' + esc(i.error) + '</span>')
  if (i.escalation) d.push('<b>Escalated to</b> ' + esc(i.escalation.responsibleTeam) + ' &mdash; ' + esc(i.escalation.nextAction) + '<br>' + esc(i.escalation.note))
  for (const e of i.evidence || []) d.push('<span class="tag rec">record</span> &ldquo;' + q(e.quote) + '&rdquo; <code>' + esc(e.site) + ' ' + esc(e.resourceId) + '</code>')
  const logLines = (log || []).filter((l) => l.includes(i.id)).slice(-3)
  for (const l of logLines) d.push('<span class="trace">' + esc(l) + '</span>')
  const wire = ((lastState && lastState.trace) || []).filter((t) => t.idempotencyKey && t.idempotencyKey.includes(i.id)).slice(-6)
  for (const t of wire) d.push(wireRow(t, false))
  return d.length ? '<div class="detail">' + d.map((x) => '<div>' + x + '</div>').join('') + '</div>' : ''
}
const prettyJson = (raw) => { try { return JSON.stringify(JSON.parse(raw), null, 1) } catch { return raw } }
const railWire = (t) =>
  '<div class="w"><span class="t">' + new Date(t.at).toTimeString().slice(0, 8) + '</span>' +
  '<span class="m' + (t.method === 'POST' ? ' post' : '') + '">' + esc(t.method) + '</span>' +
  '<span class="a" title="' + esc(t.action || t.path.split('?')[0]) + '">' + esc(t.headline || t.action || t.path.split('?')[0].replace('/api/', '')) + '</span>' +
  '<span class="st' + (t.ok ? '' : ' bad') + '">' + (t.status || 'ERR') + '</span></div>'
const renderRailTrace = (s) =>
  (document.getElementById('wiretrace').innerHTML =
    ((s.trace || []).slice(-40).reverse().map(railWire).join('')) || '<div class="empty">No calls yet.</div>')
// Drop-downs the reader opened stay open across the 1.5s re-render.
const openIds = new Set()
document.addEventListener('toggle', (e) => {
  const el = e.target
  if (el && el.id) { if (el.open) openIds.add(el.id); else openIds.delete(el.id) }
}, true)
const restoreOpen = () => { for (const id of openIds) { const el = document.getElementById(id); if (el) el.open = true } }
const wireId = (t) => 'wire-' + t.at + '-' + String(t.idempotencyKey || t.path).replace(/[^a-z0-9-]/gi, '_')
const pretty = (v) => { try { return JSON.stringify(v, null, 2) } catch { return String(v) } }
// The technical line: method, action, HTTP status, what the sim returned.
const wireTech = (t) =>
  '<div class="head">' +
  '<span class="m' + (t.method === 'GET' ? ' get' : '') + '">' + esc(t.method) + '</span>' +
  '<span class="a">' + esc(t.action || t.path.split('?')[0]) + '</span>' +
  '<span class="' + (t.ok ? 'ok' : 'fail') + '">' + (t.ok ? 'HTTP ' + t.status : 'FAILED ' + (t.status || '')) + '</span>' +
  (t.got ? '<span><span class="tag sim">sim</span> ' + esc(t.got) + '</span>' : '') + '</div>'
// One call, written for a clinician: what the agent did, what came back,
// and the wire detail behind "Show request".
const wireRow = (t, withPayload) => {
  const write = t.method !== 'GET'
  const icon = t.ok ? (write ? '&#10003;' : '&middot;') : '&#10005;'
  const sent = t.request !== undefined ? pretty(t.request) : (t.sent ? prettyJson(t.sent) : '')
  return '<div class="call' + (t.ok ? '' : ' bad') + (write ? '' : ' read') + '">' +
    '<div class="say"><span class="ic">' + icon + '</span>' +
    '<span class="t">' + new Date(t.at).toTimeString().slice(0, 8) + '</span>' +
    '<span><span class="what">' + esc(t.headline || t.action || t.path.split('?')[0]) + '</span>' +
    (t.outcome ? '<span class="out">' + esc(t.outcome) + '</span>' : '') + '</span></div>' +
    (withPayload
      ? '<details class="reqdd" id="' + wireId(t) + '"><summary>Show request</summary>' + wireTech(t) +
        (sent ? '<div class="meta" style="margin-top:8px">agent sent:</div><pre style="margin-top:4px">' + esc(sent) + '</pre>' : '') +
        (t.reply !== undefined ? '<div class="meta" style="margin-top:8px">service replied:</div><pre style="margin-top:4px">' + esc(pretty(t.reply)) + '</pre>' : '') +
        (t.idempotencyKey ? '<div class="meta">idempotency key · ' + esc(t.idempotencyKey) + '</div>' : '') + '</details>'
      : '') + '</div>'
}

function renderModal() { renderModalBody(); restoreOpen() }
function renderModalBody() {
  if (!lastState) return
  const s0 = lastState
  if (openKey === 'activity') {
    document.getElementById('modalTitle').textContent = s0.busy ? 'Working…' : 'Current activity'
    document.getElementById('modalSub').textContent = s0.phase || ''
    const recent = (s0.trace || []).slice(-15).reverse()
    document.getElementById('modalBody').innerHTML =
      '<div class="group"><h3>Most recent simulator calls <span>newest first · live</span></h3>' +
      (recent.length ? recent.map(wireRow).join('') : '<div class="empty">No calls yet.</div>') + '</div>' +
      '<div class="group"><h3>Recent activity log</h3>' +
      (s0.log || []).slice(-8).reverse().map((l) => '<div class="wire">' + esc(l) + '</div>').join('') + '</div>'
    return
  }
  if (openKey === 'trace') {
    const all = s0.trace || []
    const writes = all.filter((t) => t.method !== 'GET')
    document.getElementById('modalTitle').textContent = 'Full agent trace'
    document.getElementById('modalSub').textContent =
      all.length + ' simulator calls · ' + writes.length + ' writes · grouped by patient and task · each line says what the agent did and what the service replied; the wire detail is behind Show request'
    const claimed = new Set()
    const forItem = (i) => all.filter((t) => t.idempotencyKey && t.idempotencyKey.includes(i.id)).map((t) => { claimed.add(t); return t })
    const html = []
    for (const p0 of s0.patients) {
      const parts = []
      for (const i of p0.items) {
        const rows = forItem(i)
        if (!rows.length) continue
        parts.push('<div class="mi"><div class="row">' + chip(i.state) + '<span class="owner">' + (OWNER_LABEL[i.owner] || esc(i.owner)) + '</span>' +
          '<span class="title">' + esc(i.title) + '</span></div>' + rows.map((t) => wireRow(t, true)).join('') + '</div>')
      }
      const reads = all.filter((t) => !claimed.has(t) && t.method === 'GET' &&
        (t.path.includes(p0.patientId) || (t.sent || '').includes(p0.patientId)))
      reads.forEach((t) => claimed.add(t))
      if (parts.length || reads.length) {
        html.push('<div class="group"><h3>' + esc(p0.name) + ' <span>' + esc(p0.patientId) + '</span></h3>' + parts.join('') +
          (reads.length ? '<div class="mi"><div class="row"><span class="owner">reads</span><span class="title">' + reads.length + ' record reads for this patient</span></div>' +
            reads.map((t) => wireRow(t, false)).join('') + '</div>' : '') + '</div>')
      }
    }
    const rest = all.filter((t) => !claimed.has(t))
    if (rest.length) {
      html.push('<div class="group"><h3>Run &amp; world <span>world setup, clock, un-attributed calls</span></h3>' +
        rest.map((t) => wireRow(t, t.method !== 'GET')).join('') + '</div>')
    }
    document.getElementById('modalBody').innerHTML = html.join('') || '<div class="empty">No calls yet.</div>'
    return
  }
  if (openKey && openKey.startsWith('item:')) {
    const id = openKey.slice(5)
    let found = null
    for (const p1 of s0.patients) { const i1 = p1.items.find((x) => x.id === id); if (i1) found = { p: p1, i: i1 } }
    if (!found) return
    const { p: p1, i } = found
    document.getElementById('modalTitle').textContent = i.title
    document.getElementById('modalSub').innerHTML = esc(p1.name) + ' · ' + (OWNER_LABEL[i.owner] || esc(i.owner)) + ' · ' + chip(i.state) +
      '<div class="stmt">' + stateHelp(i) + '</div>'
    const kv = (k, v) => '<div class="kv"><span class="k">' + k + '</span><span class="v">' + v + '</span></div>'
    const parts = []
    parts.push('<div class="group"><h3>Detected from the record</h3>' +
      ((i.evidence || []).map((e) =>
        kv('<span class="tag rec">record</span>', '&ldquo;' + q(e.quote) + '&rdquo; <code>' + esc(e.site) + ' ' + esc(e.resourceId) + '</code>')).join('') ||
        '<div class="empty">Rule-detected from structured state.</div>') + '</div>')
    parts.push('<div class="group"><h3>Plan &amp; approval</h3>' +
      (i.proposedAction ? kv('Plan', esc(i.proposedAction)) : '') +
      kv('Approval', i.approval ? 'Approved by ' + esc(i.approval.by) : 'Not yet — awaiting staff approval') +
      (i.humanReason ? kv('Needs a human', esc(i.humanReason)) : '') + '</div>')
    const wire = (s0.trace || []).filter((t) => t.idempotencyKey && t.idempotencyKey.includes(i.id))
    parts.push('<div class="group"><h3>Agent &harr; ' + (OWNER_LABEL[i.owner] || esc(i.owner)) + ' <span>' + wire.length + ' calls, oldest first</span></h3>' +
      (wire.length ? wire.map((t) => wireRow(t, true)).join('') : '<div class="empty">No actions sent yet.</div>') + '</div>')
    if (i.generated) parts.push('<div class="group"><h3>Drafting provenance</h3>' +
      kv(i.generated === 'model' ? '<span class="tag ai">AI</span>' : '<span class="err">⚠</span>',
        i.generated === 'model' ? 'The live model wrote the drafted content for this task' : 'Canned fallback used — model unavailable') + '</div>')
    if (i.verification) parts.push('<div class="group"><h3>Independent verification</h3>' +
      kv('<span class="tag sim">sim</span>', (i.verification.passed ? '<span style="color:var(--good);font-weight:480">✓ passed</span> — ' : '<span class="err">✗ not yet</span> — ') + esc(i.verification.observed)) +
      (caveatFor(i.id) ? kv('Does not prove', esc(caveatFor(i.id))) : '') + '</div>')
    if (i.escalation) parts.push('<div class="group"><h3>Escalation</h3>' +
      kv('<span class="tag ai">AI</span>', '<b>' + esc(i.escalation.responsibleTeam) + '</b> — ' + esc(i.escalation.nextAction)) +
      kv('Note', esc(i.escalation.note)) + '</div>')
    document.getElementById('modalBody').innerHTML = parts.join('')
    return
  }
  const cat = CATS[openKey]
  if (!cat) return
  const s = lastState
  document.getElementById('modalTitle').textContent = cat.title
  document.getElementById('modalSub').textContent = cat.sub
  const groups = cat.patients(s).map((p) => ({ p, items: cat.items(p) })).filter((g) => openKey === 'ward' || openKey === 'ready' || g.items.length)
  document.getElementById('modalBody').innerHTML = groups.length ? groups.map((g) =>
    '<div class="group"><h3>' + esc(g.p.name) + ' <span>' + esc(g.p.patientId) + ' · ' + esc(g.p.stage ?? '?') +
    (g.p.location ? ' · ' + esc(g.p.location) : '') + ' · ' + g.items.filter((i) => i.state === 'verified').length + ' of ' + g.items.length + ' verified</span></h3>' +
    (g.items.length ? g.items.map((i) =>
      '<div class="mi"><div class="row">' + chip(i.state) + '<span class="owner">' + (OWNER_LABEL[i.owner] || esc(i.owner)) + '</span>' +
      '<span class="title">' + esc(i.title) + '</span></div>' + itemDetail(i, s.log) + '</div>').join('')
      : '<div class="empty">No items in this category for this patient.</div>') + '</div>').join('')
    : '<div class="empty">Nothing here right now.</div>'
}
function openModal(key) {
  openKey = key
  renderModal()
  document.getElementById('modal').classList.add('open')
  document.querySelector('#modal button').focus()
}
function closeModal() {
  openKey = null
  document.getElementById('modal').classList.remove('open')
}
document.addEventListener('keydown', (e) => { if (e.key === 'Escape' && openKey) closeModal() })

function render(s) {
  lastState = s
  document.getElementById('world').textContent = s.world
  document.getElementById('clock').textContent = s.simNow ? new Date(s.simNow).toISOString().slice(0, 16).replace('T', ' ') : '—'
  document.getElementById('status').innerHTML = s.busy
    ? '<span class="status" role="button" style="cursor:pointer" onclick="openModal(\\'activity\\')"><span class="spin"></span>' + esc(s.phase || 'Calling the simulator…') + '</span>'
    : (s.phase ? '<span class="status quiet" role="button" style="cursor:pointer" onclick="openModal(\\'activity\\')">' + esc(s.phase) + '</span>' : '')
  if (!s.patients.length) {
    document.getElementById('kpis').innerHTML = ''
    document.getElementById('board').innerHTML =
      '<div class="card"><div class="loading-hero"><span class="spin"></span>' +
      '<div class="what">' + esc(s.phase || 'Setting up the demo world…') + '</div>' +
      '<div class="why">Live calls against the NHS-SIM simulator — the ward list appears as records load.</div></div></div>'
    document.getElementById('services').innerHTML = ''
    renderRailTrace(s)
    return
  }
  const all = s.patients.flatMap((p) => p.items)
  const ready = s.patients.filter((p) => p.items.length && p.items.every((i) => i.state === 'verified')).length
  const open = all.filter((i) => OPEN.includes(i.state)).length
  const human = all.filter((i) => i.state === 'clinical_hold' || i.state === 'blocked_human').length
  if (history[history.length - 1] !== open) history.push(open)
  if (history.length > 60) history.shift()
  document.getElementById('kpis').innerHTML =
    kpi('ward', 'On the ward', s.patients.length, 'tracked patients') +
    kpi('ready', 'Ready to discharge', ready, 'every item verified') +
    kpi('open', 'Open barriers', open, 'agent is working these', spark()) +
    kpi('human', 'Awaiting a human', human, 'holds + external decisions')
  if (openKey) renderModal()

  const proposed = all.filter((i) => i.state === 'proposed').length

  if (!initialExpansionSet && s.patients.length) {
    expandedPatientId = s.patients[0].patientId
    initialExpansionSet = true
  }
  if (expandedPatientId && !s.patients.some((p) => p.patientId === expandedPatientId)) expandedPatientId = null

  // --- searchable patient sidebar: green ready · red needs human · amber working ---
  if (!selectedPatient || !s.patients.some((p) => p.patientId === selectedPatient)) selectedPatient = (s.patients[0] || {}).patientId
  const dotFor = (p) => {
    const ready = p.items.length && p.items.every((i) => i.state === 'verified')
    if (ready) return 'var(--good)'
    if (p.items.some((i) => ['clinical_hold', 'blocked_human', 'failed'].includes(i.state))) return 'var(--critical)'
    if (p.items.some((i) => ['approved', 'resolving', 'awaiting_verification'].includes(i.state))) return 'var(--warning)'
    return '#a5a39c'
  }
  const flt = patFilter.trim().toLowerCase()
  const shown = s.patients.filter((p) => !flt || p.name.toLowerCase().includes(flt) || p.patientId.toLowerCase().includes(flt))
  document.getElementById('plistLabel').textContent = 'Patients · ' + shown.length
  document.getElementById('plist').innerHTML = shown.map((p) => {
    const initials = esc(p.name).split(' ').map((w) => w[0]).slice(0, 2).join('')
    return '<div class="pat' + (p.patientId === selectedPatient ? ' sel' : '') + '" data-p="' + esc(p.patientId) + '" ' +
      'onclick="selectedPatient=this.dataset.p;render(lastState)">' +
      '<div class="avatar">' + initials + '</div><div style="min-width:0"><div class="pn">' + esc(p.name) + '</div>' +
      '<div class="pm">' + esc(p.patientId) + (p.location ? ' · ' + esc(p.location) : '') + '</div></div>' +
      '<span class="pdot" style="background:' + dotFor(p) + '"></span></div>'
  }).join('')
  const sel = s.patients.find((p) => p.patientId === selectedPatient)

  // --- "Can they go home?" verdict for the selected patient ---
  const heroFor = (p) => {
    if (!p) return ''
    const human = p.items.filter((i) => ['clinical_hold', 'blocked_human', 'failed'].includes(i.state))
    const proposed = p.items.filter((i) => i.state === 'proposed')
    const ready = p.items.length && p.items.every((i) => i.state === 'verified')
    const working = p.items.some((i) => ['approved', 'resolving', 'awaiting_verification'].includes(i.state))
    const open = p.items.filter((i) => i.state !== 'verified').length
    let head, cls
    if (ready) { head = 'Ready for discharge'; cls = 'yes' }
    else if (human.length || proposed.length) { head = 'Needs a human'; cls = 'no' }
    else if (working) { head = 'In progress'; cls = 'warn' }
    else { head = 'In progress'; cls = 'warn' }
    const acts = []
    if (proposed.length) acts.push('<div class="acard"><span class="t">Approve the plan</span>' +
      '<span class="sub">' + proposed.length + ' actions wait for your approval</span>' +
      '<span class="act"><button class="primary" data-p="' + esc(p.patientId) + '" onclick="approvePatient(this.dataset.p)">Approve</button></span></div>')
    for (const i of p.items.filter((x) => x.state === 'clinical_hold'))
      acts.push('<div class="acard"><span class="t">' + esc(shortTitle(i)) + '</span><span class="sub">clinical decision</span>' +
        '<span class="act"><button class="confirm" data-id="' + i.id + '" onclick="clearHold(this.dataset.id)">Confirm reviewed</button></span></div>')
    for (const i of p.items.filter((x) => x.state === 'blocked_human'))
      acts.push(i.escalation
        ? '<div class="acard done"><span class="t">' + esc(shortTitle(i)) + '</span><span class="sub">escalated to ' + esc(i.escalation.responsibleTeam) + '</span></div>'
        : '<div class="acard"><span class="t">' + esc(shortTitle(i)) + '</span><span class="sub">external decision</span>' +
          '<span class="act"><button class="confirm" data-id="' + i.id + '" onclick="escalate(this.dataset.id)">Prepare escalation</button></span></div>')
    const tasks = p.items.map((i) => '<div class="lrow" data-id="' + i.id + '" onclick="itemStory(this.dataset.id)">' + chip(i.state) +
      '<span class="owner">' + (OWNER_LABEL[i.owner] || esc(i.owner)) + '</span><span>' + esc(i.title) + '</span>' +
      '<span style="margin-left:auto;color:var(--ink-3);font-size:11px">what the agent did &rsaquo;</span></div>').join('')
    return '<div class="hero"><div class="verdict ' + cls + '">' + head + '</div>' +
      '<div class="vsub">' + (ready ? p.items.length + ' of ' + p.items.length + ' verified · clinician decision remains'
        : open + ' of ' + p.items.length + ' outstanding') +
      ' · <a class="rlink" href="/receipt?patient=' + esc(p.patientId) + '">Receipt &darr;</a></div></div>' +
      acts.join('') +
      '<div class="ptable">' + tasks + '</div>'
  }

  const graphView = () => (sel ? [sel] : []).map((p) => {
    const done = p.items.filter((i) => i.state === 'verified').length
    const pct = p.items.length ? Math.round((100 * done) / p.items.length) : 0
    const initials = esc(p.name).split(' ').map((w) => w[0]).slice(0, 2).join('')
    const expanded = true
    return '<section class="card patient-card' + (expanded ? ' expanded' : '') + '">' +
      '<button type="button" class="patient-head" data-patient="' + esc(p.patientId) + '" aria-expanded="' + expanded + '" ' +
      'aria-controls="patient-graph-' + esc(p.patientId) + '" onclick="togglePatient(this.dataset.patient)">' +
      '<div class="avatar">' + initials + '</div>' +
      '<div><div class="patient-name">' + esc(p.name) + '</div>' +
      '<div class="patient-meta">' + esc(p.patientId) + ' · ' + esc(p.stage ?? '?') +
      (p.location ? ' · ' + esc(p.location) : '') + ' · ' + esc((p.conditions || []).join(', ')) + '</div></div>' +
      '<div class="ready-pill"><span class="count">' + done + ' of ' + p.items.length + ' verified</span>' +
      '<span class="bar"><i style="width:' + pct + '%"></i></span><span class="chevron" aria-hidden="true">⌄</span></div></button>' +
      (expanded ? '<div id="patient-graph-' + esc(p.patientId) + '">' + graphForPatient(p) + '</div>' : '') + '</section>'
  }).join('')

  const patientStatus = (p) => {
    const holds = p.items.filter((i) => i.state === 'clinical_hold' || i.state === 'blocked_human')
    const failed = p.items.some((i) => i.state === 'failed')
    const ready = p.items.length && p.items.every((i) => i.state === 'verified')
    const working = p.items.some((i) => ['approved', 'resolving', 'awaiting_verification'].includes(i.state))
    if (ready) return { cls: 'good', sev: 'sev-good', label: 'Ready to discharge', sub: 'every item verified' }
    if (failed) return { cls: 'bad', sev: 'sev-bad', label: 'Action failed', sub: 'needs attention' }
    if (holds.length) return { cls: 'bad', sev: 'sev-bad', label: 'Blocked — needs a human',
      sub: shortTitle(holds[0]) + ' · ' + (OWNER_LABEL[holds[0].owner] || holds[0].owner) }
    if (working) return { cls: 'warn', sev: 'sev-warn', label: 'Agent working', sub: 'executing the approved plan' }
    return { cls: 'plain', sev: '', label: 'Awaiting approval', sub: 'plan proposed' }
  }
  const tableView = () => {
    const rows = s.patients.map((p) => {
      const st = patientStatus(p)
      const done = p.items.filter((i) => i.state === 'verified').length
      const pct = p.items.length ? Math.round((100 * done) / p.items.length) : 0
      const needs = p.items.filter((i) => i.state !== 'verified')
      const chips = needs.slice(0, 4).map((i) =>
        '<span class="need" data-id="' + i.id + '" onclick="event.stopPropagation();itemStory(this.dataset.id)">' +
        '<span class="dot" style="background:' + needDot(i.state) + '"></span>' + esc(shortTitle(i)) + '</span>').join('') +
        (needs.length > 4 ? '<span class="need more">+' + (needs.length - 4) + ' more</span>' : '')
      const initials = esc(p.name).split(' ').map((w) => w[0]).slice(0, 2).join('')
      return '<div class="prow ' + st.sev + '" data-patient="' + esc(p.patientId) + '" onclick="selectedPatient=this.dataset.patient;render(lastState)">' +
        '<div class="pcol"><div class="avatar">' + initials + '</div><div style="min-width:0"><div class="nm">' + esc(p.name) + '</div>' +
        '<div class="sub">' + esc(p.patientId) + (p.location ? ' · ' + esc(p.location) : '') + '</div></div></div>' +
        '<div><span class="schip ' + st.cls + '"><span class="dot" style="background:currentColor"></span>' + st.label + '</span>' +
        '<div class="sub" style="margin-top:4px;font-size:11.5px;color:var(--ink-3)">' + esc(st.sub) + '</div></div>' +
        '<div>' + (chips || '<span class="sub" style="color:var(--ink-3)">nothing outstanding</span>') + '</div>' +
        '<div><div style="font-size:13px;font-weight:480">' + done + ' of ' + p.items.length + '</div>' +
        '<span class="bar" style="width:90px;display:block;margin:5px 0 4px"><i style="width:' + pct + '%"></i></span>' +
        '<a class="rlink" href="/receipt?patient=' + esc(p.patientId) + '" onclick="event.stopPropagation()">Receipt &darr;</a></div></div>'
    }).join('')
    return '<div class="ptable"><div class="phead"><span>Patient</span><span>Discharge status</span><span>What it still needs</span><span>Verified</span></div>' + rows + '</div>'
  }
  const listView = () => (sel ? [sel] : []).map((p) => {
    const initials = esc(p.name).split(' ').map((w) => w[0]).slice(0, 2).join('')
    return '<div class="ptable"><div class="lrow" style="cursor:default"><div class="avatar">' + initials + '</div>' +
      '<span class="nm" style="font-weight:480">' + esc(p.name) + '</span><span class="sub" style="color:var(--ink-3);font-size:11.5px">' +
      esc(p.patientId) + (p.location ? ' · ' + esc(p.location) : '') + '</span></div>' +
      p.items.map((i) => '<div class="lrow" data-id="' + i.id + '" onclick="itemStory(this.dataset.id)">' + chip(i.state) +
        '<span class="owner">' + (OWNER_LABEL[i.owner] || esc(i.owner)) + '</span><span>' + esc(i.title) +
        ((i.evidence || [])[0] ? ' <span class="q">&ldquo;' + q(i.evidence[0].quote) + '&rdquo;</span> <span class="tag rec">record</span>' : '') + '</span></div>').join('') + '</div>'
  }).join('')
  document.getElementById('board').innerHTML = heroFor(sel)


}
async function tick() { try { render(await (await fetch('/state')).json()) } catch {} }
function itemStory(id) { openModal('item:' + id) }
async function clearHold(id) { await fetch('/clear-hold?item=' + encodeURIComponent(id), { method: 'POST' }); tick() }
async function approve() { await fetch('/approve', { method: 'POST' }); tick() }
async function approvePatient(p) { await fetch('/approve?patient=' + encodeURIComponent(p), { method: 'POST' }); tick() }
async function escalate(id) {
  const btn = event?.target
  if (btn) { btn.textContent = 'Drafting…'; btn.disabled = true }
  await fetch('/escalate?item=' + encodeURIComponent(id), { method: 'POST' })
  tick()
}
setInterval(tick, 1500); tick()
</script></body></html>`

export function startUi(board: BoardState, port = 4600): void {
  const server = createServer((req, res) => {
    const url = new URL(req.url ?? '/', 'http://localhost')
    if (url.pathname === '/state') {
      res.setHeader('content-type', 'application/json')
      res.end(JSON.stringify(board))
    } else if (url.pathname === '/clear-hold' && req.method === 'POST') {
      const ok = clearHold(board, url.searchParams.get('item') ?? '', 'Demo clinician')
      res.statusCode = ok ? 200 : 404
      res.end(ok ? 'cleared' : 'not found')
    } else if (url.pathname === '/approve' && req.method === 'POST') {
      const n = approveAll(board, 'Demo coordinator', url.searchParams.get('patient') || undefined)
      res.end(String(n))
    } else if (url.pathname === '/receipt') {
      const md = buildReceipt(board, url.searchParams.get('patient') ?? '')
      if (!md) { res.statusCode = 404; res.end('unknown patient'); return }
      res.setHeader('content-type', 'text/markdown; charset=utf-8')
      res.setHeader('content-disposition', `attachment; filename="homeward-receipt-${url.searchParams.get('patient')}.md"`)
      res.end(md)
    } else if (url.pathname === '/escalate' && req.method === 'POST') {
      prepareEscalation(board, url.searchParams.get('item') ?? '').then((ok) => {
        res.statusCode = ok ? 200 : 404
        res.end(ok ? 'escalated' : 'not found')
      })
    } else {
      res.setHeader('content-type', 'text/html')
      res.end(PAGE)
    }
  })
  server.on('error', (err: NodeJS.ErrnoException) => {
    if (err.code === 'EADDRINUSE') {
      console.error(`port ${port} is busy (an older run?) — retrying every 2s; this run's UI will take over as soon as it frees up`)
      setTimeout(() => server.listen(port, '127.0.0.1'), 2000)
    } else throw err
  })
  server.listen(port, '127.0.0.1', () => console.log(`ward list: http://localhost:${port} (localhost only)`))
}
