/**
 * Homeward "journey home" page: one patient at a time, the route from
 * hospital to home as five gates (clinical, medicines, monitoring, support,
 * handover) derived from the checklist items, the operational work and the
 * named human confirmations beneath it, the timing story against the
 * manual-ward model, and the discharge pack (record facts, prescriptions,
 * the agent's drafted letter, editable, and what the agent sends).
 *
 * Polls /state every 1.5s and re-renders only when it changed; unsaved
 * letter edits survive re-renders. Every sentence on the page is derived
 * from board state; nothing is hard-coded per patient. The raw request and
 * reply of every simulator call sit behind "Show request".
 */
import { createServer, type Server } from 'node:http'
import type { AddressInfo } from 'node:net'
import type { BoardState, ChecklistItem, PatientRow } from '../orchestrator/model.ts'
import { approveAll, clearHold, prepareEscalation, saveLetter, undoHold } from '../orchestrator/run.ts'
import type { SimClient } from '../sim/index.ts'
import { computeStory } from '../story/story.ts'

/** What each verified item does NOT prove, epistemic honesty, per item kind. */
const CAVEATS: Record<string, string> = {
  medicines: 'Collection is recorded; this does not prove adherence or ongoing supply.',
  bloods: 'Results are available; this does not constitute clinical review of those results.',
  device: 'A reading was received; this does not confirm sustained monitoring or clinical review of readings.',
  visit: 'The visit is completed; this does not confirm ongoing care-package funding or future visits.',
  summary: 'The letter reached the GP inbox; this does not confirm the GP has read or actioned it.',
  'follow-up': 'The task exists on the GP worklist; this does not confirm the review has happened.',
  'clinical-hold': 'Clinician sign-off is a human decision recorded here, not an automated judgement.',
  'care-package': 'Escalated to a human decision; nothing here resolves the funding question.',
}
const caveatFor = (id: string): string | undefined =>
  Object.entries(CAVEATS).find(([k]) => id.endsWith('-' + k))?.[1]

const mdWhen = (ms?: number) => (ms ? new Date(ms).toISOString().replace('T', ' ').slice(0, 16) + ' (sim)' : 'n/a')

/** Consolidated per-patient discharge coordination record, as Markdown. */
export function buildReceipt(board: BoardState, patientId: string): string | undefined {
  const p = board.patients.find((x) => x.patientId === patientId)
  if (!p) return undefined
  const verified = p.items.filter((i) => i.state === 'verified').length
  const blockers = p.items.filter((i) => i.state === 'clinical_hold' || i.state === 'blocked_human')
  const open = p.items.filter((i) => !['verified', 'clinical_hold', 'blocked_human'].includes(i.state))
  const L: string[] = []
  L.push(`# Discharge coordination record: ${p.name} (${p.patientId})`)
  L.push('')
  L.push(`Generated by Homeward · world \`${board.world}\` · sim clock ${mdWhen(board.simNow)} · real time ${new Date().toISOString().slice(0, 16).replace('T', ' ')} UTC`)
  L.push('')
  L.push('## Verdict')
  L.push('')
  const ready = p.items.length > 0 && p.items.every((i) => i.state === 'verified')
  L.push(ready
    ? `**Operationally ready.** All ${p.items.length} checklist items independently verified. Final discharge remains a clinical decision.`
    : `**Not yet confirmed.** ${verified} of ${p.items.length} items verified.` +
      (blockers.length ? ` Outstanding human decisions: ${blockers.map((b) => b.title).join('; ')}.` : '') +
      (open.length ? ` Still in progress: ${open.map((o) => o.title).join('; ')}.` : ''))
  L.push('')
  L.push(`Patient context: ${p.conditions.join(', ') || 'n/a'} · stage ${p.stage ?? 'n/a'}${p.location ? ' · ' + p.location : ''}. Recorded needs: ${p.needs.join(', ') || 'n/a'}. Goals: ${p.goals.join(', ') || 'n/a'}.`)
  p.items.forEach((i, n) => {
    L.push('')
    L.push(`## ${n + 1}. ${i.title}`)
    L.push('')
    L.push(`**State:** ${i.state.replace('_', ' ')} · **Owner:** ${i.owner}`)
    if (i.evidence.length) {
      L.push('')
      L.push('**Detected from the record:**')
      for (const e of i.evidence) L.push(`- "${e.quote}", \`${e.site} ${e.resourceId}\``)
    }
    if (i.proposedAction) { L.push(''); L.push(`**Plan:** ${i.proposedAction}`) }
    if (i.approval) L.push(`**Approved by:** ${i.approval.by} at ${mdWhen(i.approval.at)}`)
    if (i.humanReason) { L.push(''); L.push(`**Why a human is required:** ${i.humanReason}`) }
    const wire = (board.trace ?? []).filter((t) => t.idempotencyKey && t.idempotencyKey.includes(i.id))
    if (wire.length) {
      L.push('')
      L.push('**Actions executed (wire record):**')
      L.push('')
      L.push('| Time | What the agent did | Result | Call |')
      L.push('| --- | --- | --- | --- |')
      const cell = (s: string) => s.replace(/\|/g, '\\|')
      for (const t of wire) {
        L.push(`| ${new Date(t.at).toTimeString().slice(0, 8)} | ${cell(t.headline ?? t.action ?? t.method)} | ${cell(t.outcome ?? t.got ?? (t.ok ? 'OK' : 'failed'))} | \`${t.action ?? t.method}\` ${t.ok ? `HTTP ${t.status}` : `FAILED ${t.status || ''}`} |`)
      }
    }
    if (i.resolution) L.push(`
Idempotency key: \`${i.resolution.idempotencyKey}\``)
    if (i.generated) { L.push(''); L.push(`**Drafting provenance:** ${i.generated === 'model' ? 'content written by the live model' : i.generated === 'clinician' ? 'sections edited and saved by a clinician in Homeward' : 'canned fallback (model unavailable)'}`) }
    if (i.verification) {
      L.push('')
      L.push(`**Independent verification:** ${i.verification.passed ? 'PASSED' : 'NOT YET'}, ${i.verification.observed} at ${mdWhen(i.verification.atSimTime)}`)
    }
    if (i.escalation) {
      L.push('')
      L.push(`**Escalated to:** ${i.escalation.responsibleTeam}, ${i.escalation.nextAction}`)
      L.push(`> ${i.escalation.note}`)
    }
    const cav = caveatFor(i.id)
    if (cav && ['verified', 'clinical_hold', 'blocked_human'].includes(i.state)) {
      L.push(''); L.push(`**This does not prove:** ${cav}`)
    }
  })
  L.push('')
  L.push('---')
  L.push('')
  L.push('Synthetic simulator data (NHS-SIM). Every action above was executed against the simulator and independently re-read; RECORD quotes are verbatim from the record. Final discharge decisions rest with the responsible clinician.')
  L.push('')
  return L.join('\n')
}

export const PAGE = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Homeward</title>
<style>
:root{--nhs-blue:#005eb8;--nhs-dark:#003087;--nhs-green:#007f3b;--nhs-red:#d5281b;--nhs-amber:#ffb81c;--ink:#212b32;--muted:#4c6272;--line:#d8dde0;--wash:#f0f4f5;--pale:#e8edff;--white:#fff;--shadow:0 5px 18px rgba(33,43,50,.10);font-family:"Frutiger W01",Arial,sans-serif}
*{box-sizing:border-box}[hidden]{display:none!important}
.why{display:grid;grid-template-columns:auto 1fr;gap:14px;align-items:start;padding:16px 28px;border-bottom:1px solid var(--line);background:var(--pale)}.why .ic{width:14px;height:14px;border-radius:50%;margin-top:5px;background:var(--nhs-blue);flex:none}.why b{display:block;font-size:16px;color:var(--ink)}.why span{display:block;font-size:13px;color:var(--ink);margin-top:3px;line-height:1.45}.why span em{font-style:normal;font-weight:700}.why.warn{background:#fff8e6}.why.warn .ic{background:var(--nhs-amber)}.why.bad{background:#fbeae8}.why.bad .ic{background:var(--nhs-red)}.why.good{background:#e9f5ed}.why.good .ic{background:var(--nhs-green)}.why.live .ic{animation:pulse 1.2s ease-in-out infinite}@keyframes pulse{50%{opacity:.35}}@media (prefers-reduced-motion:reduce){.why.live .ic{animation:none}}
.boot{position:fixed;inset:0;z-index:100;background:var(--wash);display:grid;place-items:center;text-align:center;padding:24px}.boot.off{display:none}.boot .card{max-width:520px}.boot .homeward-logo{width:64px;height:64px;margin:0 auto 18px}.boot h2{font-size:24px;margin:0 0 6px;color:var(--nhs-dark)}.boot .phase{font-size:16px;color:var(--ink);min-height:24px;margin:0 0 22px}.spinner{width:52px;height:52px;border:5px solid var(--line);border-top-color:var(--nhs-blue);border-radius:50%;margin:0 auto 22px;animation:spin 1s linear infinite}@keyframes spin{to{transform:rotate(360deg)}}@media (prefers-reduced-motion:reduce){.spinner{animation:none;border-top-color:var(--line);border-left-color:var(--nhs-blue)}}
.boot ol{list-style:none;padding:0;margin:0 auto;display:grid;gap:8px;text-align:left;width:fit-content}.boot li{display:flex;align-items:center;gap:12px;font-size:14px;color:var(--muted)}.boot li i{width:22px;height:22px;border-radius:50%;border:2px solid var(--line);display:grid;place-items:center;font-size:12px;font-style:normal;flex:none;color:#fff}.boot li.done{color:var(--ink)}.boot li.done i{background:var(--nhs-green);border-color:var(--nhs-green)}.boot li.done i:before{content:"✓"}.boot li.now{color:var(--ink);font-weight:700}.boot li.now i{border-color:var(--nhs-blue);background:var(--nhs-blue)}.boot li.now i:before{content:"";width:8px;height:8px;border-radius:50%;background:#fff;display:block}
.boot .note{font-size:12px;color:var(--muted);margin:22px 0 0}body{margin:0;background:var(--wash);color:var(--ink);font-family:inherit;-webkit-font-smoothing:antialiased}button{font:inherit;cursor:pointer}.app{min-height:100vh}.nhsbar{height:8px;background:var(--nhs-blue)}
.top{min-height:86px;padding:12px 42px;display:flex;align-items:center;gap:18px;background:var(--white);border-bottom:1px solid var(--line);flex-wrap:wrap}.wordmark{display:flex;align-items:center;gap:14px}.homeward-logo{width:54px;height:54px;display:block}.homeward-logo svg{width:100%;height:100%;display:block}.wordmark h1{font-size:24px;margin:0;color:var(--nhs-dark)}.wordmark p{font-size:13px;color:var(--muted);margin:2px 0 0}.topspace{flex:1}
.shell{display:grid;grid-template-columns:270px minmax(0,1fr);align-items:start}.side{background:var(--white);border-right:1px solid var(--line);min-height:calc(100vh - 94px);padding:22px 16px;position:sticky;top:0}.side .find{width:100%;border:2px solid #768692;padding:10px 12px;font:14px "Frutiger W01",Arial,sans-serif;color:var(--ink)}.side .find:focus{outline:4px solid #ffdd00;outline-offset:0;border-color:#212b32}.side .label{font-size:11px;font-weight:700;letter-spacing:.06em;text-transform:uppercase;color:var(--muted);margin:18px 0 8px}.plist{display:flex;flex-direction:column;gap:6px}.prow{display:grid;grid-template-columns:40px 1fr;gap:10px;align-items:center;width:100%;text-align:left;border:0;border-left:5px solid transparent;padding:10px 10px 10px 8px;background:var(--wash);color:inherit}.prow .av{width:40px;height:40px;border-radius:50%;display:grid;place-items:center;font-weight:700;font-size:13px;background:#fff;color:var(--nhs-dark)}.prow b{display:block;font-size:14px}.prow small{display:block;font-size:11px;color:var(--muted);margin-top:2px}.prow em{display:block;font-size:11px;font-style:normal;font-weight:700;margin-top:3px}.prow.good{background:#e9f5ed}.prow.good em{color:var(--nhs-green)}.prow.bad{background:#fbeae8}.prow.bad em{color:var(--nhs-red)}.prow.warn{background:#fff4cf}.prow.warn em{color:#5c4200}.prow.on.good{border-left-color:var(--nhs-green)}.prow.on.bad{border-left-color:var(--nhs-red)}.prow.on.warn{border-left-color:var(--nhs-amber)}.prow.on{box-shadow:var(--shadow)}.prow:not(.on){opacity:.8}.side .none{font-size:12px;color:var(--muted);padding:10px 4px}
.patient{display:flex;align-items:center;gap:12px}.patient-avatar{width:48px;height:48px;border-radius:50%;background:#d9e5f5;display:grid;place-items:center;color:var(--nhs-dark);font-weight:700}.patient strong,.patient>span:not(.patient-avatar),.patient>span>span{display:block}.patient strong{font-size:15px}.patient span{font-size:12px;color:var(--muted);margin-top:2px}.allergy{background:#fbeae8;color:var(--nhs-red);font-weight:700;font-size:12px;padding:8px 10px}.allergy.none{background:var(--wash);color:var(--muted)}
.page{max-width:1500px;margin:0 auto;padding:34px 42px 70px}.intro{display:flex;align-items:flex-end;justify-content:space-between;gap:28px;margin-bottom:24px}.intro small{display:block;color:var(--nhs-blue);font-size:13px;font-weight:700;margin-bottom:8px}.titleline{display:flex;align-items:center;gap:18px;flex-wrap:wrap}.intro h2{font-size:38px;line-height:1.12;letter-spacing:-.5px;margin:0;max-width:760px}.top-readiness{display:inline-flex;align-items:center;gap:9px;background:#fbeae8;color:var(--nhs-red);font-size:14px;font-weight:700;padding:11px 14px;border-left:5px solid var(--nhs-red)}.top-readiness:before{content:"";width:14px;height:14px;border-radius:50%;background:var(--nhs-red);display:block}.top-readiness.ready{background:#e9f5ed;color:var(--nhs-green);border-left-color:var(--nhs-green)}.top-readiness.ready:before{background:var(--nhs-green)}.top-readiness.reviewing{background:#fff4cf;color:#5c4200;border-left-color:var(--nhs-amber)}.top-readiness.reviewing:before{background:var(--nhs-amber)}.intro p{font-size:16px;color:var(--muted);line-height:1.5;max-width:670px;margin:12px 0 0}.doctor{display:flex;align-items:center;gap:12px;min-width:235px;padding-bottom:4px}.doctor .doctor-photo{width:50px;height:50px;border-radius:50%;background:#768692;color:#fff;display:grid;place-items:center;font-weight:700;font-size:16px;letter-spacing:.5px;margin:0}.doctor-photo svg{width:33px;height:33px}.doctor strong,.doctor span{display:block}.doctor strong{font-size:14px}.doctor span{font-size:12px;color:var(--muted);margin-top:3px}
.journey{background:var(--white);box-shadow:var(--shadow);border-top:6px solid var(--nhs-blue);overflow:hidden}.journey-head{display:flex;align-items:center;justify-content:space-between;gap:20px;padding:24px 28px;border-bottom:1px solid var(--line)}.journey-head h3{font-size:20px;margin:0}.journey-head p{font-size:13px;color:var(--muted);margin:5px 0 0}.status{font-size:13px;font-weight:700;color:var(--nhs-red);padding:8px 11px;background:#fbeae8}.status.reviewing{background:#e8edff;color:var(--nhs-blue)}.status.ready{background:#e9f5ed;color:var(--nhs-green)}
.route{display:grid;grid-template-columns:230px 1fr 290px;align-items:stretch;min-height:355px}.place{padding:28px 24px;display:flex;flex-direction:column;justify-content:center}.hospital{background:#f7f9fa;border-right:1px solid var(--line)}.home{background:#e9f5ed;border-left:1px solid #b7d7c2}.place-icon{width:64px;height:64px;display:grid;place-items:center;background:var(--white);color:var(--nhs-blue);font-size:34px;font-weight:700;border:1px solid var(--line);margin-bottom:18px}.home .place-icon{color:var(--nhs-green)}.place small{font-size:12px;font-weight:700;color:var(--muted)}.place h4{font-size:22px;margin:5px 0}.place p{font-size:13px;line-height:1.45;color:var(--muted);margin:0}.place .flags{margin-top:10px;display:flex;flex-wrap:wrap;gap:5px}.wontwill{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin-bottom:22px}.wontwill>div{padding:16px 18px;border-top:6px solid}.wontwill .will{background:#e9f5ed;border-color:var(--nhs-green)}.wontwill .wont{background:#fbeae8;border-color:var(--nhs-red)}.wontwill h4{margin:0 0 10px;font-size:18px}.wontwill h4 small{display:block;font-size:12px;font-weight:400;color:var(--muted);margin-top:2px}.wontwill li b,.wontwill li span,.wontwill h4{background:none;padding:0}.wontwill .will h4{color:var(--nhs-green)}.wontwill .wont h4{color:var(--nhs-red)}.wontwill ul{margin:0;padding:0;list-style:none;display:grid;gap:9px}.wontwill li{display:grid;grid-template-columns:1fr auto;column-gap:10px;font-size:14px;line-height:1.35}.wontwill li b{display:block}.wontwill li span{display:block;grid-column:1;font-size:12.5px;color:var(--muted)}.wontwill li em{grid-column:2;grid-row:1/3;font-style:normal;font-size:11px;font-weight:700;color:var(--nhs-blue);align-self:start;white-space:nowrap}.wontwill p{margin:12px 0 0;font-size:12.5px;color:var(--muted)}.steps-head{font-size:13px;letter-spacing:.04em;text-transform:uppercase;color:var(--muted);margin:0 0 4px}@media(max-width:760px){.wontwill{grid-template-columns:1fr}}a.thread{display:inline-block;margin-top:6px;font-size:12px;font-weight:700;color:var(--nhs-blue);text-decoration:underline}.confirm .btns{display:flex;gap:8px;align-items:center;flex:none}.confirm .btns button.undo{border:2px solid var(--nhs-red);color:var(--nhs-red);background:#fff;font-weight:700;padding:8px 12px;box-shadow:none}.thread-view h4{font-size:17px;margin:0 0 4px}.thread-view .meta{font-size:12px;color:var(--muted);margin:0 0 12px}.thread-view blockquote{margin:0 0 10px;padding:12px 14px;background:var(--wash);border-left:4px solid var(--nhs-blue);font-size:14px;line-height:1.5}.thread-view dl{display:grid;grid-template-columns:auto 1fr;gap:4px 14px;font-size:12px;margin:0}.thread-view dt{color:var(--muted)}.thread-view dd{margin:0}.pgroup{margin-top:14px}.pgroup small{display:block;font-size:11px;font-weight:700;letter-spacing:.04em;text-transform:uppercase;color:var(--muted);margin-bottom:6px}.chips{display:flex;flex-wrap:wrap;gap:5px}.chip{font-size:12px;line-height:1.3;padding:4px 8px;border-radius:4px;border:1px solid var(--line);background:#fff;color:var(--ink)}.chip.cond{background:var(--pale);border-color:#b9c6f0;color:var(--nhs-dark);font-weight:700}.chip.prob{background:#fff;color:var(--muted)}.chip.bad{background:#fbeae8;border-color:#f0b9b3;color:var(--nhs-red);font-weight:700}.chip.warn{background:#fff8e6;border-color:#f3dc9a;color:#5c4200;font-weight:700}.chip.none{color:var(--muted);border-style:dashed}.place .flags span{font-size:11px;padding:3px 7px;background:#fff;border:1px solid var(--line)}.place .flags span.bad{color:var(--nhs-red);border-color:#f0c3bd;background:#fbeae8}.context{margin-top:18px;padding-top:16px;border-top:1px solid #b7d7c2}.context b{font-size:12px;display:block;margin-bottom:8px}.context span{display:block;font-size:12px;line-height:1.55}.context em{font-size:11px;color:var(--muted);font-style:normal;display:block;margin-top:10px}
.crossing{padding:30px 34px;position:relative;display:flex;flex-direction:column;justify-content:center}.track{height:4px;background:#d8dde0;position:absolute;left:calc(10% - 6px);right:calc(10% - 6px);top:24px;z-index:0}.trackfill{height:100%;width:0;background:var(--nhs-blue);transition:width .5s ease}.journey.complete .trackfill{background:var(--nhs-green)}.gates{position:relative;display:grid;grid-template-columns:repeat(5,1fr);gap:15px;margin-top:20px}.gate{text-align:center;cursor:pointer;border-radius:8px;padding:6px 4px}.gate:hover .gate-mark,.gate:focus-visible .gate-mark{box-shadow:0 0 0 4px rgba(0,94,184,.25)}.gate:focus-visible{outline:none}.gate-mark{width:52px;height:52px;margin:0 auto 12px;background:#fff;border:3px solid #aeb7bd;border-radius:50%;display:grid;place-items:center;font-size:23px;line-height:1;font-weight:700;color:#768692;position:relative;z-index:1;transition:.25s}.gate b{display:block;font-size:13px}.gate span{font-size:11px;color:var(--muted);display:block;margin-top:4px}.gate-state{display:inline-block;margin-top:8px;font-size:10px;font-style:normal;font-weight:700;color:#4c6272}
.gate span.gate-mark{display:grid;place-items:center;font-size:30px;line-height:1;margin:0 auto 12px;padding:0}.gate.none .gate-mark{background:#eef1f3;border-color:#d8dde0}.gate.none b,.gate.none .gate-state{color:var(--muted)}.gate.scanning .gate-mark,.gate.actionable .gate-mark{background:#fff4cf;border-color:var(--nhs-amber);color:#5c4200}.gate.blocked .gate-mark{background:#fbeae8;border-color:var(--nhs-red);color:var(--nhs-red)}.gate.cleared .gate-mark{background:var(--nhs-green);border-color:var(--nhs-green);color:#fff}.gate.actionable .gate-state,.gate.scanning .gate-state{color:#5c4200}.gate.blocked .gate-state{color:var(--nhs-red)}.gate.cleared .gate-state{color:var(--nhs-green)}.gate.blocked b{color:var(--nhs-red)}
.route-legend{display:flex;justify-content:center;gap:20px;flex-wrap:wrap;margin-top:32px}.route-legend span{font-size:11px;color:var(--muted);display:flex;align-items:center;gap:6px}.route-legend i{width:20px;height:20px;border-radius:50%;display:grid;place-items:center;font-size:11px;font-style:normal;font-weight:700;color:#fff}.route-legend .lg-red{background:var(--nhs-red)}.route-legend .lg-amber{background:var(--nhs-amber);color:#5c4200}.route-legend .lg-green{background:var(--nhs-green)}.route-note{text-align:center;margin:40px auto 0;max-width:600px}.route-note strong{display:block;font-size:20px}.route-note p{font-size:14px;color:var(--muted);line-height:1.45;margin:7px 0 0}
.actionbar{display:flex;align-items:center;justify-content:space-between;gap:22px;background:#f7f9fa;border-top:1px solid var(--line);padding:20px 28px;flex-wrap:wrap}.actionbar p{font-size:13px;line-height:1.4;color:var(--muted);margin:0;max-width:720px}.actionbar .actions{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.primary{border:0;background:var(--nhs-green);color:#fff;font-weight:700;font-size:16px;padding:14px 21px;min-width:225px;box-shadow:0 3px 0 #004d24}.primary:disabled{background:#768692;box-shadow:none;cursor:default}.secondary{border:2px solid var(--nhs-blue);background:#fff;color:var(--nhs-blue);font-weight:700;padding:11px 15px;text-decoration:none;font-size:14px;display:inline-block}.scan{height:10px;background:#d8dde0;display:none;overflow:hidden}.scan.on{display:block}.scan i{display:block;height:100%;width:35%;background:var(--nhs-blue);animation:scan 1.6s ease-in-out infinite}@keyframes scan{0%{margin-left:-35%}100%{margin-left:100%}}
.below{display:grid;grid-template-columns:1fr;gap:24px;margin-top:24px}.work,.timeline{background:#fff;box-shadow:var(--shadow);padding:26px 28px}.work h3,.timeline h3{font-size:18px;margin:0}.section-sub{font-size:13px;color:var(--muted);margin:6px 0 20px}.tasks{display:grid;grid-template-columns:repeat(2,1fr);gap:0 22px}.task{display:grid;grid-template-columns:32px 1fr auto;gap:11px;align-items:center;padding:13px 0;border-top:1px solid var(--line);cursor:pointer;text-align:left;background:none;border-left:0;border-right:0;border-bottom:0;width:100%;color:inherit}.task:hover b{color:var(--nhs-blue)}.task-check{width:27px;height:27px;border:2px solid #aeb7bd;display:grid;place-items:center;color:#fff;font-size:13px;font-weight:700}.task.done .task-check{background:var(--nhs-green);border-color:var(--nhs-green)}.task.busy .task-check{border-color:var(--nhs-amber);background:#fff4cf;color:#5c4200}.task.bad .task-check{border-color:var(--nhs-red);background:#fbeae8;color:var(--nhs-red)}.task b{font-size:13px;display:block}.task small{font-size:11px;color:var(--muted);display:block;margin-top:3px}.task.bad small{color:var(--nhs-red)}.task .owner{font-size:11px;color:var(--nhs-blue);font-weight:700}
.confirmations{margin-top:18px;border-top:3px solid var(--nhs-amber)}.confirm-title{font-size:13px;font-weight:700;padding:13px 0 4px}.confirm{display:grid;grid-template-columns:1fr auto;align-items:center;gap:16px;padding:12px 0;border-top:1px solid var(--line)}.confirm b,.confirm small{display:block}.confirm b{font-size:13px}.confirm small{font-size:11px;color:var(--muted);margin-top:3px;line-height:1.45}.confirm button{border:2px solid var(--nhs-blue);background:#fff;color:var(--nhs-blue);font-weight:700;padding:9px 12px}.confirm.done button{border-color:var(--nhs-green);background:var(--nhs-green);color:#fff;cursor:default}.confirm.sent button{border-color:#768692;color:#768692;cursor:default}
.clock{margin-top:26px}.clockline{display:grid;grid-template-columns:78px 1fr 80px;gap:12px;align-items:center;margin:15px 0}.clockline strong{font-size:14px}.bar{height:22px;background:#e5e8ea;position:relative}.bar i{height:100%;display:block}.usual i{background:#768692}.fast i{background:var(--nhs-blue)}.clockline span{font-size:12px;color:var(--muted);text-align:right}.saving{margin-top:24px;padding:18px;background:#e9f5ed;border-left:5px solid var(--nhs-green)}.saving.pending{background:var(--pale);border-left-color:var(--nhs-blue)}.saving strong{display:block;font-size:28px;color:var(--nhs-green)}.saving.pending strong{color:var(--nhs-blue)}.saving span{font-size:12px;line-height:1.45;color:var(--muted)}.truth{margin-top:18px;font-size:11px;line-height:1.5;color:var(--muted)}.truth b{color:var(--ink)}
.pack{margin-top:24px;background:#fff;box-shadow:var(--shadow);border-top:6px solid var(--nhs-dark)}.pack-head{display:flex;justify-content:space-between;align-items:center;gap:20px;padding:23px 28px;border-bottom:1px solid var(--line)}.pack-head h3{font-size:20px;margin:0}.pack-head p{font-size:13px;color:var(--muted);margin:5px 0 0}.draft-state{font-size:12px;font-weight:700;color:var(--nhs-blue);background:#e8edff;padding:8px 11px}.draft-state.sent{color:var(--nhs-green);background:#e9f5ed}
.pack-grid{display:grid;grid-template-columns:360px 1fr}.meds{padding:25px 28px;background:#f7f9fa;border-right:1px solid var(--line)}.meds h4,.letter h4{font-size:16px;margin:0 0 5px}.meds>p,.letter-top p{font-size:12px;color:var(--muted);line-height:1.45;margin:0}
.results{display:grid;grid-template-columns:repeat(3,1fr);gap:1px;background:var(--line);margin-top:18px}.result{background:#fff;padding:12px}.result small,.result strong{display:block}.result small{font-size:10px;color:var(--muted)}.result strong{font-size:15px;margin-top:3px}.result.flag strong{color:var(--nhs-red)}
.medicine{margin-top:18px;background:#fff;border-left:5px solid var(--nhs-amber);padding:16px}.medicine.verified{border-left-color:var(--nhs-green)}.medicine strong{font-size:15px;display:block}.medicine dl{display:grid;grid-template-columns:88px 1fr;gap:8px 12px;margin:14px 0 0}.medicine dt{font-size:11px;color:var(--muted)}.medicine dd{font-size:12px;font-weight:700;margin:0}.medicine .med-state{color:#5c4200}.medicine.verified .med-state{color:var(--nhs-green)}.med-note{font-size:11px!important;line-height:1.5!important;margin-top:16px!important;padding-top:14px;border-top:1px solid var(--line)}
.letter{padding:25px 28px}.letter-top{display:flex;justify-content:space-between;align-items:flex-start;gap:20px}.letter-patient{margin-top:18px;padding:11px 13px;background:#f0f4f5;font-size:12px}.letter-patient b{font-size:13px}.letter-fields{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:15px;margin-top:16px}.letter-field.full{grid-column:1/-1}.letter label{display:block;font-size:12px;font-weight:700;margin:0 0 7px}.letter textarea{display:block;width:100%;border:2px solid #768692;padding:11px 12px;font:14px/1.45 "Frutiger W01",Arial,sans-serif;color:var(--ink);background:#fff;min-height:96px;resize:vertical}.letter-field.full textarea{min-height:82px}.letter textarea:focus{outline:4px solid #ffdd00;outline-offset:0;border-color:#212b32}.letter-actions{display:flex;align-items:center;gap:12px;flex-wrap:wrap;margin-top:14px}.letter-actions button{font-weight:700;padding:11px 15px}.letter-actions button:disabled{opacity:.45;cursor:default}.letter-actions span{font-size:12px;color:var(--muted)}.letter-prov{margin-top:12px;font-size:11px;color:var(--muted)}.letter-prov b{color:var(--ink)}
.foot{margin-top:24px;font-size:11px;color:var(--muted)}
.overlay{position:fixed;inset:0;background:rgba(33,43,50,.55);display:none;place-items:center;padding:24px;z-index:50}.overlay.open{display:grid}.panel{background:#fff;width:min(820px,100%);max-height:90vh;overflow:auto;box-shadow:var(--shadow);border-top:6px solid var(--nhs-blue)}.panel header{display:flex;justify-content:space-between;align-items:flex-start;gap:16px;padding:20px 24px;border-bottom:1px solid var(--line)}.panel h3{font-size:18px;margin:0}.panel header p{font-size:12px;color:var(--muted);margin:4px 0 0}.ovbody{padding:6px 24px 24px}
.pi{padding:14px 0;border-top:1px solid var(--line)}.pi:first-child{border-top:0}.pi .row{display:flex;gap:10px;align-items:baseline;flex-wrap:wrap}.pi .row .own{font-size:11px;color:var(--nhs-blue);font-weight:700}.pi .row b{font-size:14px}.pi .ev{font-size:12px;color:var(--muted);margin-top:4px}.pi .ev code{font-family:ui-monospace,monospace;font-size:11px;background:var(--wash);padding:1px 5px}ol.plan{margin:8px 0 0;padding-left:22px;font-size:13px;line-height:1.55}ol.plan li{margin:3px 0}.kv{display:grid;grid-template-columns:110px 1fr;gap:0 14px;padding:8px 0;border-top:1px solid var(--line);font-size:13px}.kv .k{font-size:12px;color:var(--muted)}.kv .v{line-height:1.5}.err{color:var(--nhs-red)}.tag{font-size:9px;font-weight:700;letter-spacing:.05em;text-transform:uppercase;padding:2px 5px;background:var(--wash);color:var(--muted)}.tag.ai{background:var(--pale);color:var(--nhs-blue)}.tag.sim{background:#e9f5ed;color:var(--nhs-green)}.planfoot{display:flex;align-items:center;gap:14px;margin-top:18px;padding-top:14px;border-top:1px solid var(--line)}.planfoot .sub{font-size:12px;color:var(--muted)}.grp{margin-top:16px}.grp h4{font-size:13px;margin:0 0 4px}.grp h4 span{color:var(--muted);font-weight:400;font-size:11px;margin-left:8px}.empty{color:var(--muted);font-size:13px;padding:14px 0}
.call{border:1px solid var(--line);padding:10px 14px;margin-top:8px}.call .say{display:grid;grid-template-columns:18px 62px minmax(0,1fr);gap:8px;align-items:baseline;font-size:13px}.call .ic{width:18px;height:18px;border-radius:50%;display:grid;place-items:center;font-size:11px;font-weight:700;color:#fff;background:var(--nhs-green);align-self:start;line-height:1}.call.read .ic{background:#aeb7bd}.call.bad .ic{background:var(--nhs-red)}.call .t{color:var(--muted);font-size:12px;font-variant-numeric:tabular-nums}.call .what{font-weight:700}.call.read .what{font-weight:400;color:var(--muted)}.call .out{display:block;color:var(--muted);font-size:12px;margin-top:1px}.call.bad .out{color:var(--nhs-red)}.call.read{padding:5px 14px;border-color:transparent;margin-top:2px}
details.reqdd{margin:4px 0 0 88px}details.reqdd summary{cursor:pointer;color:var(--nhs-blue);font-size:12px;font-weight:700;list-style:none;display:flex;width:max-content;gap:4px;user-select:none}details.reqdd summary::-webkit-details-marker{display:none}details.reqdd summary::before{content:'▸';font-size:10px}details.reqdd[open] summary::before{content:'▾'}details.reqdd .head{display:flex;gap:10px;flex-wrap:wrap;font-size:12px;margin-top:8px}details.reqdd .head .m{font-weight:700;color:var(--nhs-blue)}details.reqdd .meta{font-size:11px;color:var(--muted);margin-top:8px;word-break:break-all}details.reqdd pre{background:var(--wash);padding:8px 10px;font-size:11px;line-height:1.5;max-height:320px;overflow:auto;white-space:pre-wrap;word-break:break-word;margin:4px 0 0}
@media(max-width:1050px){.intro{flex-direction:column;align-items:flex-start}.route{grid-template-columns:180px 1fr 230px}.crossing{padding-left:20px;padding-right:20px}.gates{gap:7px}.below{grid-template-columns:1fr}.pack-grid{grid-template-columns:300px 1fr}}
@media(max-width:900px){.shell{grid-template-columns:1fr}.side{position:static;min-height:0;border-right:0;border-bottom:1px solid var(--line)}.plist{flex-direction:row;flex-wrap:wrap}.prow{width:auto;min-width:220px}.route{grid-template-columns:1fr}.hospital,.home{border-left:0;border-right:0}.crossing{padding:34px 24px}.pack-grid{grid-template-columns:1fr}.meds{border-right:0;border-bottom:1px solid var(--line)}}
@media(max-width:760px){.top{padding:18px}.page{padding:24px 16px}.intro h2{font-size:31px}.track{display:none}.gates{grid-template-columns:1fr}.gate{display:grid;grid-template-columns:50px 1fr;align-items:center;text-align:left;column-gap:12px}.gate-mark{grid-row:1/3;margin:0}.actionbar{align-items:stretch;flex-direction:column}.tasks{grid-template-columns:1fr}.results,.letter-fields{grid-template-columns:1fr}.letter-field.full{grid-column:auto}.doctor{min-width:0}}
</style>
</head>
<body>
<div class="boot" id="boot" role="status" aria-live="polite">
  <div class="card">
    <span class="homeward-logo" aria-hidden="true"><svg viewBox="0 0 64 64"><path d="M8 29 32 8l24 21v27H8Z" fill="#005eb8"/><path d="M20 24v24h8V37h8v11h8V24h-8v7h-8v-7Z" fill="#fff"/><path d="M40 45h12l-5-5 4-4 12 12-12 12-4-4 5-5H40Z" fill="#00a499"/></svg></span>
    <div class="spinner" aria-hidden="true"></div>
    <h2>Setting up the ward round</h2>
    <p class="phase" id="bootPhase">Connecting to Homeward…</p>
    <ol id="bootSteps">
      <li data-step="1"><i></i>Joining the simulator world</li>
      <li data-step="2"><i></i>Admitting patients to the ward</li>
      <li data-step="3"><i></i>Loading patient records</li>
      <li data-step="4"><i></i>Reading the records for discharge barriers</li>
    </ol>
    <p class="note">Nothing is shown until every record has been read; no action is taken until staff approve the plan.</p>
  </div>
</div>
<div class="app" hidden>
  <div class="nhsbar"></div>
  <header class="top">
    <div class="wordmark"><span class="homeward-logo" aria-label="Homeward logo"><svg viewBox="0 0 64 64" role="img" aria-hidden="true"><path d="M8 29 32 8l24 21v27H8Z" fill="#005eb8"/><path d="M20 24v24h8V37h8v11h8V24h-8v7h-8v-7Z" fill="#fff"/><path d="M40 45h12l-5-5 4-4 12 12-12 12-4-4 5-5H40Z" fill="#00a499"/></svg></span><span><h1>Homeward</h1><p>Clinical discharge coordination</p></span></div>
    <span class="topspace"></span>
    <div class="patient" id="patientHead"></div>
    <span class="allergy none" id="allergy">Allergies: not loaded</span>
  </header>
  <div class="shell">
  <aside class="side"><input class="find" id="find" type="search" placeholder="Find a patient or SIM number" autocomplete="off"><div class="label" id="plistLabel">Patients</div><div class="plist" id="plist"></div></aside>
  <main class="page">
    <section class="intro" id="intro"></section>
    <section class="journey" id="journey" aria-live="polite">
      <header class="journey-head"><span><h3>The route from hospital to home</h3></span><span class="status" id="status"></span></header>
      <div class="why" id="why" aria-live="polite"></div>
      <div class="scan" id="scan"><i></i></div>
      <div class="route">
        <section class="place hospital" id="placeHospital"></section>
        <section class="crossing">
          <div class="gates" id="gates"></div>
          <div class="route-legend" id="routeLegend"><span><i class="lg-red"></i>Blocks discharge</span><span><i class="lg-amber"></i>Action required or in progress</span><span><i class="lg-green">✓</i>Verified</span></div>
          <div class="route-note" id="routeNote"></div>
        </section>
        <section class="place home" id="placeHome"></section>
      </div>
      <footer class="actionbar"><p id="actionText"></p><span class="actions"><button class="secondary" data-act="trace">What the agent did</button><a class="secondary" id="receiptLink" href="#">Receipt</a><button class="primary" id="mainAction" data-act="main"></button></span></footer>
    </section>
    <div class="below">
      <section class="work"><h3>Work required</h3><p class="section-sub" id="workSub"></p><div class="tasks" id="tasks"></div><div class="confirmations" id="confirmations"></div></section>
    </div>
    <section class="pack">
      <header class="pack-head"><span><h3>Discharge pack</h3><p>Only information needed for the hospital-to-home handover.</p></span><span class="draft-state" id="draftState"></span></header>
      <div class="pack-grid">
        <section class="meds" id="meds"></section>
        <section class="letter">
          <div class="letter-top"><span><h4>Discharge letter</h4><p id="letterSub">Drafted by the agent from the record; editable by the responsible clinician. Saved sections are what the agent sends.</p></span><button class="secondary" data-act="refresh" id="refreshLetter">Reset to the agent's draft</button></div>
          <div class="letter-patient" id="letterPatient"></div>
          <div class="letter-fields" id="letterFields"></div>
          <div class="letter-actions"><button class="primary" data-act="save" id="saveLetter">Save draft</button><span id="saveState" aria-live="polite">Not yet saved</span></div>
          <p class="letter-prov" id="letterProv"></p>
        </section>
      </div>
    </section>
    <p class="foot" id="foot"></p>
  </main>
  </div>
</div>
<div class="overlay" id="overlay"><div class="panel" role="dialog" aria-modal="true"><header><div><h3 id="ovTitle"></h3><p id="ovSub"></p></div><button class="secondary" data-act="close">Close</button></header><div class="ovbody" id="ovBody"></div></div></div>
<script>
const esc = (s) => String(s ?? '').replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]))
const q = (s) => esc(String(s ?? '').replace(/"/g, ''))
const KINDS = ['clinical-hold', 'medicines', 'bloods', 'device', 'visit', 'summary', 'follow-up', 'care-package']
const kindOf = (i) => KINDS.find((k) => i.id.endsWith('-' + k)) || 'other'
const OWNER = { gp: 'GP record', hospital: 'Hospital', pharmacy: 'Pharmacy', community: 'Community', diagnostics: 'Diagnostics', wearables: 'Home Health', clinician: 'Clinician' }
const SERVICE = { gp: 'GP practice', hospital: 'hospital', pharmacy: 'pharmacy', community: 'community team', diagnostics: 'diagnostics service', wearables: 'home monitoring service', clinician: 'clinician' }
const WORKING = ['approved', 'resolving', 'awaiting_verification']
const HUMAN = ['clinical_hold', 'blocked_human']
const GATES = [
  { label: 'Clinical', sub: 'Readiness decision', kinds: ['clinical-hold'] },
  { label: 'Medicines', sub: 'Supply and collection', kinds: ['medicines'] },
  { label: 'Monitoring', sub: 'Bloods and home watch', kinds: ['bloods', 'device'] },
  { label: 'Support', sub: 'Visit and home access', kinds: ['visit', 'care-package'] },
  { label: 'Handover', sub: 'GP letter and follow-up', kinds: ['summary', 'follow-up'] },
]
const JOB = { medicines: 'Reconcile discharge medicines', bloods: 'Arrange repeat blood monitoring', device: 'Connect home monitor', visit: 'Book home support visit', summary: 'Send the discharge letter to the GP', 'follow-up': 'Create GP follow-up' }
const DONE = { medicines: 'Medicines dispensed and collected', bloods: 'Bloods ordered and resulted', device: 'Home monitor connected, first reading received', visit: 'Home support visit completed', summary: 'Discharge letter sent, in the GP inbox', 'follow-up': 'GP follow-up task on the worklist' }
const CAVEAT = { medicines: 'Collection is recorded; this does not prove adherence or ongoing supply.', bloods: 'Results are available; this does not constitute clinical review of those results.', device: 'A reading was received; this does not confirm sustained monitoring.', visit: 'The visit is completed; this does not confirm ongoing care-package funding.', summary: 'The letter reached the GP inbox; this does not confirm the GP has read it.', 'follow-up': 'The task exists on the GP worklist; this does not confirm the review has happened.', 'clinical-hold': 'Clinician sign-off is a human decision recorded here, not an automated judgement.', 'care-package': 'Escalated to a human decision; nothing here resolves the funding question.' }
const isHuman = (i) => i.owner === 'clinician' || HUMAN.includes(i.state)
const simOutage = (i) => i.state === 'failed' && /HTTP (0|5[0-9][0-9])|no response within/.test(i.error || '')
const jobTitle = (i) => {
  const k = kindOf(i)
  if (k === 'summary' && i.draftOnly) return i.state === 'verified' ? 'Discharge letter drafted and held (not sent)' : 'Prepare the discharge letter (held, not sent)'
  if (i.state === 'verified') return DONE[k] || i.title
  return JOB[k] || i.proposedAction || i.title
}
const shortState = (i) => {
  const svc = SERVICE[i.owner] || i.owner
  if (i.state === 'proposed') return 'Awaiting approval of the plan'
  if (i.state === 'approved') return 'Approved, not started'
  if (i.state === 'resolving') return 'Acting now in the ' + svc
  if (i.state === 'awaiting_verification') return 'Done in the ' + svc + '; verifying after time moves'
  if (i.state === 'verified') return i.verification ? 'Verified: ' + i.verification.observed : 'Verified'
  if (i.state === 'failed') return simOutage(i) ? 'Simulator did not respond; a re-run retries it' : 'Failed: ' + (i.error || 'see detail')
  if (i.state === 'clinical_hold') return 'Clinician confirmation needed'
  if (i.state === 'blocked_human') return i.escalation ? 'Escalated to ' + i.escalation.responsibleTeam + '; decision pending' : 'External decision needed'
  return i.state
}
function gateState(items, n) {
  if (!items.length) return { cls: 'none', mark: '', label: 'No barrier found' }
  if (items.some((i) => i.state === 'failed')) return { cls: 'blocked', mark: '', label: items.some(simOutage) ? 'Simulator did not respond' : 'Action failed' }
  if (items.some((i) => i.state === 'clinical_hold')) return { cls: 'blocked', mark: '', label: 'Clinician confirmation needed' }
  const bh = items.find((i) => i.state === 'blocked_human')
  if (bh) return { cls: 'blocked', mark: '', label: bh.escalation ? 'Escalated, decision pending' : 'External decision needed' }
  if (items.every((i) => i.state === 'verified')) return { cls: 'cleared', mark: '✓', label: 'Verified' }
  if (items.some((i) => WORKING.includes(i.state))) return { cls: 'scanning', mark: '', label: items.some((i) => i.state === 'awaiting_verification') ? 'Verifying' : 'In progress' }
  if (items.some((i) => i.state === 'proposed')) return { cls: 'actionable', mark: '', label: 'Action required' }
  return { cls: '', mark: '', label: 'Not checked' }
}
const first = (p) => (p.name || '').split(' ')[0]
const initials = (p) => (p.name || '?').split(' ').map((w) => w[0]).slice(0, 2).join('')
/** Stable colour per patient from the name: white initials on a saturated hue, always the same for the same person. */
/** "Dr Ada Sim 0" -> "AS": drop titles and trailing numbers, first letter of the first two names. */
const clinicianInitials = (name) => {
  const words = String(name || '').split(/\\s+/).filter((w) => w && !/^(dr|mr|mrs|ms|miss|prof|nurse|sister)\\.?$/i.test(w) && !/^\\d+$/.test(w))
  return (words.slice(0, 2).map((w) => w[0].toUpperCase()).join('') || '?')
}
const avatarStyle = (p) => {
  let h = 0
  for (const c of (p.name || '?')) h = (h * 31 + c.charCodeAt(0)) % 360
  return 'background:hsl(' + h + ' 52% 38%);color:#fff'
}
const hhmm = (ms) => new Date(ms).toTimeString().slice(0, 8)
const rel = (min) => { const m = Math.max(0, Math.round(min)); const d = Math.floor(m / 1440), h = Math.floor((m % 1440) / 60); return (d ? d + 'd ' : '') + h + 'h ' + String(m % 60).padStart(2, '0') + 'm' }

// What the page says about the whole journey, from the item states alone.
function readiness(p, s) {
  const items = p.items
  const human = items.filter((i) => HUMAN.includes(i.state))
  const failed = items.filter((i) => i.state === 'failed')
  const proposed = items.filter((i) => i.state === 'proposed')
  const working = items.filter((i) => WORKING.includes(i.state))
  const open = items.filter((i) => i.state !== 'verified').length
  const ready = items.length && !open
  const outage = failed.some(simOutage)
  const R = (o) => o
  if (p.stage === 'discharged') return R({ badge: 'Discharged home', badgeCls: 'ready', status: 'Discharged in the hospital record', statusCls: 'ready', note: ['Every dependency has evidence', 'The attendance is closed in the hospital record. The receipt keeps the evidence.'], action: 'Discharged', disabled: true, text: 'The discharge is recorded in the hospital EPR.', complete: true })
  if (ready) return R({ badge: 'Ready for clinical discharge decision', badgeCls: 'ready', status: 'Ready for clinical decision', statusCls: 'ready', note: ['Every dependency now has evidence', 'The responsible clinician can make the discharge decision.'], action: 'Review complete', disabled: true, text: 'The evidence is complete. The final discharge decision remains with the clinician.', complete: true })
  if (!items.length) return R({ badge: s.busy ? 'Checking the route' : 'Nothing found yet', badgeCls: 'reviewing', status: s.phase || 'Reading the records', statusCls: 'reviewing', note: [s.busy ? 'Checking the records' : 'No barriers found', 'One review reads the hospital, pharmacy, diagnostics, community, home monitoring and GP records.'], action: 'Checking records', disabled: true, text: 'Homeward will surface what it can coordinate and what still requires a person.' })
  if (proposed.length) return R({ badge: 'Not ready: ' + open + ' outstanding', badgeCls: '', status: 'Not ready: plan awaiting review', statusCls: '', note: [proposed.length + ' action' + (proposed.length === 1 ? '' : 's') + ' can proceed; ' + human.length + ' decision' + (human.length === 1 ? '' : 's') + ' need' + (human.length === 1 ? 's' : '') + ' people'], action: 'Review plan (' + proposed.length + ' action' + (proposed.length === 1 ? '' : 's') + ')', disabled: false, kind: 'plan', text: '' })
  if (working.length) {
    const waiting = !s.busy && /approve/i.test(s.phase || '')
    return R({ badge: 'Not ready: ' + open + ' outstanding', badgeCls: 'reviewing', status: s.busy ? (s.phase || 'Coordinating') : waiting ? 'Approved, starting shortly' : 'Approved, coordinating', statusCls: 'reviewing', note: [s.busy ? (s.phase || 'Coordinating') : waiting ? 'Approved, starting shortly' : 'Coordinating ' + working.length + ' action' + (working.length === 1 ? '' : 's'), waiting ? 'The agent starts this plan on its next round; other patients do not need approving first.' : 'Each approved step is re-read in the owning service after time moves.'], action: 'Coordinating ' + working.length + ' action' + (working.length === 1 ? '' : 's'), disabled: true, text: 'Approved actions run in parallel; each is verified against the record of the service that owns it.', scanning: s.busy })
  }
  if (failed.length) return R({ badge: 'Not ready: ' + failed.length + ' action' + (failed.length === 1 ? '' : 's') + ' failed', badgeCls: '', status: 'Not ready: action failed', statusCls: '', note: [failed.length + ' action' + (failed.length === 1 ? '' : 's') + ' failed', outage ? 'The simulator did not respond; nothing was changed. Re-run against the same world to retry.' : 'Open the task for the error.'], action: 'Re-run required', disabled: true, text: outage ? 'A simulator outage, not a record problem. The re-run retries every failed action with fresh keys.' : 'The failure needs a person to look at it.' })
  return R({ badge: 'Not ready: ' + human.length + ' confirmation' + (human.length === 1 ? '' : 's') + ' outstanding', badgeCls: '', status: 'Not ready: ' + human.length + ' confirmation' + (human.length === 1 ? '' : 's') + ' remain' + (human.length === 1 ? 's' : ''), statusCls: '', note: ['Operational route verified', 'Homeward has re-read every receiving service. ' + human.map((i) => shortTitle(i.title)).join('; ') + ' remain' + (human.length === 1 ? 's' : '') + ' a named human decision.'], action: 'Awaiting confirmations', disabled: true, text: 'Operational work is verified. Record the named confirmations below.' })
}

/**
 * The one line that must always be true and visible: is the agent doing
 * anything for this patient right now, and if not, exactly why and who
 * has to do what next. Never leaves a grey button unexplained.
 */
function whyStatus(p, s) {
  const items = p.items
  const proposed = items.filter((i) => i.state === 'proposed')
  const working = items.filter((i) => WORKING.includes(i.state))
  const failed = items.filter((i) => i.state === 'failed')
  const holds = items.filter((i) => i.state === 'clinical_hold')
  const blocked = items.filter((i) => i.state === 'blocked_human')
  const n = (k, w) => k + ' ' + w + (k === 1 ? '' : 's')
  if (p.stage === 'discharged') return { tone: 'good', head: 'Done: discharged home', why: 'Every item was verified and the attendance is closed in the hospital record.', next: 'Nothing further for the agent or for staff.' }
  if (!items.length) return s.busy
    ? { tone: 'info', live: true, head: 'Agent reading the records', why: s.phase || 'Reading every service for this patient.', next: 'No action needed yet. Barriers appear here as they are found.' }
    : { tone: 'good', head: 'No barriers found', why: 'The agent read the hospital, pharmacy, diagnostics, community, home monitoring and GP records and found nothing outstanding.', next: 'The clinician makes the discharge decision.' }
  if (working.length) return { tone: 'info', live: true, head: 'Agent working: ' + n(working.length, 'action'),
    why: s.busy ? (s.phase || 'Acting in the owning services.') : 'Approved actions run on the next round; results are re-read after the sim clock moves.',
    next: 'No action needed from you' + (proposed.length ? ', except ' + n(proposed.length, 'action') + ' still awaiting approval' : '') + (holds.length ? '; the clinical hold still needs the clinician' : '') + '.' }
  if (failed.length) return { tone: 'bad', head: 'Agent stopped: ' + n(failed.length, 'action') + ' failed',
    why: failed.map((i) => (JOB[kindOf(i)] || i.title) + ' failed: ' + (i.error || 'no reason recorded')).join(' '),
    next: failed.some(simOutage) ? 'The simulator did not respond and nothing was changed. Re-run against the same world to retry.' : 'Open the task for the error. Re-running against the same world retries it; otherwise it needs a person.' }
  if (proposed.length) return { tone: 'warn', head: 'Agent idle: waiting for your approval',
    why: n(proposed.length, 'action') + ' drafted from the record. Nothing runs until staff approve the plan.',
    next: 'Press Review plan, check the steps, then Approve. The agent starts within seconds' + (holds.length || blocked.length ? '; ' + n(holds.length + blocked.length, 'item') + ' will still need a person' : '') + '.' }
  if (holds.length) return { tone: 'bad', head: 'Agent idle: needs the clinician',
    why: holds.map((i) => '"' + shortTitle(i.title) + '" can only be cleared by a clinician. The agent has no action for it and will not invent one.').join(' '),
    next: 'Clinician: read the thread, and once the review is done press Record confirmation. Discharge is gated on it; a confirmation can be undone until discharge.', link: threadLink(holds[0]) }
  if (blocked.length) { const b = blocked[0]; const e = b.escalation
    return { tone: 'bad', head: 'Agent idle: waiting on an outside decision',
      why: shortTitle(b.title) + '. ' + (b.humanReason || 'No API action can clear this.'),
      next: e ? 'Handed to ' + e.responsibleTeam + ': ' + e.nextAction + ' The agent will not act until they decide; nothing here is stuck on software.'
              : 'Press Prepare escalation to hand this to the team that owns the decision. The agent cannot clear it.' } }
  return { tone: 'good', head: 'Ready: every item verified', why: 'All operational work is verified in the service that owns it.', next: 'The responsible clinician makes the discharge decision.' }
}
/** Starting-point panel helpers: de-duplicated, labelled, colour-coded chips instead of one run-on sentence. */
const uniq = (xs) => [...new Set(xs.map((x) => String(x).trim()).filter(Boolean))]
const chip = (text, tone, title) => '<span class="chip ' + tone + '"' + (title ? ' title="' + esc(title) + '"' : '') + '>' + esc(text) + '</span>'
const placeGroup = (label, chips, empty) => (chips.length || empty)
  ? '<div class="pgroup"><small>' + label + '</small><div class="chips">' + (chips.join('') || '<span class="chip none">' + esc(empty) + '</span>') + '</div></div>'
  : ''
function renderWhy(p, s) {
  const w = whyStatus(p, s)
  const el = document.getElementById('why')
  el.className = 'why ' + w.tone + (w.live ? ' live' : '')
  el.innerHTML = '<i class="ic" aria-hidden="true"></i><div><b>' + esc(w.head) + '</b><span><em>Why:</em> ' + esc(w.why) + '</span><span><em>Next:</em> ' + esc(w.next) + (w.link ? ' ' + w.link : '') + '</span></div>'
}

let lastState = null, lastText = '', selectedPatient = null, overlayKey = null, patFilter = ''
let letterDirty = false, lastLetterJson = ''
const openIds = new Set()
document.addEventListener('toggle', (e) => { const el = e.target; if (el && el.id) { if (el.open) openIds.add(el.id); else openIds.delete(el.id) } }, true)
const restoreOpen = () => { for (const id of openIds) { const el = document.getElementById(id); if (el) el.open = true } }
const pretty = (v) => { try { return JSON.stringify(v, null, 2) } catch { return String(v) } }
const prettyJson = (raw) => { try { return JSON.stringify(JSON.parse(raw), null, 2) } catch { return raw } }
const wireId = (t) => 'wire-' + t.at + '-' + String(t.idempotencyKey || t.path).replace(/[^a-z0-9-]/gi, '_')
const wireRow = (t) => {
  const write = t.method !== 'GET'
  const icon = t.ok ? (write ? '✓' : '·') : '✕'
  const sent = t.request !== undefined ? pretty(t.request) : (t.sent ? prettyJson(t.sent) : '')
  return '<div class="call' + (t.ok ? '' : ' bad') + (write ? '' : ' read') + '"><div class="say"><span class="ic">' + icon + '</span>' +
    '<span class="t" title="real time">' + hhmm(t.at) + '</span><span><span class="what">' + esc(t.headline || t.action || t.path.split('?')[0]) + '</span>' +
    (t.outcome ? '<span class="out">' + esc(t.outcome) + '</span>' : '') + '</span></div>' +
    '<details class="reqdd" id="' + wireId(t) + '"><summary>Show request</summary>' +
    '<div class="head"><span class="m">' + esc(t.method) + '</span><span>' + esc(t.action || t.path.split('?')[0]) + '</span><span>' + (t.ok ? 'HTTP ' + t.status : 'FAILED ' + (t.status || '')) + '</span>' + (t.got ? '<span><span class="tag sim">sim</span> ' + esc(t.got) + '</span>' : '') + '</div>' +
    (sent ? '<div class="meta">agent sent:</div><pre>' + esc(sent) + '</pre>' : '') +
    (t.reply !== undefined ? '<div class="meta">service replied:</div><pre>' + esc(pretty(t.reply)) + '</pre>' : '') +
    (t.idempotencyKey ? '<div class="meta">idempotency key · ' + esc(t.idempotencyKey) + '</div>' : '') + '</details></div>'
}
const callsFor = (s, i) => (s.trace || []).filter((t) => t.idempotencyKey && t.idempotencyKey.includes(i.id))
const patient = (s) => s.patients.find((p) => p.patientId === selectedPatient) || s.patients[0]
const summaryItem = (p) => p.items.find((i) => kindOf(i) === 'summary')
const agentDraft = (s, p) => {
  const it = summaryItem(p)
  if (!it) return null
  const saves = callsFor(s, it).filter((t) => t.request && t.request.type === 'save_discharge_summary')
  return saves.length ? saves[saves.length - 1].request.dischargeSections : null
}
const LETTER_FIELDS = [['reason', 'Reason for admission', true], ['course', 'Clinical course', false], ['diagnoses', 'Diagnoses', false], ['medicationChanges', 'Discharge medicines and changes', false], ['results', 'Pertinent results', false], ['followUp', 'Follow-up and support', false], ['gpActions', 'Actions for the GP practice', true]]

// --- Boot screen: blank page with a spinner and the current setup step until the ward is ready ---
let booted = false
const SETUP_RE = /joining|admitting|confirming|loading patient|reading the records|detect/i
function bootStep(phase) {
  const t = (phase || '').toLowerCase()
  if (/joining/.test(t)) return 1
  if (/admitting|confirming/.test(t)) return 2
  if (/loading patient/.test(t)) return 3
  if (/reading the records|detect/.test(t)) return 4
  return 0
}
function renderBoot(s) {
  const phase = s ? (s.phase || 'Joining the simulator world') : 'Connecting to Homeward…'
  document.getElementById('bootPhase').textContent = phase
  const step = s ? bootStep(s.phase) : 0
  for (const li of document.querySelectorAll('#bootSteps li')) {
    const n = Number(li.dataset.step)
    li.className = n < step ? 'done' : n === step ? 'now' : ''
  }
}
function wardReady(s) {
  if (!s.patients.length) return false
  return !(s.busy && SETUP_RE.test(s.phase || ''))
}

function render(s) {
  lastState = s
  if (!booted) {
    if (!wardReady(s)) { renderBoot(s); return }
    booted = true
    document.getElementById('boot').classList.add('off')
    document.querySelector('.app').hidden = false
  }
  if (!selectedPatient || !s.patients.some((p) => p.patientId === selectedPatient)) selectedPatient = (s.patients[0] || {}).patientId
  const p = patient(s)
  const flt = patFilter.trim().toLowerCase()
  const shown = s.patients.filter((x) => !flt || x.name.toLowerCase().includes(flt) || x.patientId.toLowerCase().includes(flt))
  document.getElementById('plistLabel').textContent = flt ? shown.length + ' of ' + s.patients.length + ' patients' : 'Patients · ' + s.patients.length
  document.getElementById('plist').innerHTML = shown.map((x) => {
    const r = readiness(x, s)
    const tone = r.complete ? 'good' : x.items.some((i) => HUMAN.includes(i.state) || i.state === 'failed') ? 'bad' : 'warn'
    const word = r.complete ? (x.stage === 'discharged' ? 'Discharged' : 'Ready') : tone === 'bad' ? 'Needs a person' : x.items.some((i) => i.state === 'proposed') ? 'Awaiting approval' : x.items.length ? 'In progress' : 'Checking'
    return '<button class="prow ' + tone + (x === p ? ' on' : '') + '" data-act="select" data-p="' + esc(x.patientId) + '"><span class="av" style="' + avatarStyle(x) + '">' + esc(initials(x)) + '</span><span><b>' + esc(x.name) + '</b><small>' + esc(x.patientId) + (x.location ? ' · ' + esc(x.location) : '') + '</small><em>' + word + '</em></span></button>'
  }).join('') || '<div class="none">No patient matches.</div>'
  document.getElementById('foot').textContent = 'World ' + s.world + ' · sim clock ' + (s.simNow ? new Date(s.simNow).toISOString().slice(0, 16).replace('T', ' ') : 'n/a') + (s.phase ? ' · ' + s.phase : '') + ' · synthetic simulator data (NHS-SIM); every action was executed against the simulator and independently re-read.'
  if (!p) {
    document.getElementById('patientHead').innerHTML = ''
    document.getElementById('intro').innerHTML = '<div><div class="titleline"><h2>Setting up</h2><span class="top-readiness reviewing">' + esc(s.phase || 'Joining the simulator world') + '</span></div><p>The ward list appears as records load.</p></div>'
    document.getElementById('scan').classList.add('on')
    return
  }
  const pr = p.profile || {}
  const r = readiness(p, s)
  document.getElementById('patientHead').innerHTML = '<span class="patient-avatar" style="' + avatarStyle(p) + '">' + esc(initials(p)) + '</span><span><strong>' + esc(p.name) + '</strong><span>' + esc(p.patientId) + (p.location ? ', ' + esc(p.location) : '') + (p.stage ? ' · ' + esc(p.stage) : '') + '</span></span>'
  const al = document.getElementById('allergy')
  al.textContent = (pr.allergies || []).length ? pr.allergies.join(', ') + ' allergy' : 'No allergy recorded'
  al.className = 'allergy' + ((pr.allergies || []).length ? '' : ' none')
  al.title = 'GP record'
  document.getElementById('intro').innerHTML =
    '<div><div class="titleline"><h2>' + esc(first(p)) + '\\u2019s discharge plan</h2><span class="top-readiness ' + r.badgeCls + '">' + esc(r.badge) + '</span></div>' +
    '</div>' +
    '<div class="doctor"><span class="doctor-photo" style="' + (pr.clinician ? avatarStyle({ name: pr.clinician }) : '') + '">' + esc(pr.clinician ? clinicianInitials(pr.clinician) : '?') + '</span><span><strong>' + esc(pr.clinician || 'No clinician assigned') + '</strong><span>' + (pr.clinician ? 'Discharge review · hospital attendance' : 'Attendance has no named clinician') + '</span></span></div>'
  document.getElementById('journey').classList.toggle('complete', !!r.complete)
  const st = document.getElementById('status'); st.textContent = r.status; st.className = 'status ' + r.statusCls
  renderWhy(p, s)
  document.getElementById('scan').classList.toggle('on', !!(s.busy && (r.scanning || !p.items.length || /reading|detect|loading|joining|admitting/i.test(s.phase || ''))))
  const bad = (pr.facts || []).filter((f) => f.bad)
  document.getElementById('placeHospital').innerHTML = '<div class="place-icon">H</div><small>Starting point</small><h4>' + esc(p.location || p.stage || 'Hospital') + '</h4>' +
    placeGroup('Conditions', uniq(p.conditions || []).map((c) => chip(c, 'cond')), 'None recorded') +
    placeGroup('Active problems', uniq(pr.problems || []).map((c) => chip(c, 'prob')), '') +
    placeGroup('Flagged results', bad.filter((f) => /^diagnostics/.test(f.source)).map((f) => chip(f.label + ' ' + f.value, 'bad', f.source)), '') +
    placeGroup('Activity and home', bad.filter((f) => !/^diagnostics/.test(f.source)).map((f) => chip(f.label + ' ' + f.value, 'warn', f.source)), '')
  document.getElementById('placeHome').innerHTML = '<div class="place-icon">⌂</div><small>Destination</small><h4>Home situation</h4>' +
    '<p>' + (pr.ownWords ? esc(pr.ownWords.text) : 'No personal context on the GP record.') + '</p>' +
    '<div class="context"><b>What matters to ' + esc(first(p)) + '</b>' + ((p.goals || []).length ? p.goals.map((g) => '<span>' + esc(g) + '</span>').join('') : '<span>No goals recorded.</span>') +
    ((p.needs || []).length ? '<span style="margin-top:6px">Recorded needs: ' + esc(p.needs.join(', ')) + '</span>' : '') +
    '<em>Source: patient directory' + (pr.ownWords ? ' and GP personal context record ' + esc(pr.ownWords.resourceId) : '') + '</em></div>'
  const verified = p.items.filter((i) => i.state === 'verified').length
  document.getElementById('gates').innerHTML = '<div class="track"><div class="trackfill" style="width:' + (p.items.length ? Math.round(100 * verified / p.items.length) : 0) + '%"></div></div>' +
    GATES.map((g, n) => {
      const items = p.items.filter((i) => g.kinds.includes(kindOf(i)))
      const gs = gateState(items, n + 1)
      return '<div class="gate ' + gs.cls + '" data-act="gate" data-n="' + n + '" role="button" tabindex="0" title="Open this gate"><span class="gate-mark">' + gs.mark + '</span><b>' + g.label + '</b><span>' + g.sub + '</span><em class="gate-state">' + esc(gs.label) + '</em></div>'
    }).join('')
  document.getElementById('routeLegend').hidden = !p.items.length
  document.getElementById('routeNote').innerHTML = '<strong>' + esc(r.note[0]) + '</strong><p>' + esc(r.note[1]) + '</p>'
  document.getElementById('actionText').textContent = r.text
  const btn = document.getElementById('mainAction'); btn.textContent = r.action; btn.disabled = !!r.disabled; btn.dataset.kind = r.kind || ''
  document.getElementById('receiptLink').href = '/receipt?patient=' + encodeURIComponent(p.patientId)

  const ops = p.items.filter((i) => !isHuman(i))
  const humans = p.items.filter((i) => isHuman(i))
  const nFailed = ops.filter((i) => i.state === 'failed').length
  document.getElementById('workSub').textContent = !p.items.length ? 'Run the review to build an evidence-based coordination plan.' : ops.every((i) => i.state === 'verified') && ops.length ? ops.length + ' actions completed and verified in the receiving systems.' : ops.some((i) => i.state === 'proposed') ? 'Homeward can coordinate these ' + ops.length + ' actions in parallel once the plan is approved.' : nFailed ? nFailed + ' action' + (nFailed === 1 ? '' : 's') + ' failed; ' + ops.filter((i) => i.state === 'verified').length + ' verified. Open a task for the detail.' : 'Approved actions are running; each is verified after time moves.'
  document.getElementById('tasks').innerHTML = ops.map((i) => {
    const cls = i.state === 'verified' ? ' done' : i.state === 'failed' ? ' bad' : WORKING.includes(i.state) ? ' busy' : ''
    const mark = i.state === 'verified' ? '✓' : i.state === 'failed' ? '!' : WORKING.includes(i.state) ? '…' : ''
    return '<button class="task' + cls + '" data-act="item" data-id="' + esc(i.id) + '"><span class="task-check">' + mark + '</span><span><b>' + esc(jobTitle(i)) + '</b><small>' + esc(shortState(i)) + '</small></span><span class="owner">' + esc(OWNER[i.owner] || i.owner) + '</span></button>'
  }).join('') || '<div class="empty">No operational work found for this patient.</div>'
  const pending = humans.filter((i) => i.state !== 'verified')
  document.getElementById('confirmations').innerHTML = humans.length ? '<div class="confirm-title">' + (pending.length ? pending.length + ' named confirmation' + (pending.length === 1 ? '' : 's') + ' still protect' + (pending.length === 1 ? 's' : '') + ' the final decision' : 'All named confirmations are recorded') + '</div>' +
    humans.map(confirmRow).join('') : ''
  renderPack(s, p)
  if (overlayKey) renderOverlay()
  restoreOpen()
}

function renderPack(s, p) {
  const pr = p.profile || {}
  const med = p.items.find((i) => kindOf(i) === 'medicines')
  const facts = pr.facts || []
  document.getElementById('meds').innerHTML = '<h4>Medicines and key results</h4><p>Read from the record; every value names its source.</p>' +
    (facts.length ? '<div class="results" aria-label="Pertinent results">' + facts.map((f) => '<div class="result' + (f.bad ? ' flag' : '') + '" title="' + esc(f.source) + '"><small>' + esc(f.label) + '</small><strong>' + esc(f.value) + '</strong></div>').join('') + '</div>' : '<div class="empty">No results or flags on the record.</div>') +
    ((pr.prescriptions || []).map((rx) => {
      const ok = rx.status === 'collected'
      const state = rx.status === 'collected' ? 'Collected' + (med && med.state === 'verified' ? ', verified in the pharmacy record' : '') : rx.status === 'dispensed' ? 'Dispensed, not yet collected' : rx.status === 'approved' ? 'Approved, not yet dispensed' : rx.status
      return '<article class="medicine' + (ok ? ' verified' : '') + '"><strong>' + esc(rx.drug) + '</strong><dl><dt>Purpose</dt><dd>Discharge supply</dd><dt>Supply</dt><dd class="med-state">' + esc(state) + '</dd><dt>Dose</dt><dd>Not specified in the simulator</dd></dl></article>'
    }).join('') || '<div class="empty" style="margin-top:14px">No prescription for this patient in the pharmacy record.</div>')
  const it = summaryItem(p)
  const draft = agentDraft(s, p)
  const src = (p.letter && p.letter.sections) || draft
  const sent = it && it.state === 'verified' && !it.draftOnly
  const ds = document.getElementById('draftState')
  ds.textContent = sent ? 'Sent to the GP · verified in the inbox' : it && it.draftOnly && it.state === 'verified' ? 'Draft held (case blocked)' : p.letter ? 'Clinician draft saved · sent when the plan runs' : draft ? 'Agent draft' : 'Not drafted yet'
  ds.className = 'draft-state' + (sent ? ' sent' : '')
  document.getElementById('letterPatient').innerHTML = '<b>' + esc(p.name) + '</b> &nbsp; ' + esc(p.patientId) + (p.location ? ' &nbsp; ' + esc(p.location) : '')
  document.getElementById('letterProv').innerHTML = it && it.generated ? '<b>Provenance:</b> ' + (it.generated === 'model' ? 'sections written by the live model from the record' : it.generated === 'clinician' ? 'sections edited and saved by a clinician in Homeward' : 'canned fallback text (model unavailable), read before relying on it') : (p.letter ? '<b>Provenance:</b> clinician draft saved by ' + esc(p.letter.editedBy) : '')
  document.getElementById('refreshLetter').disabled = !draft
  const json = JSON.stringify(src || null)
  if (!letterDirty && json !== lastLetterJson) {
    lastLetterJson = json
    document.getElementById('letterFields').innerHTML = LETTER_FIELDS.map(([k, label, full]) =>
      '<div class="letter-field' + (full ? ' full' : '') + '"><label for="lf-' + k + '">' + label + '</label><textarea id="lf-' + k + '" data-k="' + k + '" spellcheck="true" placeholder="' + (src ? '' : 'Drafted by the agent once the plan is approved') + '">' + esc(src ? src[k] || '' : '') + '</textarea></div>').join('')
    document.getElementById('saveState').textContent = p.letter ? 'Saved by ' + p.letter.editedBy : 'Not yet saved'
  }
  document.getElementById('saveLetter').disabled = false
}

// --- overlays: the plan, a task, the trace --------------------------------
/** One person's action on a human item: confirm a hold, prepare or show an escalation, or the confirmed state. */
/** The record thread or document behind a human item, as a link that opens it here and comes back. */
const shortTitle = (t) => String(t || '').split(/:|\\u2014/)[0].trim()
function threadLink(i) {
  const e = (i.evidence || []).find((x) => x.site && x.site !== 'patient-directory' && x.resourceId && x.resourceId !== 'directory' && x.resourceId !== 'record-text')
  if (!e) return ''
  return '<a href="#" class="thread" data-act="thread" data-site="' + esc(e.site) + '" data-p="' + esc(i.patientId) + '" data-id="' + esc(e.resourceId) + '">Open the ' + (e.site === 'hospital' ? 'thread' : 'record') + ' ' + esc(e.resourceId) + '</a>'
}
function confirmRow(i) {
      if (i.state === 'clinical_hold') return '<div class="confirm"><span><b>' + esc(i.title) + '</b><small>' + esc(i.humanReason || 'Clinical decision, never automated.') + '</small>' + threadLink(i) + '</span><span class="btns"><button data-act="hold" data-id="' + esc(i.id) + '">Record confirmation</button></span></div>'
      if (i.state === 'verified') return '<div class="confirm done"><span><b>' + esc(i.title) + '</b><small>' + esc(i.verification ? i.verification.observed : 'Confirmed') + '</small>' + threadLink(i) + '</span><span class="btns"><button disabled>Confirmed</button>' + (i.owner === 'clinician' ? '<button class="undo" data-act="undo-hold" data-id="' + esc(i.id) + '" title="Reinstate the hold">Undo</button>' : '') + '</span></div>'
      if (i.escalation) return '<div class="confirm sent"><span><b>' + esc(i.title) + '</b><small>Escalated to ' + esc(i.escalation.responsibleTeam) + ', ' + esc(i.escalation.nextAction) + (i.escalation.source === 'fallback' ? ' (canned note; model unavailable)' : '') + '. Case stays blocked until they decide.</small></span><button disabled>Escalated</button></div>'
      return '<div class="confirm"><span><b>' + esc(i.title) + '</b><small>' + esc(i.humanReason || 'External decision the agent must not make.') + '</small></span><button data-act="escalate" data-id="' + esc(i.id) + '">Prepare escalation</button></div>'
}

/** A gate circle opens whatever that gate needs: the plan to approve, the confirmation to record, the escalation, or the agent's trace. */
function openGate(n) {
  const s = lastState; if (!s) return
  const p = patient(s); if (!p) return
  const g = GATES[n]; if (!g) return
  const items = p.items.filter((i) => g.kinds.includes(kindOf(i)))
  if (items.length === 1) {
    const i = items[0]
    if (i.state === 'proposed') return openOverlay('plan')
    if (!isHuman(i)) return openOverlay('item:' + i.id)
  }
  openOverlay('gate:' + n)
}
const overlayStack = []
function openOverlay(key, push) { if (push && overlayKey) overlayStack.push(overlayKey); else if (!push) overlayStack.length = 0; overlayKey = key; renderOverlay(); document.getElementById('overlay').classList.add('open') }
function closeOverlay() { overlayKey = null; overlayStack.length = 0; document.getElementById('overlay').classList.remove('open') }
function backOverlay() { const prev = overlayStack.pop(); if (prev) { overlayKey = prev; renderOverlay() } else closeOverlay() }
const threadCache = {}
async function loadThread(key) {
  if (threadCache[key]) return
  threadCache[key] = { loading: true }
  const [, site, p, id] = key.split(':')
  try {
    const r = await fetch('/resource?site=' + encodeURIComponent(site) + '&patient=' + encodeURIComponent(p) + '&id=' + encodeURIComponent(id))
    threadCache[key] = r.ok ? { resource: await r.json() } : { error: await r.text() }
  } catch (e) { threadCache[key] = { error: String(e) } }
  if (overlayKey === key) renderOverlay()
}
function renderOverlay() {
  const s = lastState; if (!s) return
  const p = patient(s)
  const T = document.getElementById('ovTitle'), U = document.getElementById('ovSub'), B = document.getElementById('ovBody')
  const row = (i) => '<div class="row"><span class="own">' + esc(OWNER[i.owner] || i.owner) + '</span><b>' + esc(i.title) + '</b></div>'
  if (overlayKey === 'plan') {
    const proposed = p.items.filter((i) => i.state === 'proposed')
    const humans = p.items.filter((i) => isHuman(i) && i.state !== 'verified')
    T.textContent = 'Plan for ' + p.name
    U.textContent = proposed.length + ' proposed action' + (proposed.length === 1 ? '' : 's') + ' · the exact steps the agent will take once you approve, and what it will check afterwards'
    const willLine = (i) => {
      const k = kindOf(i)
      const base = k === 'summary' && i.draftOnly ? 'Draft the discharge letter and hold it' : JOB[k] || i.proposedAction || i.title
      const detail = k === 'summary' && i.draftOnly ? 'draft it and hold it; nothing is sent while the case is blocked'
        : k === 'summary' ? 'draft it from the record, save it, send it to the GP'
        : k === 'follow-up' ? 'create the GP task' + (/telephone/i.test(i.title) ? ' and rebook the visit as a telephone review' : '')
        : k === 'medicines' ? 'reserve stock, dispense and record collection in the pharmacy'
        : k === 'bloods' ? 'order routine U&E and FBC with the result history on the request'
        : k === 'device' ? 'issue a home activity watch and wait for its first reading'
        : k === 'visit' ? 'schedule a community home-support visit'
        : ''
      return '<li><b>' + esc(base) + '</b>' + (detail ? '<span>' + esc(detail) + '</span>' : '') + '<em>' + esc(OWNER[i.owner] || i.owner) + '</em></li>'
    }
    const wontLine = (i) => '<li><b>' + esc(i.title) + '</b><span>' + esc(i.humanReason || (i.state === 'clinical_hold' ? 'Clinical decision, never automated.' : 'External decision the agent must not make.')) + '</span><em>' + esc(OWNER[i.owner] || i.owner) + '</em></li>'
    const summary = '<div class="wontwill">' +
      '<div class="will"><h4>The agent will</h4><ul>' + (proposed.map(willLine).join('') || '<li><b>Nothing</b><span>no actions are proposed</span></li>') + '</ul>' +
        '<p>Then it moves the clock on and re-reads every service to prove each step happened.</p></div>' +
      '<div class="wont"><h4>Not in this plan<small>the agent will not touch these</small></h4><ul>' +
        (humans.map(wontLine).join('') || '<li><b>Nothing held back</b><span>every item for this patient is in the plan</span></li>') +
      '</ul></div></div>' +
      '<h4 class="steps-head">Exact steps, per action</h4>'
    B.innerHTML = summary + proposed.map((i) => '<div class="pi">' + row(i) +
      ((i.evidence || [])[0] ? '<div class="ev"><span class="tag">record</span> \\u201c' + q(i.evidence[0].quote) + '\\u201d <code>' + esc(i.evidence[0].site + ' ' + i.evidence[0].resourceId) + '</code></div>' : '') +
      (i.plan && i.plan.length ? '<ol class="plan">' + i.plan.map((x) => '<li>' + esc(x) + '</li>').join('') + '</ol>' : '<div class="ev">' + esc(i.proposedAction || '') + '</div>') + '</div>').join('') +
      '' +
      (proposed.length ? '<div class="planfoot"><button class="primary" data-act="approve" data-p="' + esc(p.patientId) + '">Approve ' + proposed.length + ' action' + (proposed.length === 1 ? '' : 's') + '</button><span class="sub">Approval starts the agent on these steps only. Time is then advanced and every step is re-checked in the owning service.</span></div>' : '<div class="empty">Nothing is waiting for approval.</div>')
    return
  }
  if (overlayKey.startsWith('thread:')) {
    const [, site, , id] = overlayKey.split(':')
    const c = threadCache[overlayKey] || {}
    loadThread(overlayKey)
    T.textContent = (site === 'hospital' ? 'Thread ' : 'Record ') + id
    U.textContent = 'Read straight from the ' + site + ' record in the simulator'
    const back = '<div class="planfoot"><button class="secondary" data-act="back">Back</button></div>'
    if (c.loading || (!c.resource && !c.error)) { B.innerHTML = '<div class="empty">Reading the record…</div>' + back; return }
    if (c.error) { B.innerHTML = '<div class="empty">Could not read it: ' + esc(c.error) + '</div>' + back; return }
    const r = c.resource, d = r.data || {}
    const when = r.createdAt ? new Date(r.createdAt).toISOString().slice(0, 16).replace('T', ' ') : ''
    const plain = Object.keys(d).filter((k) => !['text', 'messages'].includes(k) && typeof d[k] !== 'object')
    B.innerHTML = '<div class="thread-view"><h4>' + esc(r.title || r.kind || id) + '</h4>' +
      '<p class="meta">' + esc([r.kind, r.status, r.priority, when, r.owner ? 'owner ' + r.owner : ''].filter(Boolean).join(' · ')) + '</p>' +
      (d.text ? '<blockquote>' + esc(d.text) + '</blockquote>' : '') +
      (Array.isArray(d.messages) ? d.messages.map((m) => '<blockquote><b>' + esc(m.from || m.author || '') + '</b> ' + esc(m.text || m.body || '') + '</blockquote>').join('') : '') +
      (plain.length ? '<dl>' + plain.map((k) => '<dt>' + esc(k) + '</dt><dd>' + esc(String(d[k])) + '</dd>').join('') + '</dl>' : '') +
      '</div>' + back
    return
  }
  if (overlayKey.startsWith('gate:')) {
    const g = GATES[Number(overlayKey.slice(5))]
    const items = p.items.filter((i) => g.kinds.includes(kindOf(i)))
    T.textContent = g.label + ': ' + g.sub
    U.textContent = items.length ? items.length + ' item' + (items.length === 1 ? '' : 's') + ' at this gate; act on each below' : 'No barrier found at this gate.'
    B.innerHTML = items.map((i) => {
      if (isHuman(i)) return confirmRow(i)
      if (i.state === 'proposed') return '<div class="confirm"><span><b>' + esc(jobTitle(i)) + '</b><small>' + esc(shortState(i)) + '</small></span><button data-act="plan">Review plan</button></div>'
      return '<div class="confirm' + (i.state === 'verified' ? ' done' : '') + '"><span><b>' + esc(jobTitle(i)) + '</b><small>' + esc(shortState(i)) + '</small></span><button data-act="item" data-id="' + esc(i.id) + '">' + (i.state === 'failed' ? 'See the error' : 'See what the agent did') + '</button></div>'
    }).join('') || '<div class="empty">Nothing to do here.</div>'
    return
  }
  if (overlayKey === 'trace') {
    const all = s.trace || []
    T.textContent = 'What the agent did'
    U.textContent = all.length + ' simulator calls · each line says what the agent did and what the service replied; the wire detail is behind Show request'
    const claimed = new Set()
    const parts = []
    for (const p0 of s.patients) {
      const items = p0.items.map((i) => ({ i, rows: callsFor(s, i).map((t) => { claimed.add(t); return t }) })).filter((x) => x.rows.length)
      if (items.length) parts.push('<div class="grp"><h4>' + esc(p0.name) + '<span>' + esc(p0.patientId) + '</span></h4>' + items.map((x) => '<div class="pi">' + row(x.i) + x.rows.map(wireRow).join('') + '</div>').join('') + '</div>')
    }
    const rest = all.filter((t) => !claimed.has(t) && t.method !== 'GET')
    if (rest.length) parts.push('<div class="grp"><h4>Run &amp; world<span>setup, clock, un-attributed writes</span></h4>' + rest.map(wireRow).join('') + '</div>')
    const reads = all.filter((t) => !claimed.has(t) && t.method === 'GET').length
    if (reads) parts.push('<div class="empty">' + reads + ' record reads not shown.</div>')
    B.innerHTML = parts.join('') || '<div class="empty">No calls yet.</div>'
    return
  }
  if (overlayKey && overlayKey.indexOf('item:') === 0) {
    const i = p.items.find((x) => x.id === overlayKey.slice(5)); if (!i) return
    const kv = (k, v) => '<div class="kv"><span class="k">' + k + '</span><span class="v">' + v + '</span></div>'
    T.textContent = jobTitle(i)
    U.textContent = p.name + ' · ' + (OWNER[i.owner] || i.owner) + ' · ' + shortState(i)
    const calls = callsFor(s, i)
    B.innerHTML = '<div class="grp"><h4>Detected from the record</h4>' + ((i.evidence || []).map((e) => kv('<span class="tag">record</span>', '\\u201c' + q(e.quote) + '\\u201d <code>' + esc(e.site + ' ' + e.resourceId) + '</code>')).join('') || '<div class="empty">Rule-detected from structured state.</div>') + '</div>' +
      '<div class="grp"><h4>Plan</h4>' + (i.proposedAction ? kv('Intent', esc(i.proposedAction)) : '') +
      (isHuman(i) ? kv('Needs a human', esc(i.humanReason || '')) : kv('Approval', i.approval ? 'Approved by ' + esc(i.approval.by) : 'Not yet, awaiting staff approval')) +
      (i.plan && i.plan.length ? kv('Steps', '<ol class="plan" style="margin:0">' + i.plan.map((x) => '<li>' + esc(x) + '</li>').join('') + '</ol>') : '') +
      (i.error ? kv('<span class="err">Failed</span>', '<span class="err">' + esc(i.error) + '</span>' + (simOutage(i) ? ', simulator outage, not a record problem' : '')) : '') + '</div>' +
      '<div class="grp"><h4>Agent \\u2194 ' + esc(OWNER[i.owner] || i.owner) + '<span>' + calls.length + ' calls, oldest first · times are real clock</span></h4>' + (calls.map(wireRow).join('') || '<div class="empty">No actions sent yet.</div>') + '</div>' +
      (i.generated ? '<div class="grp"><h4>Drafting provenance</h4>' + kv(i.generated === 'model' ? '<span class="tag ai">AI</span>' : i.generated === 'clinician' ? '<span class="tag">human</span>' : '<span class="err">⚠</span>', i.generated === 'model' ? 'The live model wrote the drafted content' : i.generated === 'clinician' ? 'A clinician edited and saved the content in Homeward' : 'Canned fallback used, model unavailable') + '</div>' : '') +
      (i.verification ? '<div class="grp"><h4>Independent verification</h4>' + kv(i.owner === 'clinician' ? '<span class="tag">human</span>' : '<span class="tag sim">sim</span>', (i.verification.passed ? '<b style="color:var(--nhs-green)">✓ passed</b>, ' : '<span class="err">✗ not yet</span>, ') + esc(i.verification.observed) + ' <span style="color:var(--muted)">(sim clock ' + esc(new Date(i.verification.atSimTime).toISOString().slice(0, 16).replace('T', ' ')) + ')</span>') + (CAVEAT[kindOf(i)] ? kv('Does not prove', esc(CAVEAT[kindOf(i)])) : '') + '</div>' : '') +
      (i.escalation ? '<div class="grp"><h4>Escalation</h4>' + kv(i.escalation.source === 'fallback' ? '<span class="err">⚠ canned</span>' : '<span class="tag ai">AI</span>', '<b>' + esc(i.escalation.responsibleTeam) + '</b>, ' + esc(i.escalation.nextAction)) + kv('Note', esc(i.escalation.note)) + '</div>' : '')
  }
}

// --- actions ----------------------------------------------------------------
const post = async (path) => { await fetch(path, { method: 'POST' }); await tick(true) }
document.addEventListener('click', async (e) => {
  const el = e.target.closest('[data-act]'); if (!el) return
  const act = el.dataset.act
  if (act === 'select') { selectedPatient = el.dataset.p; letterDirty = false; lastLetterJson = ''; if (lastState) render(lastState) }
  else if (act === 'main') { if (el.dataset.kind === 'plan') openOverlay('plan') }
  else if (act === 'trace') openOverlay('trace')
  else if (act === 'plan') openOverlay('plan')
  else if (act === 'gate') openGate(Number(el.dataset.n))
  else if (act === 'item') openOverlay('item:' + el.dataset.id)
  else if (act === 'close') closeOverlay()
  else if (act === 'approve') { closeOverlay(); await post('/approve?patient=' + encodeURIComponent(el.dataset.p)) }
  else if (act === 'hold') { el.disabled = true; await post('/clear-hold?item=' + encodeURIComponent(el.dataset.id)) }
  else if (act === 'undo-hold') { el.disabled = true; await post('/undo-hold?item=' + encodeURIComponent(el.dataset.id)) }
  else if (act === 'thread') { e.preventDefault(); openOverlay('thread:' + el.dataset.site + ':' + el.dataset.p + ':' + el.dataset.id, true) }
  else if (act === 'back') backOverlay()
  else if (act === 'escalate') { el.textContent = 'Drafting…'; el.disabled = true; await post('/escalate?item=' + encodeURIComponent(el.dataset.id)) }
  else if (act === 'refresh') { const d = lastState && agentDraft(lastState, patient(lastState)); if (d) { for (const [k] of LETTER_FIELDS) { const t = document.getElementById('lf-' + k); if (t) t.value = d[k] || '' } letterDirty = true; document.getElementById('saveState').textContent = 'Reset to the agent\\u2019s draft, not saved' } }
  else if (act === 'save') {
    const sections = {}; for (const [k] of LETTER_FIELDS) { const t = document.getElementById('lf-' + k); sections[k] = t ? t.value : '' }
    const p = patient(lastState)
    const res = await fetch('/letter?patient=' + encodeURIComponent(p.patientId), { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ sections }) })
    const it = summaryItem(p)
    document.getElementById('saveState').textContent = res.ok ? (it && it.state === 'verified' && !it.draftOnly ? 'Saved as an amendment; re-sending is not automated' : 'Saved, the agent sends these sections') : 'Save failed'
    letterDirty = false; lastLetterJson = ''
    await tick(true)
  }
})
document.getElementById('overlay').addEventListener('click', (e) => { if (e.target === e.currentTarget) closeOverlay() })
document.addEventListener('keydown', (e) => { if (e.key === 'Escape' && overlayKey) closeOverlay() })
document.getElementById('letterFields').addEventListener('input', () => { letterDirty = true; document.getElementById('saveState').textContent = 'Unsaved changes' })
document.getElementById('find').addEventListener('input', (e) => { patFilter = e.target.value; if (lastState) render(lastState) })

async function tick(force) {
  try {
    const text = await (await fetch('/state')).text()
    if (!force && text === lastText) return
    lastText = text
    render(JSON.parse(text))
  } catch {
    if (!booted) renderBoot(null)
  }
}
setInterval(tick, 1500); tick()
</script></body></html>`

export function startUi(board: BoardState, port = 4600, getSim?: () => SimClient | undefined): Server {
  const server = createServer((req, res) => {
    const url = new URL(req.url ?? '/', 'http://localhost')
    if (url.pathname === '/state') {
      res.setHeader('content-type', 'application/json')
      let story: unknown = null
      try { story = computeStory(board) } catch (err) { console.error(`story: ${String((err as Error).message)}`) }
      res.end(JSON.stringify({ ...board, story }))
    } else if (url.pathname === '/undo-hold' && req.method === 'POST') {
      const ok = undoHold(board, url.searchParams.get('item') ?? '', 'Demo clinician')
      res.statusCode = ok ? 200 : 409
      res.end(ok ? 'reinstated' : 'cannot undo')
    } else if (url.pathname === '/resource') {
      const sim = getSim?.()
      const site = url.searchParams.get('site') ?? '', patient = url.searchParams.get('patient') ?? '', id = url.searchParams.get('id') ?? ''
      if (!sim) { res.statusCode = 503; res.end('simulator not connected (fallback mode)'); return }
      sim.siteView(site as any, { patient, limit: 300 }).then((view) => {
        const r = ((view.resources ?? []) as any[]).find((x) => x.id === id)
        if (!r) { res.statusCode = 404; res.end('not in the ' + site + ' record'); return }
        res.setHeader('content-type', 'application/json')
        res.end(JSON.stringify(r))
      }).catch((err) => { res.statusCode = 502; res.end(String((err as Error).message).slice(0, 200)) })
    } else if (url.pathname === '/clear-hold' && req.method === 'POST') {
      const ok = clearHold(board, url.searchParams.get('item') ?? '', 'Demo clinician')
      res.statusCode = ok ? 200 : 404
      res.end(ok ? 'cleared' : 'not found')
    } else if (url.pathname === '/approve' && req.method === 'POST') {
      const n = approveAll(board, 'Demo coordinator', url.searchParams.get('patient') || undefined)
      res.end(String(n))
    } else if (url.pathname === '/receipt') {
      const md = buildReceipt(board, url.searchParams.get('patient') ?? '')
      if (!md) { res.statusCode = 404; res.end('unknown patient'); return }
      res.setHeader('content-type', 'text/markdown; charset=utf-8')
      res.setHeader('content-disposition', `attachment; filename="homeward-receipt-${url.searchParams.get('patient')}.md"`)
      res.end(md)
    } else if (url.pathname === '/letter' && req.method === 'POST') {
      let body = ''
      req.on('data', (c) => { body += c })
      req.on('end', () => {
        let sections: Record<string, unknown> = {}
        try { sections = (JSON.parse(body || '{}') as { sections?: Record<string, unknown> }).sections ?? {} } catch { /* empty draft */ }
        const ok = saveLetter(board, url.searchParams.get('patient') ?? '', sections, 'Demo clinician')
        res.statusCode = ok ? 200 : 404
        res.end(ok ? 'saved' : 'not found')
      })
    } else if (url.pathname === '/escalate' && req.method === 'POST') {
      prepareEscalation(board, url.searchParams.get('item') ?? '').then((ok) => {
        res.statusCode = ok ? 200 : 404
        res.end(ok ? 'escalated' : 'not found')
      })
    } else {
      res.setHeader('content-type', 'text/html')
      res.end(PAGE)
    }
  })
  server.on('error', (err: NodeJS.ErrnoException) => {
    if (err.code === 'EADDRINUSE') {
      console.error(`port ${port} is busy (an older run?), retrying every 2s; this run's UI will take over as soon as it frees up`)
      setTimeout(() => server.listen(port, '127.0.0.1'), 2000)
    } else throw err
  })
  server.listen(port, '127.0.0.1', () => console.log(`ward list: http://localhost:${(server.address() as AddressInfo).port} (localhost only)`))
  return server
}
