/**
 * Homeward ward-list UI, Mercury-style: light surfaces, Inter variable font
 * with measured weights (420/480/530), cobalt actions, sidebar, KPI tiles
 * with a live sparkline, collapsible patient cards, a patient-centred barrier
 * graph, an Accounts-style Services rail,
 * and the activity log.
 *
 * The rail opens with the story panel: the same ward twice — an illustrative
 * manual-working model (src/story/baseline.ts) beside the live agent world —
 * with bed-hours-saved counters and a replay scrubber.
 *
 * Polls /state every 2s. Buttons: "Approve plan" (header, staff approval of
 * all proposed items), "Confirm reviewed" (clinical hold sign-off),
 * "Prepare escalation" (blocked_human handover). Each KPI tile opens a modal
 * over a blurred backdrop listing the items behind that number with what the
 * agent planned, did, verified, and the evidence it quoted. No dependencies — Node http
 * + one page. Inter loads from Google Fonts; falls back to system-ui offline.
 *
 * Colors follow the dataviz skill's fixed status palette (icon + label,
 * never color alone); text stays in ink tokens, the dot carries the color.
 */
import { createServer } from 'node:http'
import type { BoardState, ChecklistItem, PatientRow } from '../orchestrator/model.ts'
import { approveAll, clearHold, prepareEscalation } from '../orchestrator/run.ts'
import { computeStory } from '../story/story.ts'

/** What each verified item does NOT prove — epistemic honesty, per item kind. */
const CAVEATS: Record<string, string> = {
  medicines: 'Collection is recorded; this does not prove adherence or ongoing supply.',
  bloods: 'Results are available; this does not constitute clinical review of those results.',
  device: 'A reading was received; this does not confirm sustained monitoring or clinical review of readings.',
  visit: 'The visit is completed; this does not confirm ongoing care-package funding or future visits.',
  summary: 'The letter reached the GP inbox; this does not confirm the GP has read or actioned it.',
  'follow-up': 'The task exists on the GP worklist; this does not confirm the review has happened.',
  'clinical-hold': 'Clinician sign-off is a human decision recorded here, not an automated judgement.',
  'care-package': 'Escalated to a human decision; nothing here resolves the funding question.',
}
const caveatFor = (id: string): string | undefined =>
  Object.entries(CAVEATS).find(([k]) => id.endsWith('-' + k))?.[1]

const mdWhen = (ms?: number) => (ms ? new Date(ms).toISOString().replace('T', ' ').slice(0, 16) + ' (sim)' : '—')

/** Consolidated per-patient discharge coordination record, as Markdown. */
export function buildReceipt(board: BoardState, patientId: string): string | undefined {
  const p = board.patients.find((x) => x.patientId === patientId)
  if (!p) return undefined
  const verified = p.items.filter((i) => i.state === 'verified').length
  const blockers = p.items.filter((i) => i.state === 'clinical_hold' || i.state === 'blocked_human')
  const open = p.items.filter((i) => !['verified', 'clinical_hold', 'blocked_human'].includes(i.state))
  const L: string[] = []
  L.push(`# Discharge coordination record — ${p.name} (${p.patientId})`)
  L.push('')
  L.push(`Generated by Homeward · world \`${board.world}\` · sim clock ${mdWhen(board.simNow)} · real time ${new Date().toISOString().slice(0, 16).replace('T', ' ')} UTC`)
  L.push('')
  L.push('## Verdict')
  L.push('')
  const ready = p.items.length > 0 && p.items.every((i) => i.state === 'verified')
  L.push(ready
    ? `**Operationally ready.** All ${p.items.length} checklist items independently verified. Final discharge remains a clinical decision.`
    : `**Not yet confirmed.** ${verified} of ${p.items.length} items verified.` +
      (blockers.length ? ` Outstanding human decisions: ${blockers.map((b) => b.title).join('; ')}.` : '') +
      (open.length ? ` Still in progress: ${open.map((o) => o.title).join('; ')}.` : ''))
  L.push('')
  L.push(`Patient context: ${p.conditions.join(', ') || '—'} · stage ${p.stage ?? '—'}${p.location ? ' · ' + p.location : ''}. Recorded needs: ${p.needs.join(', ') || '—'}. Goals: ${p.goals.join(', ') || '—'}.`)
  p.items.forEach((i, n) => {
    L.push('')
    L.push(`## ${n + 1}. ${i.title}`)
    L.push('')
    L.push(`**State:** ${i.state.replace('_', ' ')} · **Owner:** ${i.owner}`)
    if (i.evidence.length) {
      L.push('')
      L.push('**Detected from the record:**')
      for (const e of i.evidence) L.push(`- "${e.quote}" — \`${e.site} ${e.resourceId}\``)
    }
    if (i.proposedAction) { L.push(''); L.push(`**Plan:** ${i.proposedAction}`) }
    if (i.approval) L.push(`**Approved by:** ${i.approval.by} at ${mdWhen(i.approval.at)}`)
    if (i.humanReason) { L.push(''); L.push(`**Why a human is required:** ${i.humanReason}`) }
    const wire = (board.trace ?? []).filter((t) => t.idempotencyKey && t.idempotencyKey.includes(i.id))
    if (wire.length) {
      L.push('')
      L.push('**Actions executed (wire record):**')
      L.push('')
      L.push('| Time | Action | Sent to | Result |')
      L.push('| --- | --- | --- | --- |')
      for (const t of wire) {
        L.push(`| ${new Date(t.at).toTimeString().slice(0, 8)} | \`${t.action ?? t.method}\` | \`${t.path.split('?')[0]}\` | ${t.ok ? `HTTP ${t.status}` : `FAILED ${t.status || ''}`}${t.got ? ` → ${t.got}` : ''} |`)
      }
    }
    if (i.resolution) L.push(`
Idempotency key: \`${i.resolution.idempotencyKey}\``)
    if (i.generated) { L.push(''); L.push(`**Drafting provenance:** ${i.generated === 'model' ? 'content written by the live model' : 'canned fallback (model unavailable)'}`) }
    if (i.verification) {
      L.push('')
      L.push(`**Independent verification:** ${i.verification.passed ? 'PASSED' : 'NOT YET'} — ${i.verification.observed} at ${mdWhen(i.verification.atSimTime)}`)
    }
    if (i.escalation) {
      L.push('')
      L.push(`**Escalated to:** ${i.escalation.responsibleTeam} — ${i.escalation.nextAction}`)
      L.push(`> ${i.escalation.note}`)
    }
    const cav = caveatFor(i.id)
    if (cav && ['verified', 'clinical_hold', 'blocked_human'].includes(i.state)) {
      L.push(''); L.push(`**This does not prove:** ${cav}`)
    }
  })
  L.push('')
  L.push('---')
  L.push('')
  L.push('Synthetic simulator data (NHS-SIM). Every action above was executed against the simulator and independently re-read; RECORD quotes are verbatim from the record. Final discharge decisions rest with the responsible clinician.')
  L.push('')
  return L.join('\n')
}

export const PAGE = `<!doctype html>
<html lang="en"><head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Homeward</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400..700&display=swap" rel="stylesheet">
<style>
  :root{
    --page:#f9f9f7; --surface:#ffffff; --ink:#0b0b0b; --ink-2:#52514e; --ink-3:#898781;
    --hairline:rgba(11,11,11,0.10); --grid:#e1e0d9;
    --accent:#5266eb; --accent-soft:rgba(82,102,235,0.08);
    --good:#0ca30c; --warning:#fab219; --serious:#ec835a; --critical:#d03b3b;
    --radius:12px;
  }
  *{box-sizing:border-box;margin:0}
  body{font-family:Inter,system-ui,-apple-system,"Segoe UI",sans-serif;background:var(--page);color:var(--ink);
       font-size:14px;line-height:1.45;-webkit-font-smoothing:antialiased}
  a{color:inherit;text-decoration:none}

  .app{display:grid;grid-template-columns:224px 1fr;min-height:100vh}
  .sidebar{background:var(--surface);border-right:1px solid var(--hairline);padding:20px 14px;
           display:flex;flex-direction:column;gap:2px;position:sticky;top:0;height:100vh}
  .brand{display:flex;align-items:center;gap:10px;padding:4px 8px 18px}
  .brand .mark{width:30px;height:30px;border-radius:8px;background:linear-gradient(135deg,#5266eb,#7a8cf0);
               display:grid;place-items:center;color:#fff;font-weight:530;font-size:13px}
  .brand .name{font-weight:480;font-size:14px}
  .brand .sub{font-size:11px;color:var(--ink-3)}
  .nav-item{display:flex;align-items:center;gap:10px;padding:8px 10px;border-radius:8px;color:var(--ink-2);
            font-weight:420;cursor:pointer}
  .nav-item.active{background:var(--accent-soft);color:var(--accent);font-weight:480}
  .nav-item:hover:not(.active){background:#f4f4f1}
  .sidebar .foot{margin-top:auto;padding:10px;font-size:12px;color:var(--ink-3);border-top:1px solid var(--grid)}
  .sidebar .foot b{color:var(--ink-2);font-weight:480}

  .main{padding:28px 36px;max-width:1220px}
  .header{display:flex;align-items:flex-end;justify-content:space-between;gap:16px}
  h1{font-size:22px;font-weight:480;letter-spacing:0.01em}
  .subtitle{color:var(--ink-3);font-size:13px;margin-top:2px}
  button.primary{font:inherit;font-size:13px;font-weight:480;color:#fff;background:var(--accent);
                 border:none;border-radius:999px;padding:9px 20px;cursor:pointer;white-space:nowrap}
  button.primary:hover{filter:brightness(1.06)}
  button.ghost{font:inherit;font-size:12px;font-weight:480;color:var(--ink-2);background:var(--surface);
               border:1px solid var(--hairline);border-radius:999px;padding:8px 16px;cursor:pointer;white-space:nowrap}
  button.ghost:hover{background:#f4f4f1}
  .wire{font-family:ui-monospace,SFMono-Regular,monospace;font-size:11px;display:flex;gap:8px;align-items:baseline;
        padding:5px 0;border-top:1px solid var(--grid);color:var(--ink-2)}
  .wire .m{min-width:38px;font-weight:600}
  .wire .m.post{color:var(--accent)}
  .wire .bad{color:var(--critical)}
  .wire .k{color:var(--ink-3)}
  .wire code{background:#f4f4f1;border-radius:4px;padding:0 4px}
  .kv{display:grid;grid-template-columns:96px 1fr;gap:0 14px;padding:8px 0;border-top:1px solid var(--grid);align-items:baseline}
  .kv:first-of-type{border-top:none}
  .kv .k{font-size:12px;color:var(--ink-3);font-weight:420}
  .kv .v{font-size:13px;color:var(--ink);line-height:1.5}
  .kv .v code{font-family:ui-monospace,monospace;font-size:11px;background:#f4f4f1;border-radius:4px;padding:1px 5px}
  .call{border:1px solid var(--grid);border-radius:8px;padding:10px 14px;margin-top:8px}
  .call .head{display:flex;gap:10px;align-items:baseline;font-size:12px;flex-wrap:wrap}
  .call .head .t{color:var(--ink-3);font-variant-numeric:tabular-nums}
  .call .head .m{font-weight:600;color:var(--accent)}
  .call .head .m.get{color:var(--ink-3)}
  .call .head .a{font-weight:480}
  .call .head .ok{color:var(--good);font-weight:480}
  .call .head .fail{color:var(--critical);font-weight:480}
  .call pre{background:#f6f6f4;border-radius:6px;padding:8px 10px;font-size:11px;line-height:1.5;
            white-space:pre-wrap;word-break:break-all;margin:8px 0 0;font-family:ui-monospace,monospace;color:var(--ink-2)}
  .call .meta{font-size:11px;color:var(--ink-3);margin-top:6px;word-break:break-all}

  .kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin:22px 0}
  .kpi{background:var(--surface);border:1px solid var(--hairline);border-radius:var(--radius);padding:14px 16px;
       position:relative;overflow:hidden}
  .kpi .label{font-size:12px;color:var(--ink-3);font-weight:420}
  .kpi .value{font-size:26px;font-weight:530;letter-spacing:-0.01em;margin-top:2px}
  .kpi .hint{font-size:11px;color:var(--ink-3)}
  .kpi.has-spark{padding-bottom:40px}
  .kpi{cursor:pointer;transition:border-color .12s,box-shadow .12s}
  .kpi:hover,.kpi:focus-visible{border-color:var(--accent);box-shadow:0 0 0 3px var(--accent-soft);outline:none}
  .kpi .more{position:absolute;top:12px;right:14px;font-size:11px;color:var(--ink-3)}

  .modal-backdrop{position:fixed;inset:0;z-index:50;display:none;place-items:center;padding:24px;
                  background:rgba(11,11,11,0.28);backdrop-filter:blur(6px);-webkit-backdrop-filter:blur(6px)}
  .modal-backdrop.open{display:grid}
  .modal{background:var(--surface);border:1px solid var(--hairline);border-radius:14px;width:min(760px,100%);
         max-height:84vh;overflow:auto;padding:20px 24px 24px;box-shadow:0 20px 60px rgba(11,11,11,0.18)}
  .modal-head{display:flex;align-items:center;gap:12px;margin-bottom:4px}
  .modal-head h2{font-size:17px;font-weight:480}
  .modal-head .sub{color:var(--ink-3);font-size:12px;margin-top:2px}
  .modal-head button{margin-left:auto}
  .modal .group{margin-top:16px}
  .modal .group h3{font-size:13px;font-weight:480;display:flex;gap:8px;align-items:baseline}
  .modal .group h3 span{color:var(--ink-3);font-size:11px;font-weight:420}
  .mi{padding:10px 0;border-top:1px solid var(--grid)}
  .mi .row{display:flex;align-items:baseline;gap:10px}
  .mi .detail{margin:6px 0 0 0;padding-left:8px;border-left:2px solid var(--grid);font-size:12px;color:var(--ink-2)}
  .mi .detail>div{margin-top:3px}
  .mi .detail b{font-weight:480;color:var(--ink)}
  .mi .detail code{font:inherit;font-size:11px;color:var(--ink-3)}
  .mi .trace{color:var(--ink-3);font-variant-numeric:tabular-nums}
  .modal .empty{color:var(--ink-3);font-size:13px;padding:18px 0}
  .kpi svg{position:absolute;left:0;right:0;bottom:0;width:100%;height:28px;display:block}

  .content{display:grid;grid-template-columns:1fr 340px;gap:14px;align-items:start}
  .card{background:var(--surface);border:1px solid var(--hairline);border-radius:var(--radius);
        padding:18px 20px;margin-bottom:14px;box-shadow:0 1px 2px rgba(11,11,11,0.03)}
  .rail .card{padding:16px 18px}
  .rail h2,.log-card h2{font-size:13px;font-weight:480;margin-bottom:6px}

  .patient-card{padding:0;overflow:hidden;transition:border-color .16s}
  .patient-card.expanded{border-color:rgba(11,11,11,0.16)}
  .patient-head{display:flex;align-items:center;gap:12px;flex-wrap:wrap;width:100%;padding:16px 18px;
                border:0;background:transparent;color:inherit;text-align:left;font:inherit;cursor:pointer}
  .patient-head:hover{background:#fbfbf9}
  .patient-head:focus-visible{outline:2px solid var(--accent);outline-offset:-2px}
  .avatar{width:34px;height:34px;border-radius:50%;background:rgba(82,102,235,0.10);color:var(--accent);
          display:grid;place-items:center;font-weight:480;font-size:13px;flex:none}
  .patient-name{font-weight:480;font-size:15px}
  .patient-meta{color:var(--ink-3);font-size:12px}
  .ready-pill{margin-left:auto;display:flex;align-items:center;gap:10px}
  .ready-pill .count{font-size:12px;color:var(--ink-2);font-weight:420;white-space:nowrap}
  .bar{width:110px;height:6px;border-radius:3px;background:var(--grid);overflow:hidden}
  .bar>i{display:block;height:100%;background:var(--good);border-radius:3px}
  .chevron{width:20px;height:20px;display:grid;place-items:center;color:var(--ink-3);font-size:14px;line-height:1;
           transition:transform .16s,color .16s;flex:none}
  .patient-card.expanded .chevron{transform:rotate(180deg);color:var(--ink)}

  .items{margin-top:12px}
  .item{display:flex;align-items:baseline;gap:10px;padding:9px 0;border-top:1px solid var(--grid);cursor:pointer}
  .item:hover{background:#fbfbf9}
  .tag{font-size:9px;font-weight:600;letter-spacing:.05em;text-transform:uppercase;border-radius:4px;
       padding:1px 5px;vertical-align:1px;white-space:nowrap}
  .tag.rec{background:#efeeea;color:#5c5a55}
  .tag.ai{background:var(--accent-soft);color:var(--accent)}
  .tag.sim{background:rgba(12,163,12,0.10);color:#0a7a0a}
  .legend{display:flex;gap:10px;align-items:center;font-size:11px;color:var(--ink-2);margin-left:auto;flex-wrap:wrap}
  .legend span{display:inline-flex;gap:5px;align-items:center}
  .chip{display:inline-flex;align-items:center;gap:6px;padding:2px 9px;border-radius:999px;
        font-size:11px;font-weight:480;color:var(--ink-2);background:#f4f4f1;flex:none;min-width:92px;justify-content:center}
  .chip .dot{width:7px;height:7px;border-radius:50%;flex:none}
  .owner{font-size:11px;color:var(--ink-3);min-width:76px;font-weight:420}
  .item .title{font-weight:420}
  .evidence{color:var(--ink);font-size:12px;font-style:normal}
  .err{color:var(--critical);font-size:12px}
  .item .right{margin-left:auto;flex:none}
  button.confirm{font:inherit;font-size:12px;font-weight:480;color:var(--accent);background:var(--surface);
                 border:1px solid var(--accent);border-radius:999px;padding:4px 14px;cursor:pointer}
  button.confirm:hover{background:var(--accent-soft)}
  .escalation{margin-top:6px;padding:8px 10px;border:1px solid var(--hairline);border-left:3px solid var(--accent);
              border-radius:6px;font-size:12px;color:var(--ink-2);background:var(--accent-soft)}

  .graph-wrap{border-top:1px solid var(--grid);padding:16px 18px 18px;background:var(--surface)}
  .graph-toolbar{display:flex;align-items:center;justify-content:space-between;gap:14px;margin-bottom:8px}
  .graph-title{font-size:12px;font-weight:480;color:var(--ink-2)}
  .legend{display:flex;align-items:center;gap:12px;flex-wrap:wrap;color:var(--ink-3);font-size:10px}
  .legend span{display:inline-flex;align-items:center;gap:5px;white-space:nowrap}
  .legend i{width:7px;height:7px;border-radius:50%;display:block}
  .dependency-graph{height:430px;position:relative;isolation:isolate;overflow:hidden}
  .dependency-lines{position:absolute;inset:0;width:100%;height:100%;z-index:0;overflow:visible}
  .dependency-lines line{stroke-width:1;vector-effect:non-scaling-stroke;opacity:.26}
  .graph-hub{position:absolute;left:50%;top:50%;transform:translate(-50%,-50%);z-index:2;width:58px;height:58px;
             border-radius:50%;background:var(--surface);border:1px solid rgba(82,102,235,.52);display:grid;place-items:center}
  .graph-hub .person{position:relative;width:11px;height:11px;border:1.5px solid var(--accent);border-radius:50%;margin-top:-9px}
  .graph-hub .person:after{content:"";position:absolute;width:23px;height:12px;left:-7.5px;top:15px;border:1.5px solid var(--accent);
                           border-bottom:0;border-radius:14px 14px 0 0}
  .graph-node{--node-color:var(--ink-3);position:absolute;transform:translate(-50%,-50%);z-index:2;width:166px;min-height:62px;
              border:1px solid var(--hairline);border-left:3px solid var(--node-color);border-radius:10px;background:var(--surface);
              padding:10px 12px;cursor:pointer;text-align:left;transition:background .12s,border-color .12s}
  .graph-node:hover,.graph-node:focus-visible{background:#fafaf8;border-color:rgba(11,11,11,.20);border-left-color:var(--node-color);outline:none}
  .graph-node .node-top{display:flex;align-items:center;justify-content:space-between;gap:7px;margin-bottom:5px}
  .graph-node .node-owner{font-size:9px;font-weight:600;letter-spacing:.055em;text-transform:uppercase;color:var(--ink-3)}
  .graph-node .node-title{font-size:12px;line-height:1.3;font-weight:480}
  .graph-node .node-action{margin-top:7px;font:inherit;font-size:10px;font-weight:530;color:var(--accent);background:transparent;
                           border:0;padding:0;cursor:pointer}
  .graph-node.not-started{--node-color:#a5a39c}
  .graph-node.in-progress{--node-color:var(--warning)}
  .graph-node.stuck{--node-color:var(--critical)}
  .graph-node.completed{--node-color:var(--good)}
  .graph-insights{border-top:1px solid var(--grid);margin-top:6px;padding-top:10px;font-size:11px;color:var(--ink-2)}
  .graph-insights b{font-weight:480;color:var(--ink)}

  .story h2{display:flex;align-items:baseline;gap:8px}
  .story h2 .t{margin-left:auto;font-size:11px;color:var(--ink-3);font-weight:420;font-variant-numeric:tabular-nums;white-space:nowrap}
  .story h2 .t.proj{color:var(--accent)}
  .counters{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin:10px 0 12px}
  .counter{background:#f6f6f4;border-radius:8px;padding:8px 10px;min-width:0}
  .counter .v{font-size:20px;font-weight:530;letter-spacing:-0.01em;line-height:1.1;font-variant-numeric:tabular-nums}
  .counter .v small{font-size:11px;font-weight:420;color:var(--ink-3)}
  .counter .l{font-size:10px;color:var(--ink-3);margin-top:2px;line-height:1.25}
  .lane{padding:10px 0 2px;border-top:1px solid var(--grid)}
  .lane-head{display:flex;align-items:baseline;gap:8px;font-size:12px;font-weight:480}
  .lane-head .note{font-size:10px;color:var(--ink-3);font-weight:420}
  .lane-head .n{margin-left:auto;font-size:11px;color:var(--ink-3);font-weight:420;font-variant-numeric:tabular-nums;white-space:nowrap}
  .track{position:relative;height:66px;margin:6px 30px 0}
  .track:before{content:"";position:absolute;left:0;right:0;top:50%;border-top:1px dashed var(--grid)}
  .track .end{position:absolute;top:50%;transform:translate(-50%,-50%);width:24px;height:24px;border-radius:6px;
              background:#f4f4f1;color:var(--ink-3);display:grid;place-items:center}
  .track .end svg{width:15px;height:15px;fill:none;stroke:currentColor;stroke-width:1.6;stroke-linecap:round;stroke-linejoin:round}
  .track .end.bed{left:-26px}
  .track .end.home{left:calc(100% + 26px)}
  .track .end.home.lit{background:rgba(12,163,12,0.12);color:#0a7a0a}
  .av{position:absolute;top:50%;width:30px;height:30px;transform:translate(-50%,-50%);cursor:default;
      transition:left .6s cubic-bezier(.2,.7,.2,1),margin-top .6s}
  .av svg{position:absolute;inset:0;width:30px;height:30px;transform:rotate(-90deg)}
  .av svg circle{fill:none;stroke-width:2.5}
  .av .ring-bg{stroke:var(--grid)}
  .av .ring{stroke:var(--warning);transition:stroke-dashoffset .6s}
  .av.idle .ring{stroke:#a5a39c}
  .av.home .ring{stroke:var(--good)}
  .av.blocked .ring{stroke:var(--critical)}
  .av .ini{position:absolute;inset:5px;border-radius:50%;background:var(--surface);display:grid;place-items:center;
           font-size:9px;font-weight:530;color:var(--accent);letter-spacing:.02em}
  .av.home .ini{color:#0a7a0a}
  .av.blocked .ini{color:var(--critical)}
  .av.flash .ini{animation:pulse .8s ease-out}
  @keyframes pulse{0%{box-shadow:0 0 0 0 rgba(12,163,12,.5)}100%{box-shadow:0 0 0 14px rgba(12,163,12,0)}}
  .story-foot{display:flex;align-items:center;gap:8px;margin-top:8px;padding-top:10px;border-top:1px solid var(--grid)}
  .story-foot input[type=range]{flex:1;min-width:0;accent-color:var(--accent)}
  .story-foot .tl{font-size:11px;color:var(--ink-3);font-variant-numeric:tabular-nums;white-space:nowrap;min-width:52px;text-align:right}
  .story-foot button.ghost{padding:5px 12px;font-size:11px}
  .story .disclaimer{font-size:10.5px;color:var(--ink-3);margin-top:8px;line-height:1.45}
  .story .disclaimer b{font-weight:480;color:var(--ink-2)}
  .story .disclaimer a{color:var(--accent);cursor:pointer}

  @media(max-width:900px){
    .app{grid-template-columns:1fr}.sidebar{display:none}.main{padding:22px 18px}.content{grid-template-columns:1fr}.rail{display:none}
    .kpis{grid-template-columns:repeat(2,1fr)}.dependency-graph{height:auto;display:grid;grid-template-columns:1fr 1fr;gap:8px;padding-top:104px}
    .dependency-lines{display:none}.graph-hub{top:18px;transform:translateX(-50%)}
    .graph-node{position:relative!important;left:auto!important;top:auto!important;transform:none!important;width:auto;min-height:62px}
  }
  @media(max-width:560px){.dependency-graph{grid-template-columns:1fr}.graph-toolbar{align-items:flex-start;flex-direction:column}.ready-pill .bar{display:none}}

  .svc{display:flex;align-items:center;gap:10px;padding:8px 0;border-top:1px solid var(--grid)}
  .svc:first-of-type{border-top:none}
  .svc .ic{width:28px;height:28px;border-radius:50%;background:rgba(82,102,235,0.10);color:var(--accent);
           display:grid;place-items:center;font-size:10px;font-weight:480;flex:none}
  .svc .nm{font-size:13px;font-weight:420}
  .svc .n{margin-left:auto;font-size:12px;color:var(--ink-2);font-variant-numeric:tabular-nums}
  .svc .n.clear{color:var(--ink-3)}

  .status{display:inline-flex;align-items:center;gap:8px;font-size:12px;color:var(--ink-2);
          background:var(--surface);border:1px solid var(--hairline);border-radius:999px;padding:6px 14px}
  .status.quiet{color:var(--ink-3)}
  .spin{width:13px;height:13px;border:2px solid var(--accent-soft);border-top-color:var(--accent);
        border-radius:50%;animation:spin .8s linear infinite;flex:none}
  @keyframes spin{to{transform:rotate(360deg)}}
  .loading-hero{display:flex;flex-direction:column;align-items:center;gap:16px;padding:110px 0;color:var(--ink-2)}
  .loading-hero .spin{width:34px;height:34px;border-width:3px}
  .loading-hero .what{font-size:14px;font-weight:480}
  .loading-hero .why{font-size:12px;color:var(--ink-3)}
  #wiretrace{display:flex;flex-direction:column;max-height:340px;overflow:auto}
  #wiretrace .w{font-family:ui-monospace,monospace;font-size:10.5px;color:var(--ink-2);
                display:flex;gap:6px;align-items:baseline;padding:5px 0;border-top:1px solid var(--grid)}
  #wiretrace .w:first-child{border-top:none}
  #wiretrace .t{color:var(--ink-3);flex:none;font-variant-numeric:tabular-nums}
  #wiretrace .m{font-weight:600;flex:none}
  #wiretrace .m.post{color:var(--accent)}
  #wiretrace .a{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
  #wiretrace .st{margin-left:auto;flex:none;color:var(--ink-3)}
  #wiretrace .st.bad{color:var(--critical)}
</style></head><body>
<div class="app">
  <aside class="sidebar">
    <div class="brand"><div class="mark">H</div>
      <div><div class="name">Homeward</div><div class="sub">discharge coordination</div></div></div>
    <div class="nav-item active">Ward round</div>
    <div class="nav-item" onclick="openModal('trace')">Full trace</div>
    <div class="foot">world <b id="world">—</b><br>sim clock <b id="clock">—</b></div>
  </aside>
  <main class="main">
    <div class="header">
      <div><h1>Ward round</h1>
        <div class="subtitle">Barriers detected from the record · resolved in the owning service · verified after time moves</div></div>
      <span id="status"></span>
      <button class="primary" id="approveBtn" style="display:none" onclick="approve()">Approve plan</button>
    </div>
    <div class="kpis" id="kpis"></div>
    <div class="content">
      <div id="board"></div>
      <div class="rail">
        <div class="card story" id="story" style="display:none">
          <h2>Same ward, twice <span class="t" id="storyClock">—</span></h2>
          <div class="counters" id="counters"></div>
          <div class="lane"><div class="lane-head">Today&rsquo;s ward <span class="note">illustrative model</span><span class="n" id="laneBaselineN"></span></div>
            <div class="track" id="laneBaseline"><span class="end bed" title="in a hospital bed"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 18V8M3 14h18v4M21 14v-3a2 2 0 0 0-2-2h-8v5M3 18h18"/><circle cx="7" cy="10.5" r="1.6"/></svg></span><span class="end home" title="home"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 11.5 12 4l9 7.5M5 10v10h5v-5h4v5h5V10"/></svg></span></div></div>
          <div class="lane"><div class="lane-head">With Homeward <span class="note" id="laneAgentNote">live simulator world</span><span class="n" id="laneAgentN"></span></div>
            <div class="track" id="laneAgent"><span class="end bed" title="in a hospital bed"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 18V8M3 14h18v4M21 14v-3a2 2 0 0 0-2-2h-8v5M3 18h18"/><circle cx="7" cy="10.5" r="1.6"/></svg></span><span class="end home" title="home"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 11.5 12 4l9 7.5M5 10v10h5v-5h4v5h5V10"/></svg></span></div></div>
          <div class="story-foot"><button class="ghost" id="replayBtn" onclick="replayStory(false)" title="Replay from fit to the model horizon · double-click to follow the live clock again">Replay</button>
            <input type="range" id="scrub" min="0" max="100" step="1" value="100" oninput="scrubStory(this.value)" aria-label="story time">
            <span class="tl" id="scrubLabel">now</span></div>
          <div class="disclaimer" id="storyNote"></div>
        </div>
        <div class="card"><h2>Services</h2><div id="services"></div></div>
        <div class="card log-card" id="audit"><h2>Trace <span style="font-size:11px;color:var(--ink-3);font-weight:420">· live, newest first</span></h2><div id="wiretrace"></div></div>
      </div>
    </div>
  </main>
</div>
<div class="modal-backdrop" id="modal" onclick="if (event.target === this) closeModal()">
  <div class="modal" role="dialog" aria-modal="true" aria-labelledby="modalTitle">
    <div class="modal-head"><div><h2 id="modalTitle"></h2><div class="sub" id="modalSub"></div></div>
      <div class="legend"><span><span class="tag rec">record</span> from the sim record</span>
        <span><span class="tag ai">AI</span> model-written</span>
        <span><span class="tag sim">sim</span> service response</span></div>
      <button class="confirm" onclick="closeModal()">Close</button></div>
    <div id="modalBody"></div>
  </div>
</div>
<script>
const CAVEATS = ${JSON.stringify(CAVEATS)}
const caveatFor = (id) => { const e = Object.entries(CAVEATS).find(([k]) => id.endsWith('-' + k)); return e && e[1] }
const META = {
  proposed:               { label: 'Not started', color: '#a5a39c' },
  approved:               { label: 'In progress', color: 'var(--warning)' },
  resolving:              { label: 'Working',    color: 'var(--warning)' },
  awaiting_verification:  { label: 'Verifying',  color: 'var(--warning)' },
  verified:               { label: 'Completed',  color: 'var(--good)' },
  failed:                 { label: 'Stuck',      color: 'var(--critical)' },
  clinical_hold:          { label: 'Clinical hold', color: 'var(--critical)' },
  blocked_human:          { label: 'Human decision', color: 'var(--critical)' },
}
const SERVICES = {
  gp: 'GP Records', hospital: 'Hospital EPR', pharmacy: 'Pharmacy', community: 'Community Care',
  diagnostics: 'Diagnostics', wearables: 'Home Health', clinician: 'Clinician',
}
const OWNER_LABEL = {
  gp: 'GP', hospital: 'Hospital', pharmacy: 'Pharmacy', community: 'Community',
  diagnostics: 'Diagnostics', wearables: 'Home Health', clinician: 'Clinician',
}
const OPEN = ['proposed','approved','resolving','awaiting_verification','failed']
const esc = (s) => String(s ?? '').replace(/[&<>"]/g, (c) => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))
const q = (s) => esc(String(s ?? '').replace(/"/g, ''))
const chip = (state) => {
  const m = META[state] || { label: state, color: 'var(--ink-3)' }
  return '<span class="chip"><span class="dot" style="background:' + m.color + '"></span>' + m.label + '</span>'
}
const GRAPH_STATE = {
  proposed:              { key: 'not-started', label: 'Not started', color: '#a5a39c' },
  approved:              { key: 'in-progress', label: 'In progress', color: 'var(--warning)' },
  resolving:             { key: 'in-progress', label: 'In progress', color: 'var(--warning)' },
  awaiting_verification: { key: 'in-progress', label: 'In progress', color: 'var(--warning)' },
  failed:                { key: 'stuck', label: 'Stuck', color: 'var(--critical)' },
  clinical_hold:         { key: 'stuck', label: 'Stuck', color: 'var(--critical)' },
  blocked_human:         { key: 'stuck', label: 'Stuck', color: 'var(--critical)' },
  verified:              { key: 'completed', label: 'Completed', color: 'var(--good)' },
}
const graphState = (state) => GRAPH_STATE[state] || GRAPH_STATE.proposed
let expandedPatientId = null
let initialExpansionSet = false
function togglePatient(id) {
  expandedPatientId = expandedPatientId === id ? null : id
  if (lastState) render(lastState)
}
const taskTitle = (item) => {
  const id = item.id.toLowerCase()
  if (id.endsWith('clinical-hold')) return 'Clinical review'
  if (id.endsWith('medicines')) return 'Discharge medicines'
  if (id.endsWith('bloods')) return 'Blood monitoring'
  if (id.endsWith('device')) return 'Home monitoring'
  if (id.endsWith('visit')) return 'Home support visit'
  if (id.endsWith('summary')) return 'Discharge summary'
  if (id.endsWith('follow-up')) return 'GP follow-up'
  if (id.endsWith('care-package')) return 'Care package'
  return item.title
}
function graphForPatient(p) {
  const count = Math.max(p.items.length, 1)
  const positions = p.items.map((_, index) => {
    const angle = (-Math.PI / 2) + (index * Math.PI * 2 / count)
    return { x: 50 + Math.cos(angle) * 33, y: 50 + Math.sin(angle) * 36 }
  })
  const lines = p.items.map((i, index) => {
    const pos = positions[index]
    return '<line x1="50%" y1="50%" x2="' + pos.x.toFixed(2) + '%" y2="' + pos.y.toFixed(2) +
      '%" style="stroke:' + graphState(i.state).color + '" />'
  }).join('')
  const nodes = p.items.map((i, index) => {
    const pos = positions[index]
    const state = graphState(i.state)
    const label = taskTitle(i)
    const action = i.state === 'clinical_hold'
      ? '<button class="node-action" data-id="' + esc(i.id) + '" onclick="event.stopPropagation();clearHold(this.dataset.id)">Confirm reviewed</button>'
      : (i.state === 'blocked_human' && !i.escalation
        ? '<button class="node-action" data-id="' + esc(i.id) + '" onclick="event.stopPropagation();escalate(this.dataset.id)">Prepare escalation</button>'
        : '')
    return '<div class="graph-node ' + state.key + '" role="button" tabindex="0" data-id="' + esc(i.id) + '" ' +
      'aria-label="' + q((OWNER_LABEL[i.owner] || i.owner) + ': ' + label + '. ' + state.label) + '" title="' + q(i.title) + '" ' +
      'style="left:' + pos.x.toFixed(2) + '%;top:' + pos.y.toFixed(2) + '%" ' +
      'onclick="itemStory(this.dataset.id)" onkeydown="if(event.keyCode===13||event.keyCode===32){event.preventDefault();itemStory(this.dataset.id)}">' +
      '<div class="node-top"><span class="node-owner">' + (OWNER_LABEL[i.owner] || esc(i.owner)) + '</span></div>' +
      '<div class="node-title">' + esc(label) + '</div>' + action + '</div>'
  }).join('')
  const insights = (p.insights || []).length
    ? '<div class="graph-insights"><b>Agent observations:</b> ' + p.insights.map((n) => esc(n.title)).join(' · ') + '</div>'
    : ''
  return '<div class="graph-wrap"><div class="graph-toolbar"><span class="graph-title">Discharge dependencies</span>' +
    '<span class="legend"><span><i style="background:#a5a39c"></i>Not started</span>' +
    '<span><i style="background:var(--warning)"></i>In progress</span>' +
    '<span><i style="background:var(--critical)"></i>Stuck</span>' +
    '<span><i style="background:var(--good)"></i>Completed</span></span></div>' +
    '<div class="dependency-graph"><svg class="dependency-lines" aria-hidden="true">' + lines + '</svg>' +
    '<div class="graph-hub" aria-hidden="true"><span class="person"></span></div>' + nodes + '</div>' + insights + '</div>'
}
const history = []
const spark = () => {
  if (history.length < 2) return ''
  const max = Math.max(...history, 1)
  const pts = history.map((v, i) =>
    (i / (history.length - 1) * 100).toFixed(1) + ',' + (26 - (v / max) * 22).toFixed(1)).join(' ')
  return '<svg viewBox="0 0 100 30" preserveAspectRatio="none">' +
    '<polygon points="0,30 ' + pts + ' 100,30" fill="rgba(82,102,235,0.10)"/>' +
    '<polyline points="' + pts + '" fill="none" stroke="var(--accent)" stroke-width="1.5" vector-effect="non-scaling-stroke"/></svg>'
}
const kpi = (key, label, value, hint, extra) =>
  '<div class="kpi' + (extra ? ' has-spark' : '') + '" role="button" tabindex="0" onclick="openModal(\\'' + key + '\\')" ' +
  'onkeydown="if (event.key === \\'Enter\\' || event.key === \\' \\') { event.preventDefault(); openModal(\\'' + key + '\\') }">' +
  '<span class="more">details</span><div class="label">' + label + '</div><div class="value">' + value + '</div>' +
  (hint ? '<div class="hint">' + hint + '</div>' : '') + (extra || '') + '</div>'

// --- KPI detail modal: what the agent is doing behind each number ------------
const CATS = {
  ward:  { title: 'On the ward',        sub: 'every tracked patient and their full checklist',
           patients: (s) => s.patients, items: (p) => p.items },
  ready: { title: 'Ready to discharge', sub: 'patients with every item verified',
           patients: (s) => s.patients.filter((p) => p.items.length && p.items.every((i) => i.state === 'verified')), items: (p) => p.items },
  open:  { title: 'Open barriers',      sub: 'items the agent is proposing, working or verifying',
           patients: (s) => s.patients, items: (p) => p.items.filter((i) => OPEN.includes(i.state)) },
  human: { title: 'Awaiting a human',   sub: 'clinical holds and external decisions automation must not touch',
           patients: (s) => s.patients, items: (p) => p.items.filter((i) => i.state === 'clinical_hold' || i.state === 'blocked_human') },
}
let lastState = null
let openKey = null
const when = (ms) => ms ? new Date(ms).toISOString().slice(0, 16).replace('T', ' ') : ''
const itemDetail = (i, log) => {
  const d = []
  if (i.proposedAction && (i.state === 'proposed' || i.state === 'approved')) d.push('<b>Plan:</b> ' + esc(i.proposedAction))
  if (i.approval) d.push('<b>Approved</b> by ' + esc(i.approval.by) + (i.approval.at ? ' at ' + when(i.approval.at) : ''))
  if (i.humanReason) d.push('<b>Why a human:</b> ' + esc(i.humanReason))
  if (i.resolution) d.push('<b>Agent did:</b> ' + esc(i.resolution.action) + ' &rarr; <code>' + esc(i.resolution.resourceId) + '</code>' +
    (i.resolution.atSimTime ? ' at ' + when(i.resolution.atSimTime) : '') + ' <code>key ' + esc(i.resolution.idempotencyKey) + '</code>')
  if (i.verification) d.push('<b>' + (i.verification.passed ? 'Verified:' : 'Checked, not yet:') + '</b> ' + esc(i.verification.observed) +
    (i.verification.atSimTime ? ' at ' + when(i.verification.atSimTime) : ''))
  if (i.error) d.push('<b class="err">Error:</b> <span class="err">' + esc(i.error) + '</span>')
  if (i.escalation) d.push('<b>Escalated to</b> ' + esc(i.escalation.responsibleTeam) + ' &mdash; ' + esc(i.escalation.nextAction) + '<br>' + esc(i.escalation.note))
  for (const e of i.evidence || []) d.push('<span class="tag rec">record</span> &ldquo;' + q(e.quote) + '&rdquo; <code>' + esc(e.site) + ' ' + esc(e.resourceId) + '</code>')
  const logLines = (log || []).filter((l) => l.includes(i.id)).slice(-3)
  for (const l of logLines) d.push('<span class="trace">' + esc(l) + '</span>')
  const wire = ((lastState && lastState.trace) || []).filter((t) => t.idempotencyKey && t.idempotencyKey.includes(i.id)).slice(-6)
  for (const t of wire) d.push(wireRow(t, false))
  return d.length ? '<div class="detail">' + d.map((x) => '<div>' + x + '</div>').join('') + '</div>' : ''
}
const prettyJson = (raw) => { try { return JSON.stringify(JSON.parse(raw), null, 1) } catch { return raw } }
const railWire = (t) =>
  '<div class="w"><span class="t">' + new Date(t.at).toTimeString().slice(0, 8) + '</span>' +
  '<span class="m' + (t.method === 'POST' ? ' post' : '') + '">' + esc(t.method) + '</span>' +
  '<span class="a">' + esc(t.action || t.path.split('?')[0].replace('/api/', '')) + '</span>' +
  '<span class="st' + (t.ok ? '' : ' bad') + '">' + (t.status || 'ERR') + '</span></div>'
const renderRailTrace = (s) =>
  (document.getElementById('wiretrace').innerHTML =
    ((s.trace || []).slice(-40).reverse().map(railWire).join('')) || '<div class="empty">No calls yet.</div>')
const wireRow = (t, withPayload) =>
  '<div class="call"><div class="head">' +
  '<span class="t">' + new Date(t.at).toTimeString().slice(0, 8) + '</span>' +
  '<span class="m' + (t.method === 'GET' ? ' get' : '') + '">' + esc(t.method) + '</span>' +
  '<span class="a">' + esc(t.action || t.path.split('?')[0]) + '</span>' +
  '<span class="' + (t.ok ? 'ok' : 'fail') + '">' + (t.ok ? 'HTTP ' + t.status : 'FAILED ' + (t.status || '')) + '</span>' +
  (t.got ? '<span><span class="tag sim">sim</span> ' + esc(t.got) + '</span>' : '') + '</div>' +
  (withPayload && t.sent ? '<div class="meta" style="margin-top:8px">agent sent:</div><pre style="margin-top:4px">' + esc(prettyJson(t.sent)) + '</pre>' : '') +
  (withPayload && t.idempotencyKey ? '<div class="meta">idempotency key · ' + esc(t.idempotencyKey) + '</div>' : '') +
  '</div>'

function renderModal() {
  if (!lastState) return
  const s0 = lastState
  if (openKey === 'activity') {
    document.getElementById('modalTitle').textContent = s0.busy ? 'Working…' : 'Current activity'
    document.getElementById('modalSub').textContent = s0.phase || ''
    const recent = (s0.trace || []).slice(-15).reverse()
    document.getElementById('modalBody').innerHTML =
      '<div class="group"><h3>Most recent simulator calls <span>newest first · live</span></h3>' +
      (recent.length ? recent.map(wireRow).join('') : '<div class="empty">No calls yet.</div>') + '</div>' +
      '<div class="group"><h3>Recent activity log</h3>' +
      (s0.log || []).slice(-8).reverse().map((l) => '<div class="wire">' + esc(l) + '</div>').join('') + '</div>'
    return
  }
  if (openKey === 'trace') {
    const all = s0.trace || []
    const writes = all.filter((t) => t.method !== 'GET')
    document.getElementById('modalTitle').textContent = 'Full agent trace'
    document.getElementById('modalSub').textContent =
      all.length + ' simulator calls · ' + writes.length + ' writes · grouped by patient and task · every request, payload, idempotency key and response'
    const claimed = new Set()
    const forItem = (i) => all.filter((t) => t.idempotencyKey && t.idempotencyKey.includes(i.id)).map((t) => { claimed.add(t); return t })
    const html = []
    for (const p0 of s0.patients) {
      const parts = []
      for (const i of p0.items) {
        const rows = forItem(i)
        if (!rows.length) continue
        parts.push('<div class="mi"><div class="row">' + chip(i.state) + '<span class="owner">' + (OWNER_LABEL[i.owner] || esc(i.owner)) + '</span>' +
          '<span class="title">' + esc(i.title) + '</span></div>' + rows.map((t) => wireRow(t, true)).join('') + '</div>')
      }
      const reads = all.filter((t) => !claimed.has(t) && t.method === 'GET' &&
        (t.path.includes(p0.patientId) || (t.sent || '').includes(p0.patientId)))
      reads.forEach((t) => claimed.add(t))
      if (parts.length || reads.length) {
        html.push('<div class="group"><h3>' + esc(p0.name) + ' <span>' + esc(p0.patientId) + '</span></h3>' + parts.join('') +
          (reads.length ? '<div class="mi"><div class="row"><span class="owner">reads</span><span class="title">' + reads.length + ' record reads for this patient</span></div>' +
            reads.map((t) => wireRow(t, false)).join('') + '</div>' : '') + '</div>')
      }
    }
    const rest = all.filter((t) => !claimed.has(t))
    if (rest.length) {
      html.push('<div class="group"><h3>Run &amp; world <span>world setup, clock, un-attributed calls</span></h3>' +
        rest.map((t) => wireRow(t, t.method !== 'GET')).join('') + '</div>')
    }
    document.getElementById('modalBody').innerHTML = html.join('') || '<div class="empty">No calls yet.</div>'
    return
  }
  if (openKey && openKey.startsWith('item:')) {
    const id = openKey.slice(5)
    let found = null
    for (const p1 of s0.patients) { const i1 = p1.items.find((x) => x.id === id); if (i1) found = { p: p1, i: i1 } }
    if (!found) return
    const { p: p1, i } = found
    document.getElementById('modalTitle').textContent = i.title
    document.getElementById('modalSub').innerHTML = esc(p1.name) + ' · ' + (OWNER_LABEL[i.owner] || esc(i.owner)) + ' · ' + chip(i.state)
    const kv = (k, v) => '<div class="kv"><span class="k">' + k + '</span><span class="v">' + v + '</span></div>'
    const parts = []
    parts.push('<div class="group"><h3>Detected from the record</h3>' +
      ((i.evidence || []).map((e) =>
        kv('<span class="tag rec">record</span>', '&ldquo;' + q(e.quote) + '&rdquo; <code>' + esc(e.site) + ' ' + esc(e.resourceId) + '</code>')).join('') ||
        '<div class="empty">Rule-detected from structured state.</div>') + '</div>')
    parts.push('<div class="group"><h3>Plan &amp; approval</h3>' +
      (i.proposedAction ? kv('Plan', esc(i.proposedAction)) : '') +
      kv('Approval', i.approval ? 'Approved by ' + esc(i.approval.by) : 'Not yet — awaiting staff approval') +
      (i.humanReason ? kv('Needs a human', esc(i.humanReason)) : '') + '</div>')
    const wire = (s0.trace || []).filter((t) => t.idempotencyKey && t.idempotencyKey.includes(i.id))
    parts.push('<div class="group"><h3>Agent &harr; ' + (OWNER_LABEL[i.owner] || esc(i.owner)) + ' <span>' + wire.length + ' calls, oldest first</span></h3>' +
      (wire.length ? wire.map((t) => wireRow(t, true)).join('') : '<div class="empty">No actions sent yet.</div>') + '</div>')
    if (i.generated) parts.push('<div class="group"><h3>Drafting provenance</h3>' +
      kv(i.generated === 'model' ? '<span class="tag ai">AI</span>' : '<span class="err">⚠</span>',
        i.generated === 'model' ? 'The live model wrote the drafted content for this task' : 'Canned fallback used — model unavailable') + '</div>')
    if (i.verification) parts.push('<div class="group"><h3>Independent verification</h3>' +
      kv('<span class="tag sim">sim</span>', (i.verification.passed ? '<span style="color:var(--good);font-weight:480">✓ passed</span> — ' : '<span class="err">✗ not yet</span> — ') + esc(i.verification.observed)) +
      (caveatFor(i.id) ? kv('Does not prove', esc(caveatFor(i.id))) : '') + '</div>')
    if (i.escalation) parts.push('<div class="group"><h3>Escalation</h3>' +
      kv('<span class="tag ai">AI</span>', '<b>' + esc(i.escalation.responsibleTeam) + '</b> — ' + esc(i.escalation.nextAction)) +
      kv('Note', esc(i.escalation.note)) + '</div>')
    document.getElementById('modalBody').innerHTML = parts.join('')
    return
  }
  const cat = CATS[openKey]
  if (!cat) return
  const s = lastState
  document.getElementById('modalTitle').textContent = cat.title
  document.getElementById('modalSub').textContent = cat.sub
  const groups = cat.patients(s).map((p) => ({ p, items: cat.items(p) })).filter((g) => openKey === 'ward' || openKey === 'ready' || g.items.length)
  document.getElementById('modalBody').innerHTML = groups.length ? groups.map((g) =>
    '<div class="group"><h3>' + esc(g.p.name) + ' <span>' + esc(g.p.patientId) + ' · ' + esc(g.p.stage ?? '?') +
    (g.p.location ? ' · ' + esc(g.p.location) : '') + ' · ' + g.items.filter((i) => i.state === 'verified').length + ' of ' + g.items.length + ' verified</span></h3>' +
    (g.items.length ? g.items.map((i) =>
      '<div class="mi"><div class="row">' + chip(i.state) + '<span class="owner">' + (OWNER_LABEL[i.owner] || esc(i.owner)) + '</span>' +
      '<span class="title">' + esc(i.title) + '</span></div>' + itemDetail(i, s.log) + '</div>').join('')
      : '<div class="empty">No items in this category for this patient.</div>') + '</div>').join('')
    : '<div class="empty">Nothing here right now.</div>'
}
function openModal(key) {
  openKey = key
  renderModal()
  document.getElementById('modal').classList.add('open')
  document.querySelector('#modal button').focus()
}
function closeModal() {
  openKey = null
  document.getElementById('modal').classList.remove('open')
}
document.addEventListener('keydown', (e) => { if (e.key === 'Escape' && openKey) closeModal() })

function render(s) {
  lastState = s
  document.getElementById('world').textContent = s.world
  document.getElementById('clock').textContent = s.simNow ? new Date(s.simNow).toISOString().slice(0, 16).replace('T', ' ') : '—'
  document.getElementById('status').innerHTML = s.busy
    ? '<span class="status" role="button" style="cursor:pointer" onclick="openModal(\\'activity\\')"><span class="spin"></span>' + esc(s.phase || 'Calling the simulator…') + '</span>'
    : (s.phase ? '<span class="status quiet" role="button" style="cursor:pointer" onclick="openModal(\\'activity\\')">' + esc(s.phase) + '</span>' : '')
  if (!s.patients.length) {
    document.getElementById('kpis').innerHTML = ''
    document.getElementById('board').innerHTML =
      '<div class="card"><div class="loading-hero"><span class="spin"></span>' +
      '<div class="what">' + esc(s.phase || 'Setting up the demo world…') + '</div>' +
      '<div class="why">Live calls against the NHS-SIM simulator — the ward list appears as records load.</div></div></div>'
    document.getElementById('services').innerHTML = ''
    renderStory(s)
    renderRailTrace(s)
    return
  }
  const all = s.patients.flatMap((p) => p.items)
  const ready = s.patients.filter((p) => p.items.length && p.items.every((i) => i.state === 'verified')).length
  const open = all.filter((i) => OPEN.includes(i.state)).length
  const human = all.filter((i) => i.state === 'clinical_hold' || i.state === 'blocked_human').length
  if (history[history.length - 1] !== open) history.push(open)
  if (history.length > 60) history.shift()
  document.getElementById('kpis').innerHTML =
    kpi('ward', 'On the ward', s.patients.length, 'tracked patients') +
    kpi('ready', 'Ready to discharge', ready, 'every item verified') +
    kpi('open', 'Open barriers', open, 'agent is working these', spark()) +
    kpi('human', 'Awaiting a human', human, 'holds + external decisions')
  if (openKey) renderModal()

  const proposed = all.filter((i) => i.state === 'proposed').length
  const btn = document.getElementById('approveBtn')
  btn.style.display = proposed ? '' : 'none'
  btn.textContent = 'Approve plan (' + proposed + ')'

  if (!initialExpansionSet && s.patients.length) {
    expandedPatientId = s.patients[0].patientId
    initialExpansionSet = true
  }
  if (expandedPatientId && !s.patients.some((p) => p.patientId === expandedPatientId)) expandedPatientId = null
  document.getElementById('board').innerHTML = s.patients.map((p) => {
    const done = p.items.filter((i) => i.state === 'verified').length
    const pct = p.items.length ? Math.round((100 * done) / p.items.length) : 0
    const initials = esc(p.name).split(' ').map((w) => w[0]).slice(0, 2).join('')
    const expanded = expandedPatientId === p.patientId
    return '<section class="card patient-card' + (expanded ? ' expanded' : '') + '">' +
      '<button type="button" class="patient-head" data-patient="' + esc(p.patientId) + '" aria-expanded="' + expanded + '" ' +
      'aria-controls="patient-graph-' + esc(p.patientId) + '" onclick="togglePatient(this.dataset.patient)">' +
      '<div class="avatar">' + initials + '</div>' +
      '<div><div class="patient-name">' + esc(p.name) + '</div>' +
      '<div class="patient-meta">' + esc(p.patientId) + ' · ' + esc(p.stage ?? '?') +
      (p.location ? ' · ' + esc(p.location) : '') + ' · ' + esc((p.conditions || []).join(', ')) + '</div></div>' +
      '<div class="ready-pill"><span class="count">' + done + ' of ' + p.items.length + ' verified</span>' +
      '<span class="bar"><i style="width:' + pct + '%"></i></span><span class="chevron" aria-hidden="true">⌄</span></div></button>' +
      (expanded ? '<div id="patient-graph-' + esc(p.patientId) + '">' + graphForPatient(p) + '</div>' : '') + '</section>'
  }).join('')

  document.getElementById('services').innerHTML = Object.entries(SERVICES).map(([key, name]) => {
    const n = all.filter((i) => i.owner === key && i.state !== 'verified').length
    const initials = name.split(' ').map((w) => w[0]).slice(0, 2).join('')
    return '<div class="svc"><span class="ic">' + initials + '</span><span class="nm">' + name + '</span>' +
      '<span class="n' + (n ? '' : ' clear') + '">' + (n ? n + ' open' : 'clear') + '</span></div>'
  }).join('')

  renderStory(s)
  renderRailTrace(s)
}
// --- The story: the same ward twice ------------------------------------------
// Lanes are timelines from /state.story. storyT is the sim time the lanes are
// drawn at (null = follow the live clock). The agent lane is only known up to
// now; past that it holds and the label says "projected".
let storyT = null
let storyAnim = null
const prevDone = {}
const RING = 2 * Math.PI * 12.5
const rel = (ms, fitAt) => {
  const m = Math.max(0, Math.round((ms - fitAt) / 60000))
  const d = Math.floor(m / 1440), h = Math.floor((m % 1440) / 60)
  return '+' + (d ? d + 'd ' : '') + h + 'h ' + String(m % 60).padStart(2, '0') + 'm'
}
// Mirrors countersAt() in src/story/story.ts.
const storyCounters = (patients, t, now) => {
  const tAgent = Math.min(t, now)
  let bedsFreed = 0, homeModel = 0, saved = 0
  for (const p of patients) {
    const a = p.agent.homeAt, b = p.baseline.homeAt
    if (a !== null && a <= tAgent) { bedsFreed++; if (b !== null) saved += Math.max(0, b - a) }
    if (b !== null && b <= t) homeModel++
  }
  return { bedsFreed, homeModel, bedHoursSaved: Math.round(saved / 3600000 * 10) / 10 }
}
const laneAt = (lane, t) => {
  const done = lane.items.filter((i) => i.doneAt !== null && i.doneAt <= t).length
  const home = lane.homeAt !== null && lane.homeAt <= t
  return { done, total: lane.items.length, home, frac: lane.items.length ? done / lane.items.length : 0 }
}
function renderLane(trackId, key, patients, laneOf, t, fitAt, live) {
  const track = document.getElementById(trackId)
  const rows = patients.map((p) => ({ p, lane: laneOf(p), at: laneAt(laneOf(p), t) }))
  // Spread avatars that share a position so none hides another.
  const groups = {}
  rows.forEach((r) => { const g = r.at.home ? 'home' : String(Math.round(r.at.frac * 6)); (groups[g] = groups[g] || []).push(r) })
  const seen = new Set()
  let homeCount = 0
  for (const g of Object.values(groups)) {
    g.forEach((r, idx) => {
      const id = key + ':' + r.p.patientId
      seen.add(id)
      let el = track.querySelector('[data-key="' + id + '"]')
      if (!el) {
        el = document.createElement('div')
        el.className = 'av'
        el.dataset.key = id
        el.innerHTML = '<svg viewBox="0 0 30 30" aria-hidden="true"><circle class="ring-bg" cx="15" cy="15" r="12.5"/>' +
          '<circle class="ring" cx="15" cy="15" r="12.5" stroke-dasharray="' + RING.toFixed(2) + '" stroke-dashoffset="' + RING.toFixed(2) + '"/></svg>' +
          '<span class="ini">' + esc(r.p.name).split(' ').map((w) => w[0]).slice(0, 2).join('') + '</span>'
        track.appendChild(el)
      }
      const blocked = !!r.lane.blockedBy && !r.at.home
      const flash = prevDone[id] !== undefined && r.at.done > prevDone[id]
      prevDone[id] = r.at.done
      if (r.at.home) homeCount++
      el.className = 'av' + (r.at.home ? ' home' : blocked ? ' blocked' : r.at.done ? '' : ' idle') + (flash ? ' flash' : '')
      el.style.left = (r.at.home ? 100 : 5 + r.at.frac * 83).toFixed(1) + '%'
      el.style.marginTop = ((idx - (g.length - 1) / 2) * 18).toFixed(0) + 'px'
      el.querySelector('.ring').setAttribute('stroke-dashoffset', (RING * (1 - r.at.frac)).toFixed(2))
      el.title = r.p.name + ' · ' + r.at.done + ' of ' + r.at.total + ' done' +
        (r.at.home ? ' · home ' + rel(r.lane.homeAt, fitAt) : blocked ? ' · waiting on a human decision' : (live && t > 0 ? '' : '')) +
        (r.lane.missedPolls ? ' · ' + r.lane.missedPolls + ' missed inbox check' + (r.lane.missedPolls > 1 ? 's' : '') : '')
    })
  }
  track.querySelectorAll('.av').forEach((el) => { if (!seen.has(el.dataset.key)) el.remove() })
  track.querySelector('.end.home').classList.toggle('lit', homeCount > 0)
  return homeCount
}
function renderStory(s) {
  const st = s.story
  const card = document.getElementById('story')
  if (!st || !st.patients.length) { card.style.display = 'none'; return }
  card.style.display = ''
  const t = storyT === null ? st.now : Math.min(Math.max(storyT, st.fitAt), st.horizon)
  const clock = document.getElementById('storyClock')
  clock.textContent = rel(t, st.fitAt) + (t > st.now ? ' · projected' : t < st.now ? ' · replay' : ' · now')
  clock.className = 't' + (t > st.now ? ' proj' : '')
  const c = storyCounters(st.patients, t, st.now)
  document.getElementById('counters').innerHTML =
    '<div class="counter" title="beds the agent world has freed"><div class="v">' + c.bedsFreed + '</div><div class="l">beds freed</div></div>' +
    '<div class="counter" title="for each bed freed: when the manual model would free it, minus when the agent did"><div class="v">' + c.bedHoursSaved + '<small> h</small></div><div class="l">bed-hours saved<br>vs model</div></div>' +
    '<div class="counter" title="patients home: agent world / manual model"><div class="v">' + c.bedsFreed + '<small> / ' + c.homeModel + '</small></div><div class="l">home<br>agent / model</div></div>'
  const nB = renderLane('laneBaseline', 'b', st.patients, (p) => p.baseline, t, st.fitAt, false)
  const nA = renderLane('laneAgent', 'a', st.patients, (p) => p.agent, Math.min(t, st.now), st.fitAt, true)
  document.getElementById('laneBaselineN').textContent = nB + ' of ' + st.patients.length + ' home'
  document.getElementById('laneAgentN').textContent = nA + ' of ' + st.patients.length + ' home'
  document.getElementById('laneAgentNote').textContent = t > st.now ? 'live world · as of now' : 'live simulator world'
  const scrub = document.getElementById('scrub')
  scrub.min = st.fitAt; scrub.max = st.horizon; scrub.step = 60000
  if (document.activeElement !== scrub) scrub.value = t
  document.getElementById('scrubLabel').textContent = storyT === null ? 'now' : rel(t, st.fitAt)
  const pm = st.params.pollMinutes
  document.getElementById('storyNote').innerHTML =
    '<b>Today&rsquo;s ward</b> is an illustrative model, not a measurement: the same checklist, each team checking its inbox on its own cadence ' +
    '(pharmacy ' + pm.pharmacy + ' min, results ' + pm.diagnostics + ', letter ' + pm.hospital + ', community ' + pm.community + ', GP ' + pm.gp + '), ' +
    'jobs started one after another, ' + Math.round(st.params.dropProbability * 100) + '% of checks missing the job, discharge at the next ward round. ' +
    '<b>With Homeward</b> is what the agent actually did in the simulator, read back and verified. Patients are synthetic.'
}
function scrubStory(v) {
  if (storyAnim) { cancelAnimationFrame(storyAnim); storyAnim = null }
  storyT = Number(v)
  if (lastState) renderStory(lastState)
}
function replayStory(loop) {
  const st = lastState && lastState.story
  if (!st) return
  if (storyAnim) cancelAnimationFrame(storyAnim)
  const from = st.fitAt, to = st.horizon, duration = 12000
  const start = performance.now()
  const step = (ts) => {
    const k = Math.min(1, (ts - start) / duration)
    storyT = from + (to - from) * k
    if (lastState) renderStory(lastState)
    if (k < 1) storyAnim = requestAnimationFrame(step)
    else { storyAnim = null; if (loop) setTimeout(() => replayStory(true), 2500) }
  }
  storyAnim = requestAnimationFrame(step)
}
document.getElementById('replayBtn').addEventListener('dblclick', () => { storyT = null; if (storyAnim) cancelAnimationFrame(storyAnim); storyAnim = null; if (lastState) renderStory(lastState) })
// ?attract=1 loops the replay for passers-by at the stall.
if (new URLSearchParams(location.search).get('attract')) {
  const waitForStory = setInterval(() => { if (lastState && lastState.story && lastState.story.patients.length) { clearInterval(waitForStory); replayStory(true) } }, 1000)
}

async function tick() { try { render(await (await fetch('/state')).json()) } catch {} }
function itemStory(id) { openModal('item:' + id) }
async function clearHold(id) { await fetch('/clear-hold?item=' + encodeURIComponent(id), { method: 'POST' }); tick() }
async function approve() { await fetch('/approve', { method: 'POST' }); tick() }
async function escalate(id) {
  const btn = event?.target
  if (btn) { btn.textContent = 'Drafting…'; btn.disabled = true }
  await fetch('/escalate?item=' + encodeURIComponent(id), { method: 'POST' })
  tick()
}
setInterval(tick, 1500); tick()
</script></body></html>`

export function startUi(board: BoardState, port = 4600): void {
  const server = createServer((req, res) => {
    const url = new URL(req.url ?? '/', 'http://localhost')
    if (url.pathname === '/state') {
      res.setHeader('content-type', 'application/json')
      let story: unknown = null
      try { story = computeStory(board) } catch (err) { console.error(`story: ${String((err as Error).message)}`) }
      res.end(JSON.stringify({ ...board, story }))
    } else if (url.pathname === '/clear-hold' && req.method === 'POST') {
      const ok = clearHold(board, url.searchParams.get('item') ?? '', 'Demo clinician')
      res.statusCode = ok ? 200 : 404
      res.end(ok ? 'cleared' : 'not found')
    } else if (url.pathname === '/approve' && req.method === 'POST') {
      const n = approveAll(board, 'Demo coordinator', url.searchParams.get('patient') || undefined)
      res.end(String(n))
    } else if (url.pathname === '/receipt') {
      const md = buildReceipt(board, url.searchParams.get('patient') ?? '')
      if (!md) { res.statusCode = 404; res.end('unknown patient'); return }
      res.setHeader('content-type', 'text/markdown; charset=utf-8')
      res.setHeader('content-disposition', `attachment; filename="homeward-receipt-${url.searchParams.get('patient')}.md"`)
      res.end(md)
    } else if (url.pathname === '/escalate' && req.method === 'POST') {
      prepareEscalation(board, url.searchParams.get('item') ?? '').then((ok) => {
        res.statusCode = ok ? 200 : 404
        res.end(ok ? 'escalated' : 'not found')
      })
    } else {
      res.setHeader('content-type', 'text/html')
      res.end(PAGE)
    }
  })
  server.on('error', (err: NodeJS.ErrnoException) => {
    if (err.code === 'EADDRINUSE') {
      console.error(`port ${port} is busy (an older run?) — retrying every 2s; this run's UI will take over as soon as it frees up`)
      setTimeout(() => server.listen(port, '127.0.0.1'), 2000)
    } else throw err
  })
  server.listen(port, '127.0.0.1', () => console.log(`ward list: http://localhost:${port} (localhost only)`))
}
